### ISSUE TITLE
Error updating to Artifactory HA chart 2.6.0+ with external DB and custom secrets

### ISSUE THREAD

**Issue by erick-duran** [jfrog/charts#1001]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug?

**Version of Helm and Kubernetes**:
Helm 3.2.4
Kubernetes 1.15.11

**Which chart**:
Artifactory HA

**What happened**:
Upgrading from chart v2.5.7 to v2.6.0 and higher versions results in status `Init:CreateContainerConfigError`. The error from describing the pod is: `Error: secret "<release-name>-artifactory-ha-database-creds" not found`. We currently use a custom secret to set up the database credentials. Here are my DB related values:

```yaml
database:
  driver: org.postgresql.Driver
  secrets:
    password:
      key: password
      name: psql-secret
    user:
      key: user
      name: psql-secret
  type: postgresql
  url: <db-url>
postgresql:
  enabled: false
```

**What you expected to happen**:
Upgrade to new chart version.

**How to reproduce it** (as minimally and precisely as possible):
- Install on chart version 2.5.7 and reference custom secrets. 
- Upgrade to latest chart.

**Anything else we need to know**:
Asking for the suggested procedure to perform the upgrade. I noticed in the changelog that the DB template changes shouldn't affect users with external DBs, so just wondering if I'm missing something.

Also happens when manually deleting the release and performing an install.
