### ISSUE TITLE
artifactory-nginx pod fails to start

### ISSUE THREAD

**Issue by yug0slav** [jfrog/charts#1068]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
k8s: "1.16.10"
helm "v3.2.4"

**Which chart**:
center/jfrog/artifactory

**What happened**:
trying to deploy artifactory-pro on k8s. Artifactory-nginx pod fails: CrashLoopBackOff

pod logs
```
2020-08-12T17:46:18.881323288Z standard_init_linux.go:211: exec user process caused "operation not permitted"
```

**What you expected to happen**:
pod starts normally

**How to reproduce it** (as minimally and precisely as possible):
 helm -n jfrog install artifactory center/jfrog/artifactory -f values.yaml
- postgres desabled
- ingress enabled (with tls)

**Anything else we need to know**:

**Comment by chukka** [comment]
@yug0slav Can you please share the reproducible steps with values.yaml  and complete logs to debug further

**Comment by yug0slav** [comment]
Missed this part in the docs for ingress with TLS:
```
  ingress:
    enabled: true
    hosts:
      - artifactory.company.com
  artifactory:
    service:
      type: NodePort
  nginx
    enabled: false
```
