### ISSUE TITLE
PostgreSQL PersistentVolumeClaim (PVC) is getting deleted

### ISSUE THREAD

**Issue by JihadMotii-REISys** [jfrog/charts#1105]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 1.17

**Which chart**: jfrog/artifactory

**What happened**: PersistentVolumeClaim (PVC) for postgresql initially gets created through ArgoCD then it gets deleted

**What you expected to happen**: If the postgresql is enabled then the chart should provision PVC (50Gi) which will be used by PostgreSQL Pod

**How to reproduce it** (as minimally and precisely as possible):

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-artifactory
  namespace: argocd
spec:
  destination:
    namespace: build
    server: https://kubernetes.default.svc
  project: {{ .Values.project }}
  source:
    chart: jfrog/artifactory
    helm:
      values: |
        artifactory:
          persistence:
            size: 500Gi
            maxCacheSize: 50000000000
          license:
            licenseKey: |-
              cHJXXXXXXXXXXX.....
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "6"
        javaOpts:
          xms: "4g"
          xmx: "6g"
        postgresql:
          enabled: true
          postgresqlPassword: "MY_PASSWD"
          persistence:
            enabled: true
            size: 50Gi
        nginx:
          enabled: false
        ingress:
          enabled: true
          hosts:
            - jfrog.mydomain.com
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt
          tls:
            - secretName: jfrog.mydomain.com
              hosts:
                - jfrog.mydomain.com
    repoURL: https://repo.chartcenter.io
    targetRevision: 11.0.1 # JFrog Artifactory V7.7.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
```

**Anything else we need to know**:

**Comment by chukka** [comment]
@JihadMotii-REISys when does PVC gets deleted ? is it on helm upgrade ? Can you please share the reproducible steps ?
Also share K8s platform you are using (GKE/EKS/Rancher/Openshift) ?

**Comment by JihadMotii-REISys** [comment]
@chukka Sure
**Is it on helm upgrade?:** 
yes, when you install this chart either through helm command line (as mentioned in the chart [README](https://github.com/jfrog/charts/tree/master/stable/artifactory)) or through ArgoCD.

**when does PVC gets deleted?:** 
This PVC gets deleted right after it gets created. When argocd provision or when you execute helm upgrade to install this jfrog chart (with values mentioned above), I can see in the ArgoCD UI that this PVC got created but 1-2 seconds later, it gets deleted. looks like something deprovision it or removes it.

 **Also share K8s platform you are using (GKE/EKS/Rancher/Openshift) ?:** 
I'm using EKS/Rancher but i'm not deploying anything through Rancher.

**Can you please share the reproducible steps ?:** 
Producing this issue using Helm would be simply following the instruction in the [README](https://github.com/jfrog/charts/tree/master/stable/artifactory)) except you would need to provide this `values.yaml` :

```
artifactory:
  persistence:
    size: 500Gi
    maxCacheSize: 50000000000
  license:
    licenseKey: |-
      cHJXXXXXXXXXXX.....
resources:
  requests:
    memory: "4Gi"
    cpu: "2"
  limits:
    memory: "8Gi"
    cpu: "6"
javaOpts:
  xms: "4g"
  xmx: "6g"
postgresql:
  enabled: true
  postgresqlPassword: "MY_PASSWD"
  persistence:
    enabled: true
    size: 50Gi
nginx:
  enabled: false
ingress:
  enabled: true
  hosts:
    - jfrog.mydomain.com
  annotations:
    kubernetes.io/ingress.class: nginx
```
