### ISSUE TITLE
[artifactory] custom certificate is ignored

### ISSUE THREAD

**Issue by dfioravanti** [jfrog/charts#1173]
**Is this a request for help?**: Yes (maybe a bug report)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Helm: v3.3.4
Kubernetes: v1.19.0

**Which chart**: artifactory

**What happened**:
1. I created a self signed certificate via `$ openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=mydomain/O=mydomain"`
2. imported as a secret with `kubectl create secret tls artifacts-tls --key tls.key --cert tls.crt -n development`
3. I wanted artifactory to create a ingress object that terminate https connections with that certificate 

```
ingress:
  enabled: true
  defaultBackend:
    enabled: false
  hosts:
    - myhost
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls:
    - secretName: development/artifacts-tls
      hosts:
        - myhost
```
4. I connect to `https://myhost` and I get the default certificate served to me.

**What you expected to happen**:
I would expect my certificate to be used and not the standard one. Am I doing something wrong or is this a bug?

**How to reproduce it** (as minimally and precisely as possible): explained above

**Anything else we need to know**:

**Comment by rahulsadanandan** [comment]
@dfioravanti Hi,
I was not able to reproduce the issue. I believe the problem is with the secretName: 
Since secret resources can only be accessed inside a namespace, you don’t need to provide `development/artifacts-tls` It should be just the secret name.
Please try with 
```yaml
tls:
    - secretName: artifacts-tls
```

**Comment by rahulsadanandan** [comment]
@dfioravanti Hi,
I'm closing this, but if you face any issue feel free to reopen

**Comment by anishp55** [comment]
i am running into this exact same issue
```
persistence:
    size: 512Gi
ingress:
    enabled: true
    defaultBackend:
        enabled: false
    hosts:
        - host1
    annotations:
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
        - secretName: akp-jcr-tls
        hosts: 
        - host1
```

i've tried a bunch of combinations and nothing seems to work.  it would be helpful if there was a small example like you have for the large/medium/small deployments as trying to make heads or tails of the vaules in a 1500 like chart is a tiny bit difficult.
