### ISSUE TITLE
[artifactory-ha] FEATURE: Ability to define/apply Artifactory YAML Config

### ISSUE THREAD

**Issue by fl-max** [jfrog/charts#1207]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

I would like the ability to define [Artifactory YAML Configuration](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration) as a Value/ConfigMap and have the Chart automatically apply the configuration w/o having to bounce the Artifactory nodes (post-hook?).

**Version of Helm and Kubernetes**:
Kubernetes: `v1.17.7`
Helm: `v3.0.3`

**Which chart**:
`stable/artifactory-ha` Version `4.4.0`

**Anything else we need to know**:
This **maybe** possible using [this](https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#provide-custom-configmaps-to-artifactory) but it would be fairly convoluted and would cause the Pods to bounce.

**Comment by fl-max** [comment]
For those stumbling upon this, a workaround until this is implemented in the chart is to create a post-hook Job:

```yaml
kind: Job
apiVersion: batch/v1
metadata:
  name: {{ .Release.Name }}-apply-yaml-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: artifactory-ha-4.4.0
  annotations:
    helm.sh/hook: 'post-install,post-upgrade'
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: '-5'
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-apply-yaml-config
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: artifactory-ha-4.4.0
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-artifactory-ha-configmaps
      containers:
        - name: apply-config
          image: 'curlimages/curl:7.73.0'
          command:
            - curl
            - '-u$(ADMIN_USER):$(ADMIN_PASS)'
            - '-X'
            - PATCH
            - >-
              http://{{ .Release.Name }}-artifactory-ha-primary.{{ .Release.Namespace }}:8081/artifactory/api/system/configuration
            - '-H'
            - '"Content-Type: application/yaml"'
            - '-T'
            - /artifactory/artifactory-config.yaml
          env:
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: artifactory
                  key: admin-user
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: artifactory
                  key: admin-pass
          volumeMounts:
            - name: config
              mountPath: /artifactory
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
```
Using your own method of injecting `{{ .Release.Name }}` and `{{ .Release.Namespace }}` (ie. Terraform).

And then adding the configMap to `artifactory.configMaps`. Example:
```yaml
artifactory:
  configMaps: |
    artifactory-config.yaml: |-
      {{- if .Values.ingress.enabled }}
      {{- if .Values.ingress.tls }}
      urlBase: "https://{{ index .Values.ingress.hosts 0 }}"
      {{- else }}
      urlBase: "http://{{ index .Values.ingress.hosts 0 }}"
      {{- end }}
      {{- end }}
      mailServer:
        enabled: true
        {{- if .Values.ingress.enabled }}
        {{- if .Values.ingress.tls }}
        artifactoryUrl: "https://{{ index .Values.ingress.hosts 0 }}"
        {{- else }}
        artifactoryUrl: "http://{{ index .Values.ingress.hosts 0 }}"
        {{- end }}
        {{- end }}
        from: artifactory@example.com
        host: smtp.example.com
        port: 25
        subjectPrefix: "Notice"
        ssl: false
        tls: false
      trashcanConfig:
        enabled: true
        retentionPeriodDays: 7
      localRepositories:
        pypi-local:
          type: pypi
          checksumPolicyType: server-generated-checksums
          description: "Contains PyPi packages"
          notes: "Some notes here"
          repoLayout: simple-default
          xray:
            enabled: false
          blackedOut: false
          downloadRedirect:
            enabled: true
```

Ideally the Job should be built into the Helm Chart and we'd just be able to pass in our config (ie. `artifactory.artifactoryConfigYaml`)

I think this is the "easiest" way of implementing this but there could be potential issues here when removing configuration as it appears you need to provide null values **once** to remove. [JCasC](https://www.jenkins.io/projects/jcasc/) handles this by using a sidecar for more complex logic. Maybe that's a better route?
