### ISSUE TITLE
[Pipelines] existingSecrets for ingress not working

### ISSUE THREAD

**Issue by asanami** [jfrog/charts#1220]
**Which chart**:
Using pipelines:

```
apiVersion: v1
appVersion: 1.8.7
description: A Helm chart for JFrog Pipelines
home: https://jfrog.com/pipelines/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/pipelines/icon/pipelines-logo.png
keywords:
- pipelines
- jfrog
- devops
maintainers:
- email: helm@jfrog.com
  name: Chart Maintainers at JFrog
name: pipelines
sources:
- https://github.com/jfrog/charts/pipelines
- https://bintray.com/jfrog/pipelines
version: 2.0.4
```

**What happened**:

Specifying the following yaml for rabbitmq:

```
rabbitmq:

  #externalUrl: amqp://artifactory-pipelines-mq.artifactory.arm.com
  # Existing password secret
  #existingPasswordSecret: pipelines-rabbitmq-secret
  #existingErlangSecret: pipelines-rabbitmq-secret
  ingress:
    enabled: true
    hostname: pipelines-mq.artifactory.arm.com
    path: /
    tls: true
    existingSecret: artifactory

    annotations:
      ingress.kubernetes.io/force-ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      ingress.kubernetes.io/proxy-read-timeout: "600"
      ingress.kubernetes.io/proxy-send-timeout: "600"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

```

Results in a missing tls secret

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pipelines-rabbitmq
  namespace: artifactory
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-7.4.3
    app.kubernetes.io/instance: pipelines
    app.kubernetes.io/managed-by: Tiller
  annotations:
    
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    
spec:
  rules:
    - host: pipelines-mq.artifactory.arm.com
      http:
        paths:
          - path: /
            backend:
              serviceName: pipelines-rabbitmq
              servicePort: http-stats
  tls:
    - hosts:
        - pipelines-mq.artifactory.arm.com
      secretName: %!!(MISSING)s(<nil>)-tls

```
It looks like something is wrong with the version of rabbitmq chart being used here.
