### ISSUE TITLE
Inconsistencies between charts and their core configurations

### ISSUE THREAD

**Issue by asanami** [jfrog/charts#1222]
Various charts have Inconsistencies between how things are configured.  E.g. masterkey in x-ray chart allows masterKeySecretName but not in the pipelines chart.  And there are others.  Any efforts to align on naming conventions and consistency?

**Comment by chukka** [comment]
@asanami Yes, This is work in progress (tracked internally) , we are planning to release this in coming few weeks 

We just released  `jfrog-platform` chart  available at https://chartcenter.io/jfrog/jfrog-platform and sources [here](https://github.com/jfrog/charts/tree/master/stable/jfrog-platform)

**Few highlights:**

[0.0.3 chart release]
- Single command to install entire Jfrog platform

- Single database(postgresql) for all products

- Use global values to configure  few common parameters like masterKey, JoinKey, etc.,

**Update :**

[0.0.4 chart release]

- Added Migration steps to move existing artifactory/artifactory-ha installations to JFrog platform chart - Refer [here](https://github.com/jfrog/charts/blob/master/stable/jfrog-platform/UPGRADE_NOTES.md)

Please try and share feedback (bug reports or feature requests) :)

**Comment by asanami** [comment]
I'm happy to try the new chart. 

- Does it support a documented process for overriding the system.yaml?
- Does it support separate databases for each product
- masterKey, JoinKey specified as secrets.  We actually annotate these with vault webhooks.  E.g.

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-join-key-secret
  labels:
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: {{ .Values.vault_addr }}
    vault.security.banzaicloud.io/vault-role: {{ .Values.vault_role }}
    argocd.argoproj.io/sync-options: Validate=false
type: Opaque
data:
  join-key: {{ .Values.join_key_secret | b64enc }}
```
