### ISSUE TITLE
[artifactory-ha]Local PVCs still created when NFS is enabled

### ISSUE THREAD

**Issue by davjr96** [jfrog/charts#1245]
I am running the following options with the latest version of the ha helm chart
```
 persistence:
      type: nfs
      nfs:
        ip: ***********
        haDataMount: "/data/kubernetes/data"
        haBackupMount: "/data/kubernetes/backup"
        dataDir: "/var/opt/jfrog/artifactory-ha"
        backupDir: "/var/opt/jfrog/artifactory-backup"
  haDataDir:
    enabled: true
    path: /var/opt/jfrog/artifactory-ha
```
When I deploy this I expect Artifactory to use NFS for the storage backend. However when deployed 3 PVCs are also created. Is there a way to not create this and have artifactory use solely the NFS volumes? If these are necessary is it possible to reduce the size as no data will be stored there with the NFS backend?

```
kubectl get pvc
NAME                                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
artifactory-artifactory-ha-backup-pvc         Bound    artifactory-artifactory-ha-backup-pv       200Gi      RWO                           20h
artifactory-artifactory-ha-data-pvc           Bound    artifactory-artifactory-ha-data-pv         200Gi      RWO                           20h
data-artifactory-postgresql-0                 Bound    pvc-e727e450-687e-4da3-a270-ab69669d25f2   50Gi       RWO            thin-disk      20h
volume-artifactory-artifactory-ha-member-0    Bound    pvc-a123d67c-227b-469a-94c6-f61c11565c79   200Gi      RWO            thin-disk      20h
volume-artifactory-artifactory-ha-member-1    Bound    pvc-29753a22-d1e7-426c-919d-fe698c217c64   200Gi      RWO            thin-disk      20h
volume-artifactory-artifactory-ha-primary-0   Bound    pvc-b5672e28-a44f-460e-a8e7-7b85893cc89a   200Gi      RWO            thin-disk      20h
```

Thanks!

**Comment by chukka** [comment]
@davjr96 Thanks for reporting , Can you confirm the chart version of artifactory-ha chart ?

**Comment by davjr96** [comment]
Hi @chukka 
It looks like I am using version 4.0.4
`helm show chart center/jfrog/artifactory-ha
apiVersion: v1
appVersion: 7.7.8
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 9.3.4
description: Universal Repository Manager supporting all major packaging formats,
  build tools and CI servers.
home: https://www.jfrog.com/artifactory/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory-ha/logo/artifactory-logo.png
keywords:
- artifactory
- jfrog
- devops
maintainers:
- email: helm@jfrog.com
  name: Chart Maintainers at JFrog
name: artifactory-ha
sources:
- https://bintray.com/jfrog/product/JFrog-Artifactory-Pro/view
- https://github.com/jfrog/charts
version: 4.0.4`

**Comment by davjr96** [comment]
I just tried again with v4.4.4 with the same outcome

**Comment by chukka** [comment]
@davjr96  Thanks for reporting ! We plan to test this with NFS enabled  next week to reproduce it (will track this internally)

**Comment by TJM** [comment]
We also confirm this. We set our local volumes to 20Gi to use for local "logs" and temporary cache. Perhaps this comes down to something that should just be documented?

```yaml
artifactory:
  persistence:
    size: 20Gi # Make smaller PV since we are using NFS
    type: nfs
    nfs:
      ip: 10.9.35.100
      haDataMount: /app-artifactory-prod-001/artifactory
      haBackupMount: /app-artifactory-prod-001/backup
      capacity: 10Ti
  haDataDir:
    enabled: true
    path: /var/opt/jfrog/artifactory-ha
```
