### ISSUE TITLE
JF_SHARED_DATABASE_URL  is not set correctly when database.url is present

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [jfrog/charts#1255]
https://github.com/jfrog/charts/blob/65ed085fde448c7f0944116ce6201f029a1ccd1f/stable/artifactory/templates/artifactory-statefulset.yaml#L295

looks like copy paste error
it should be something like this

```
 {{- else if .Values.database.url }}
              value:   {{ tpl .Values.database.url . }}
```
instead of 

```
 {{- else if .Values.database.url }}
              name: {{ template "artifactory.fullname" . }}-database-creds
              key: db-url
```

**Comment by chukka** [comment]
@abhinavkhanna-sf Looks like you have mistaken here , we fetch database url from secret - Please refer [here](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-database-secrets.yaml#L14)

**Comment by abhinavkhanna-sf** [comment]
@chukka 
Sorry you are correct.

I still have one question re: below scenario. It looks like if you are providing username/password thru external secret, you have to provide URL as well thru secret.


from sts
```
      {{- if or .Values.database.secrets.url .Values.database.url }}
        - name: JF_SHARED_DATABASE_URL
          valueFrom:
            secretKeyRef:
        {{- if .Values.database.secrets.url }}
              name: {{ tpl .Values.database.secrets.url.name . }}
              key: {{ tpl .Values.database.secrets.url.key . }}
        {{- else if .Values.database.url }}
              name: {{ template "artifactory.fullname" . }}-database-creds
              key: db-url
        {{- end }}
```

from secret

```
{{- if and  (not .Values.database.secrets) (not .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "artifactory-ha.fullname" . }}-database-creds
  labels:
    app: {{ template "artifactory-ha.name" . }}
    chart: {{ template "artifactory-ha.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- with .Values.database.url }}
  db-url: {{ tpl . $ | b64enc | quote }}
  {{- end }}
  {{- with .Values.database.user }}
  db-user: {{ tpl . $ | b64enc | quote }}
  {{- end }}
  {{- with .Values.database.password }}
  db-password: {{ tpl . $ | b64enc | quote }}
  {{- end }}
{{- end }}
``` 

what happens in the following case is  since i have provided secrets, it will not create {{ template "artifactory-ha.fullname" . }}-database-creds. However, in sts since there is no url under secrets so it still tries to use the secret resource 

```
    database:
      type: 'postgresql'
      driver: 'org.postgresql.Driver'
      url: my.portgresl.url
      secrets:
        user:
          key: 'username'
          name: 'artifactory-jcr-creds'
        password:
          key: 'password'
          name: 'artifactory-jcr-creds'
```

**Comment by abhinavkhanna-sf** [comment]
something like this(not tested)
```
      
        - name: JF_SHARED_DATABASE_URL
        {{- if .Values.database.secrets.url }}
          valueFrom:
            secretKeyRef:
              name: {{ tpl .Values.database.secrets.url.name . }}
              key: {{ tpl .Values.database.secrets.url.key . }}
        {{- else if and .Values.database.secrets .Values.database.url }}
          value: {{ .Values.database.url }}
        {{- else if .Values.database.url }}
          valueFrom:
            secretKeyRef:
              name: {{ template "artifactory.fullname" . }}-database-creds
              key: db-url
        {{- end }}
```
not an expert , something like above might work
