### ISSUE TITLE
jfrog charts does not with helm template command when added as dependencies

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [jfrog/charts#1266]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

```
helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:5
8:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"202
0-08-28T23:04:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}


```

**Which chart**: All of them

**What happened**: helm template command fails when you add frog charts as dependencies

**What you expected to happen**: helm should download dependent charts and create templates.

**How to reproduce it** (as minimally and precisely as possible):

- Create a Chart.yaml with sub-chart with slash in the name

```
name: artifactory-jcr
description: JFrog Artifactory Container Registry
apiVersion: v2
version: 1.0.0
appVersion: 1.0.0
type: application
deprecated: false
dependencies:
  - repository: 'https://repo.chartcenter.io'
    name: 'jfrog/artifactory-jcr'
    version: '3.2.2'
    alias: 'artifactory-jcr'

```
- Run

```
helm dependency update
# This downloads a file artifactory-jcr-3.2.2.tgz in ./charts/   folder
```

- Run

```
helm template . --name-template artifactory-jcr  --debug
```

**Anything else we need to know**:

As per helm, helm repo should not be namespaced and should not contain slashes.

https://github.com/helm/helm/issues/9017

https://github.com/helm/helm/issues/8537
