### ISSUE TITLE
After mounting S3V3 as persistency JCR stops showing onboarding page

### ISSUE THREAD

**Issue by kivio** [jfrog/charts#1277]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
3.3.0

**Which chart**:
artifactory-jcr

**What happened**:
When configured S3 V3 as persistency layer after first login I don't get onboarding page and JCR says that EULA is not signed then I can't use it fully. 

**What you expected to happen**:
Normal configuration or possibility to configure those steps from chart values

**How to reproduce it** (as minimally and precisely as possible):
configure s3 v3 persistency type

**Anything else we need to know**:
don't know

**Comment by kivio** [comment]
found way to fix it. Config map needed:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-config
  namespace: artifactory
data:
  artifactory.config.import.yml: |
    GeneralConfiguration:
      eula:
        accepted: true

    OnboardingConfiguration:
      repoTypes:
        - docker
        - helm
```

and then in `artifactory.artifactory.configMapName: artifactory-config`

it works for me - even will be good if it will work in all storage cases same way.
