### ISSUE TITLE
[xray] Feature Request: Ability to define LoadBalancer IP of Xray service

### ISSUE THREAD

**Issue by broomyocymru** [jfrog/charts#1304]
Currently there is no way to define a static load balancer ip on the xray service template xray-svc.yaml, an optional param server.service.loadBalancerIP would resolve this. Our use case is to provide internal private address on an Azure AKS.
```
server:
  service:
    type: LoadBalancer
    name: xray
    loadBalancerIP: 192.103.67.51
    annotations:
      "service.beta.kubernetes.io/azure-load-balancer-internal": "true" 
```
Alternatively providing an additionalSpec field that accepted yaml may provide a more generic solution.
```
server:
  service:
    additionalSpec: |
         loadBalancerIP: 192.103.67.51
         customKey: customVal
```
