### ISSUE TITLE
[artifactory][artifactory-ha] Allow filebeat metrics configuration

### ISSUE THREAD

**Issue by donovanmuller** [jfrog/charts#1321]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Which chart**: 

* `artifactory`
* `artifactory-ha`

**What you expected to happen**: With the Mission Control `4.6.1` [release](https://www.jfrog.com/confluence/display/JFROG/Mission+Control+Release+Notes#MissionControlReleaseNotes-MissionControl4.6.1) the new [Artifactory Performance Trend](https://www.jfrog.com/confluence/display/JFROG/Dashboard#Dashboard-ArtifactoryPerformanceTrends) Dashboard requires that the following configuration be added to the Artifactory System YAML:

```yaml
...
      shared:    
        metrics:
          filebeat:
            enabled: true
            elasticsearch:
              url: http://mission-control.mission-control.svc:8082/elasticsearch
              username: ---
              password: ---
```

this is currently only possible by overriding `systemYaml`. Property support for this would be easier to maintain.

**Anything else we need to know**: I assume this type of cross product (Artifactory -> Mission Control) configuration is why the new `jfrog-platform` Chart is attractive.
