### ISSUE TITLE
[Bug Report] Issue in creating customVolumes & customVolumeMounts in Artifactory HA

### ISSUE THREAD

**Issue by mrgarg2** [jfrog/charts#1330]
Hello Team,

There is an issue while creating customVolume or customVolumeMount in Artifactory HA, 

Version of Helm : v3.0.1

Version of kubernetes : client Version v1.14 , server Version v1.16

Chart : Artifactory-HA

Issue : 
I tried to create customVolumeMount in values.yaml, I added a customVolumeMount in global and a customVolumeMount in artifactory section and it looks like only global volume mounts are created and artifactory volume mounts are getting ignored.

Below is the code snippet we added in Values.yaml

**charts/stable/artifactory-ha/Values.yaml** 
```
global:
  customVolumes: |
    - name: trusted-certs
      configMap:
        name: trusted-certs
		
     customVolumeMounts: |
     - name: trusted-certs
       mountPath: /var/opt/jfrog/artifactory/etc/security/keys/trusted
	
artifactory:
  customVolumeMount: |
     - name: artifactory-configmaps
       mountPath: /tmp/artifactory-config-map
```
	 
Following is the code snippet from artifactory stateful set from where it creates the customVolume and customVolumeMount.

**charts/stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml**
```
{{- if or .Values.artifactory.customVolumeMounts .Values.global.customVolumeMounts }}
	{{ tpl (include "artifactory-ha.customVolumeMounts" .) . | indent 8 }}
{{- end }}
```
This stateful set refers to _helpers.tpl which has the following customVolumes & customVolumesMount block which might be the root cause of the issue.

**charts/stable/artifactory-ha/templates/_helper.tpl**
```
{{/*
Resolve customVolumes value
*/}}
{{- define "artifactory-ha.customVolumes" -}}
{{- if .Values.global.customVolumes -}}
{{- .Values.global.customVolumes -}}
{{- else if .Values.artifactory.customVolumes -}}
{{- .Values.artifactory.customVolumes -}}
{{- end -}}
{{- end -}}

{{/*
Resolve customVolumeMounts value
*/}}
{{- define "artifactory-ha.customVolumeMounts" -}}
{{- if .Values.global.customVolumeMounts -}}
{{- .Values.global.customVolumeMounts -}}
{{- else if .Values.artifactory.customVolumeMounts -}}
{{- .Values.artifactory.customVolumeMounts -}}
{{- end -}}
{{- end -}}
```

It looks like if there are customVolume or customVolumeMount present in both global and artifactory block in Values.yaml than it would create only global ones & not the artifactory one, since there is else if statement present.

I recommend that there should be "if" statement in both blocks instead of "else if" since, that would result in creating both global and artifactory customVolume & customVolumeMounts.

```
{{/*
Resolve customVolumes value
*/}}
{{- define "artifactory-ha.customVolumes" -}}
{{- if .Values.global.customVolumes -}}
{{- .Values.global.customVolumes -}}
{{- end -}}
{{- if .Values.artifactory.customVolumes -}}
{{- .Values.artifactory.customVolumes -}}
{{- end -}}
{{- end -}}

{{/*
Resolve customVolumeMounts value
*/}}
{{- define "artifactory-ha.customVolumeMounts" -}}
{{- if .Values.global.customVolumeMounts -}}
{{- .Values.global.customVolumeMounts -}}
{{- end -}}
{{- if .Values.artifactory.customVolumeMounts -}}
{{- .Values.artifactory.customVolumeMounts -}}
{{- end -}}
{{- end -}}
```
Please look into it & suggest if there is a better workaround or I should raise a pull request for my proposed changes.

Regards,
Sajal Garg
