### ISSUE TITLE
Unable to install jfrog helm charts

### ISSUE THREAD

**Issue by JihadMotii-REISys** [jfrog/charts#1344]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
**Helm**
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

Kubernetes
V1.18

**Which chart**:
jfrog/artifactory

**What happened**:
Unable to install jfrog helm charts through ArgoCD and this issue gets thrown:
```
Unable to save changes: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `helm chart pull https://repo.chartcenter.io/jfrog/artifactory:11.0.1` failed exit status 1: Error: ref may only contain a single colon character (:) unless specifying a port number
```

**What you expected to happen**:
Installing jfrog artifactory through ArgoCD

**How to reproduce it** (as minimally and precisely as possible):
Please create an application.yaml file with the following content and apply it through using helm command line.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-artifactory
  namespace: argocd
spec:
  destination:
    namespace: build
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jfrog/artifactory
    repoURL: https://repo.chartcenter.io
    targetRevision: 11.0.1
    helm:
      values: |
        artifactory:
          admin:
            ip: "*"
            username: "admin"
            password: "admin"
          persistence:
            size: 500Gi
            maxCacheSize: 50000000000
          license:
            licenseKey: |-
              cDDDDXXXXXDDDDXXXX
              DDFFDDDD.....
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "6"
        javaOpts:
          xms: "4g"
          xmx: "6g"
        postgresql:
          enabled: false
        database:
          type: postgresql
          driver: org.postgresql.Driver
          url: 'jdbc:postgresql://HOSTNAME:5432/jfrog'
          user: dbUsername
          password: dbPassword
        nginx:
          enabled: false
        ingress:
          enabled: true
          hosts:
            - jfrog.example.com
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt
          tls:
            - secretName: jfrog.example.com
              hosts:
                - jfrog.example.com
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - Validate=false
```

**Anything else we need to know**:
This helm chart above it was working fine until suddenly stopped working. I'm using ArgoCD to deploy my CICD tool helm charts.
Please see screenshot of the issue

![Screen Shot 2021-01-28 at 8 09 55 PM](https://user-images.githubusercontent.com/9051199/106186637-d621c400-61a4-11eb-86f6-c8c02b64725f.png)
Thanks in advance!
