### ISSUE TITLE
[artifactory] Ingress does not use custom certificate

### ISSUE THREAD

**Issue by lusu007** [jfrog/charts#1390]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
- Helm v3.5.2
- Managed Kubernetes OVH 1.19.5

**Which chart**:
- artifactory-oss

**What happened**:
When setting up an ingress for Artifactory and adding cert-manager annotations Artifactory does not use or overrides the custom generated certificate. 

**What you expected to happen**:
Artifactory should use the certificate which cert-manager generated.

**How to reproduce it** (as minimally and precisely as possible):
Just install Artifactory with an ingress by using the official documentation and add needed annotations for cert-manager.

**Anything else we need to know**:
Nothing. If you need more information just contact me.

**Comment by rimusz** [comment]
@lusu007 if you properly installed and setup `cert-manager` which setup is cloud agnostic it should work just fine.
When`cert-manager` is installed, please instal `ClusterIssuer`:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: your_email@domain.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: ingress-nginx ### set correct ingress class
```

Create Artifactory OSS `override-values.yaml` file:
```
artifactory:

  ingress: 
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ingress.class: ingress-nginx ### set correct ingress class
    hosts:
      - art-oss.domain.com
    tls:
      - secretName: art-oss.domain.com
        hosts:
          - art-oss.domain.com

  postgresql:
    postgresqlPassword: SomeSecurePassword!!!

  nginx:
    enabled: false
```
 
Then install Artifactory OSS:
```
$ kubectl create ns artifactory-oss
$ helm upgrade --install art-oss -n artifactory-oss jfrog/artifactory-oss --version=3.5.1 -f override-values.yaml
```
