### ISSUE TITLE
Postgresql dependency using deprecated API extensions/v1beta1 for Deployment kind

### ISSUE THREAD

**Issue by mkkot-onegini** [jfrog/charts#1402]
**Version of Helm and Kubernetes**:
K8s:
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean",

helm:
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29"

**Which chart**:
```
- name: jfrog-artifactory
    chart: jfrog/jfrog/artifactory
    version: 7.17.4
```

**What happened**:
The chart is pulling:

```
dependencies:
  - name: postgresql
    version: 9.3.4
    repository: https://charts.bitnami.com/bitnami
```

postgres is trying to deploy:

```
helm template jfrog/jfrog/artifactory --version 7.17.4
[...]
# Source: artifactory/charts/postgresql/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: RELEASE-NAME-postgresql
  labels:
    app: RELEASE-NAME-postgresql
    chart: "postgresql-0.9.5"
```

Which breaks deployment with:
 Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

Which is exactly what the release notes say will happen:
_In 1.16 if you submit a Deployment to the API server and specify extensions/v1beta1 as the API group it will be rejected with:_
```
error: unable to recognize "deployment": no matches for kind "Deployment" in version "extensions/v1beta1"
```
https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/

**What you expected to happen**:

Postgres uses apiVersion: apps/v1 for deployments.

**How to reproduce it** (as minimally and precisely as possible):

Install Kubernetes >= 1.16 and try to deploy artifactory chart with postgres enabled.

**Anything else we need to know**:
```
postgresql:
  enabled: false
```
makes deployment possible.
