### ISSUE TITLE
Can't add only the custom ingress

### ISSUE THREAD

**Issue by mkkot-onegini** [jfrog/charts#1412]
**Is this a BUG REPORT or FEATURE REQUEST?**
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v3.5.2, K8s: "v1.18.9-eks-d1db3c"

**Which chart**:
jfrog/artifactory --version '11.13.0'

**What happened**:

Two ingresses are created instead of one.

helm upgrade --install artifactory  jfrog/artifactory --version '11.13.0' -f values.yaml

values.yaml:

```
ingress:
  enabled: true

customIngress:
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: artifactory-nginx
    annotations:
      kubernetes.io/ingress.class: haproxy
      meta.helm.sh/release-name: artifactory
      meta.helm.sh/release-namespace: artifactory-staging
  spec:
    backend:
      serviceName: artifactory-artifactory-nginx
      servicePort: 80
    rules:
    - host: staging.artifactory.mydomain.com
      http:
        paths:
        - backend:
            serviceName: artifactory-artifactory-nginx
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
```

**What you expected to happen**:

First of all, the values.yaml suggests to use pipe: "customIngress: |" which is wrong and doesn't work. It works only as "customIngress:".

The second thing is that I can't deploy my custom ingress without 

```
ingress:
  enabled: true
```
This instruction: https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/ingress.yaml#L1
says that whole ingress template won't be interpreted if I don't enable it.

But if I enable it, it will deploy my custom ingress and the default one:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: artifactory
    meta.helm.sh/release-namespace: artifactory-staging
  creationTimestamp: "2021-04-16T09:00:58Z"
  generation: 1
  labels:
    app: artifactory
    app.kubernetes.io/managed-by: Helm
    chart: artifactory-11.13.0
    heritage: Helm
    release: artifactory
spec:
  backend:
    serviceName: artifactory-artifactory
    servicePort: 8082
status:
  loadBalancer:
    ingress:
    - hostname: xxxx
```

The default one is undesired and it spins up ELB that won't be used but has to be payed.

**How to reproduce it** (as minimally and precisely as possible):
Try to create custom ingress without creating the default one.
