### ISSUE TITLE
[artifactory-ha] Database URL can't be specified in values

### ISSUE THREAD

**Issue by FalconerTC** [jfrog/charts#1418]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Kubernetes 1.17.17-gke.2800

**Which chart**:
Artifactory-ha 4.9.4

**What happened**:
Database values can't be mix-and-matched between secrets and direct values (as in, `.Values.database.url` and `.Values.database.secrets` can not both be defined). The following values config

```
database:
  type: postgresql
  url: jdbc:postgresql://localhost:5432/artifactory
  driver: org.postgresql.Driver
  secrets:
    user:
      name: artifactory-db
      key: username
    password:
      name: artifactory-db
      key: password
```

Will cause `JF_SHARED_DATABASE_URL` to check in a default secret instead of the value in `database.url`

**What you expected to happen**:
I would like to be able to supply database credentials as a secret but the database URL as a value to the chart

**How to reproduce it** (as minimally and precisely as possible):
See above example

**Anything else we need to know**:
This was caused by the following change
https://github.com/jfrog/charts/commit/59f029e29bd4c99c540002e6a73633a94bbc614d

```
      {{- if or .Values.database.secrets.url .Values.database.url }}
        - name: JF_SHARED_DATABASE_URL
          valueFrom:
            secretKeyRef:
        {{- if .Values.database.secrets.url }}
              name: {{ tpl .Values.database.secrets.url.name . }}
              key: {{ tpl .Values.database.secrets.url.key . }}
        {{- else if .Values.database.url }}
              name: {{ template "artifactory-ha.fullname" . }}-database-creds
              key: db-url
        {{- end }}
```

Maybe `artifactory-database-secrets.yaml` can be made optional with an additional config? `database.createSecret` or something?
