### ISSUE TITLE
What are the exact S3 action to allow for S3 backend storage setup?

### ISSUE THREAD

**Issue by casper-gh** [jfrog/charts#1424]
Question: Regarding S3 backend for storage, what are the exact actions for IAM role attached to the nodes? 

https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#aws-s3

```
  persistence:
    type: aws-s3
    awsS3:
      bucketName: "my-bucket"
      endpoint: "https://s3.us-east-1.amazonaws.com"
      region: "us-east-1"
      testConnection: false
      path: "artifactory-ha/filestore"
      roleName: "myRole"
```

I'm looking for the IAM policy, something like:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject"
            ],
            "Resource": "my-bucket"
        }
    ]
}
```

I actually tried this policy, but I'm not sure if it's working because objects are copied to S3 after they're written into local storage. And I couldnt find any log that would show the object copy process.
