### ISSUE TITLE
[Xray] Unable to connect to CloudSQL

### ISSUE THREAD

**Issue by FalconerTC** [jfrog/charts#1440]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
❯ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

1.17.17-gke.4900

**Which chart**:
xray

**What happened**:
The Xray chart is unable to connect to Postgresql and crash-loops with errors like the following

```
xray-dev-0 xray-indexer 2021-05-25T22:28:54.024Z [jfxid] [INFO ] [                ] [sql_layer:38                  ] [main                ] connecting to postgresql attempt #5
xray-dev-0 xray-indexer 2021-05-25T22:28:54.024Z [jfxid] [INFO ] [                ] [sql_layer:133                 ] [main                ] Setting database max idle connections 5
xray-dev-0 xray-indexer 2021-05-25T22:28:54.024Z [jfxid] [INFO ] [                ] [sql_layer:142                 ] [main                ] Setting database max open connections 30
xray-dev-0 xray-indexer 2021-05-25T22:28:54.024Z [jfxid] [INFO ] [                ] [sql_layer:150                 ] [main                ] Setting database max idle sec 120
xray-dev-0 xray-indexer 2021-05-25T22:28:54.024Z [jfxid] [INFO ] [                ] [sql_layer:159                 ] [main                ] Setting database max lifetime sec 120000000
xray-dev-0 xray-persist 2021-05-25T22:28:54.197Z [jfxps] [INFO ] [                ] [sql_layer:38                  ] [main                ] connecting to postgresql attempt #5
xray-dev-0 xray-persist 2021-05-25T22:28:54.197Z [jfxps] [INFO ] [                ] [sql_layer:133                 ] [main                ] Setting database max idle connections 5
xray-dev-0 xray-persist 2021-05-25T22:28:54.197Z [jfxps] [INFO ] [                ] [sql_layer:142                 ] [main                ] Setting database max open connections 30
xray-dev-0 xray-persist 2021-05-25T22:28:54.197Z [jfxps] [INFO ] [                ] [sql_layer:150                 ] [main                ] Setting database max idle sec 120
xray-dev-0 xray-persist 2021-05-25T22:28:54.197Z [jfxps] [INFO ] [                ] [sql_layer:159                 ] [main                ] Setting database max lifetime sec 120000000
...
xray-dev-0 xray-persist 2021-05-25T22:28:57.198Z [jfxps] [ERROR] [                ] [general_utils:23              ] [main                ] Critical error: exiting from Xray Program, reason: dial tcp 127.0.0.1:5433: connect: connection refused
```

**What you expected to happen**:
Xray should come up

**How to reproduce it** (as minimally and precisely as possible):
I am attempting to connect to Xray to Google CloudSQL via the cloudsql-proxy (https://github.com/GoogleCloudPlatform/cloudsql-proxy). I have the following values set in doing so
```
common:
  customSidecarContainers: |
    - name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.17-buster
      command:
        - "/cloud_sql_proxy"
        - "-instances={{ .Values.projectId }}:{{ .Values.region }}:{{ .Values.database.instanceId }}=tcp:{{ .Values.database.port }}"
        - "-credential_file=/secrets/credentials.json"
        - "-verbose=true"
      securityContext:
        runAsNonRoot: true
      volumeMounts:
        - name: proxysql-credentials-volume
          mountPath: /secrets
          readOnly: true

    customVolumes: |
    - name: proxysql-credentials-volume
      secret:
        secretName: service-account-credentials
        items:
          - key: credentials.json
            path: credentials.json
```

I've configured Xray to use external auth, by supplying credential directly
```
postgresql:
  enabled: false

database:
  type: postgresql
  driver: org.postgresql.Driver
  user: xray
  password: ****
  url: postgresql://localhost:5432/xray?sslmode=disable
```

and by using existing secrets

```
postgresql:
  enabled: false

database:
  type: postgresql
  driver: org.postgresql.Driver
  secrets:
    user:
      name: xray-db
      key: username
    password:
      name: xray-db
      key: password
    url:
      name: xray-db
      key: url
```

In all cases, Xray is not able to authenticate with Postgresql. CloudSQL logs confirm that requests seem to be coming with the incorrect credentials
```
2021-05-25 22:19:10.908 UTC [1551]: [1-1] db=xray,user=xray FATAL:  password authentication failed for user "xray"
```

Some things I have tried:
  - I confirmed it can connect to CloudSQL using public IP instead of the sidecar (I use the sidecar with zero issue for artifactory-ha though so I don't see why I wouldn't be able to use it here)
  - I've tried it with a shared Postgresql instance and with an empty one
  - I've confirmed I can authenticate via the sidecar by using postgres in a different init container and running `psql 'postgresql://xray:***@localhost:5432/xray?sslmode=disable'`
  - I verified CloudSQL allows connections without SSL
  - I verified `JF_SHARED_DATABASE_URL`, `JF_SHARED_DATABASE_PASSWORD`, and `JF_SHARED_DATABASE_USERNAME` are being set correctly in the xray containers 

Any idea why I would be seeing issues here? The only difference between this and artifactory-ha seems to be the connection string not using SSL and not going through JDBC, so I don't understand why this would be working fine with Artifactory

**Comment by FalconerTC** [comment]
Testing this out more, I can recreate the same issue without the Cloudsql proxy. The following config
```
database:
  type: postgresql
  driver: org.postgresql.Driver
  user: xray
  password: ****
  url: postgresql://<private_ip>:5432/xray?sslmode=disable
```

Has the same results, when using a private IP on the same network to connect to CloudSQL. I ran a Postgres sidecar and verified I can connect using `psql 'postgresql://xray:***@<private_ip>:5432/xray?sslmode=disable'`
