### ISSUE TITLE
Artifactory-HA custom master-key not working at all, causing failed Startup probe

### ISSUE THREAD

**Issue by frankfong0208** [jfrog/charts#1474]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 BUG REPORT

**Version of Helm and Kubernetes**:
Helm v3.5.3
Kubernetes versions:
Client Version: v1.19.4
Server Version: v1.18.9-eks-d1db3c
**Which chart**:
https://artifacthub.io/packages/helm/jfrog/jfrog-platform/0.7.0
I tried 0.6.0 first and then 0.7.0, same result.
**What happened**:
As described above, the jfrog-platform-artifactory-ha-primary-0 pod would not start the main  artifactory-ha container due to failed startup probe. I googled for the errors and someone mentioned this could probably due to corrupted master key, which I don't quite follow as the key was generated and configured per the official doco. 

**What you expected to happen**:
The jfrog-platform-artifactory-ha-primary-0 pod should start healthy and the jfrog-platform-artifactory-ha-member-0 and jfrog-platform-artifactory-ha-member-1 pods should start as well afterwards rather than get stuck waiting for the primary pod. 

**How to reproduce it** (as minimally and precisely as possible):
1. setup AWS RDS postgres database 
2. generate custom 32/16 hex value for master-key; create a generic k8s secret to store this with the key name as master-key. 
3. create a customvalues file with artifactory-ha.artifactory.masterKeySecretName=artifactory-master-key
4. run "helm upgrade --install jfrog-platform --namespace jfrog-platform jfrog/jfrog-platform --version 0.6.0 -f jfrog-platform/customvalues.yaml" 

**Anything else we need to know**:
I also tried putting artifactory-ha.global.masterKeySecretName=artifactory-master-key, and even not using a secret, but just hard-code the master key value in this artifactory-ha.global.masterKey=<hex value> or artifactory-ha.artifactory.masterKey=<hex value> in the customvalues.yaml file. to no avail. 
I also tried the global.masterKey or global.masterKeySecretName paths, same result. 
The moment I commented out these values, the chart would use the default dummy master key which is bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb and everything worked just fine. 
Every time I redo the chart installation, I would delete the artifactory_ha database from inside the rds postgres instance and even tried recreating the rds itself to ensure rds was not contaminated. however, the result was still the same.
Part of customvalues.yaml file:
``` yaml
artifactory-ha:
  enabled: true
  postgresql:
    enabled: false
  waitForDatabase: false
  database:
    type: postgresql
    driver: org.postgresql.Driver
    secrets: 
      user:
        name: "jp-database-creds"
        key: "db-admin-user"
      password:
        name: "jp-database-creds"
        key: "db-admin-password"
      url:
        name: "jp-database-creds"
        key: "db-url"
  artifactory:
    joinKeySecretName: artifactory-join-key
    masterKeySecretName: artifactory-master-key 
    migration:
      enabled: false
    persistence:
      annotations: eks\.amazonaws\.com/role-arn=arn:aws:iam::111111:role/shared-artifactory-s3-role
      type: aws-s3-v3
      awsS3V3:     
        region: ap-southeast-2     
        bucketName: shared-artifactory-bucket
```
