### ISSUE TITLE
artifactory-ha behind ALB ingress controller 

### ISSUE THREAD

**Issue by djschnei21** [jfrog/charts#1490]
**Is this a request for help?**: 
yes

Hi all - Have been spinning my wheels a bit trying to get artifactory-ha installed behind an ALB ingress controller on AWS.  As far as I can tell this should be possible, however I can't seem to get it working and haven't found any examples online.  

This is currently what I have:
```
ingress:
    enabled: true
    defaultBackend:
      enabled: false
    hosts:
      - jfrog.foo.com
    annotations:
      external-dns.alpha.kubernetes.io/hostname: jfrog.foo.com
      ingress.kubernetes.io/force-ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      ingress.kubernetes.io/proxy-read-timeout: "2400"
      ingress.kubernetes.io/proxy-send-timeout: "2400"
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:foo:certificate/foo
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
      alb.ingress.kubernetes.io/healthcheck-path: /router/api/v1/system/health
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
      alb.ingress.kubernetes.io/healthy-threshold-count: "2"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/security-groups: awsuatdss-it-cicd-eks-alb0
      alb.ingress.kubernetes.io/success-codes: 200-399
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
  nginx:
    enabled: false
```

Does anyone know of any documentation, or maybe have a working example of how I can achieve this setup?

**Comment by zendern** [comment]
@djschnei21  Ok i was able to get this to work and thought I would share. (fwiw i am using the `jfrog-platform` helm chart but under the covers it uses the `artifactory` chart which at least the `ingress.yaml` appears to be basically the same so hopefully this helps)

First thing based on this start of an issue on the `aws-load-balancer-controller` project https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1724. I could not confirm that `ClusterIp` would or would not work. So I switched my config to use `NodePort`.

```
artifactory:
    service:
      type: NodePort
```

For the `ingress` configuration side I have done the following.

```
ingress:
    enabled: true
    defaultBackend:
      enabled: false
    hosts:
      - jfrog.foo.com
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:foo:certificate/foo
      alb.ingress.kubernetes.io/target-type: "instance"
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
      alb.ingress.kubernetes.io/healthy-threshold-count: "2"
      alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
      alb.ingress.kubernetes.io/conditions.jfrog-platform-artifactory: '[{ "field": "path-pattern", "pathPatternConfig": { "values": ["/*"] } }]'
```

Nginx is of course disabled like you have as well

```
nginx:
    enabled: false
```

Things to note: 

The `condition` was important to allow for all things to be resolved. Without it the login page did load but no images, scripts, etc were found and it would just fail if you tried to login.

Also not setting `alb.ingress.kubernetes.io/healthcheck-path` was important b/c without it everything under the `/artifactory` target group was not marked as healthy b/c that path does not exist. 

Another thing to note for what I have above vs what you have setup for `external-dns` I did not use the kube and `aws-load-balancer-controller` magic to set it up as it was more IAM setup that I wanted to do and just opt'd to do it via IAC.
