### ISSUE TITLE
[mission-control] resources block  correctly not placed

### ISSUE THREAD

**Issue by pbecotte** [jfrog/charts#1507]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which chart**: mission-control

**What Happened**:

https://github.com/jfrog/charts/blob/master/stable/mission-control/templates/mission-control-statefulset.yaml#L198

This resources block is associated with the `wait-for-db` init container. However, that container (except for the resource block) is wrapped in an `if` statement. If the `if` evaluates False, this block will generate invalid yaml.

**How to reproduce it** (as minimally and precisely as possible):

The default `jfrog-platform` chart will reproduce the issue

`helm template jfrog-platform > myfile.yaml`

The duplicate resource block is at line 3551 with my current setup.

**Anything else we need to know**:

I am guessing the reason this hasn't been noticed is that it doesn't make much sense to run this without a database. The issue here is that the `platform` helm chart defined `global.database` which is not used in `mission-control`.  Using this as a platform override works around the issue. The duplicate resources is a bug either way, but this should probably be fixed as well.

```
mission-control:
  enabled: true
  # This chart doesn't use the global value, so copy these over for now
  database:
    host: "{{ .Release.Name }}-postgresql"
    port: 5432
```
