### ISSUE TITLE
Xray filebat permissions error when enableing shared Metrics and filebeat

### ISSUE THREAD

**Issue by mohammad-hamaydeh** [jfrog/charts#1521]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-dispatcher", GitCommit:"766e62361387c284022a97270f0997d67ae792d0", GitTreeState:"clean", BuildDate:"2020-12-01T16:13:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.12-gke.2101", GitCommit:"c8d75ae17b4628860e58bcdbe73c1f29dae62361", GitTreeState:"clean", BuildDate:"2021-08-18T18:42:22Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

appVersion: 3.32.2
version: 103.32.2

**What happened**:

After enabled Metrics and filebeat and we are getting  error on the filebeat permission  on Xray server logs as well the xray trends does not show up on Artifactory UI trends 
```
shared:
    metrics:
        enabled: true 
        filebeat:
            elasticsearch:
                password: password
                url: http://insight.insight.svc:8082/elasticsearch
                username: username
            enabled: true
            log:
                enabled: true
                level: debug
    logging:
        consoleLog:
            enabled: false
xray:
    metrics:
        enabled: true
```
```
2021-10-11T12:27:52.809Z [jfxr ] [WARN ] [17c558c90ed2738a] [process_execution_manager:281 ] [main                ] (--wrapper--)Process 11915:/opt/jfrog/xray/app/third-party/filebeat/filebeat finished unexpectedly and will be restarted. Stdout=, Stderr=Exiting: error loading config file: config file ("/opt/jfrog/xray/var/etc/filebeat.yaml") can only be writable by the owner but the permissions are "-rw-rw-r--" (to fix the permissions use: 'chmod go-w /opt/jfrog/xray/var/etc/filebeat.yaml')
```

**What you expected to happen**:
Filebeat.yaml should have the correct permissions  so the filebeat should work fine 

**How to reproduce it** (as minimally and precisely as possible):
enabling shared Metrics and filebeat  as mentioned

**Anything else we need to know**:
