### ISSUE TITLE
artifactory.persistence.enabled: false still mounts an artifactory-volume and requires a pvc

### ISSUE THREAD

**Issue by jansmets** [jfrog/charts#1543]
As discussed in JFrog Support #185742 persistency is not required when using “S3 Direct Upload”. (no eventual cache)
"artifactory-volume" is not using an EmptyDir with  artifactory.persistence.enabled: false

```
 volumes:
  - name: artifactory-volume
    persistentVolumeClaim:
      claimName: artifactory-volume-jfrog-platform-artifactory-0
```
