### ISSUE TITLE
[jfrog-platform] HA setup (3 nodes), binaries are not replicated

### ISSUE THREAD

**Issue by duelyy** [jfrog/charts#1571]
**Is this a request for help?**: 
Help

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
Bug

**Version of Helm and Kubernetes**:
Helm: v3.6.2
Kubernetes:

**Which chart**:
[jfrog-platform](https://github.com/jfrog/charts/tree/master/stable/jfrog-platform)

**What happened**:
HA setup where there's 3 nodes behind nginx.

Whenever I run `docker pull NAME` from my local workstation, I get a 500 error. If I run `docker pull` a few more times, I eventually am able to grab the image.

```
docker pull NAME
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```

Checked the path, `/var/opt/jfrog/artifactory/data/artifactory/filestore`, on all three nodes and noticed that binaries are not being replicated.

**What you expected to happen**:

My understanding is that `file-system` should have replicated the binaries on all three nodes equally. I expect that whenever I run `docker pull NAME`, that I should not get a 500 error.

**How to reproduce it** (as minimally and precisely as possible):

```
docker pull NAME
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```

**Anything else we need to know**:

Below is the snippet of values.yaml file that was used to provision the Artifactory cluster.
```
artifactory:
  enabled: true
  artifactory:
    replicaCount: 3
  persistence:
    enabled: true
    binarystoreXml: |
      <config version="2">
          <chain template="cluster-file-system"/>
      </config>
```

Exec into one of the pods and it doesn't look like the binarystore.xml picked up the `cluster-file-system`
```
sh-4.4$ cat /artifactory_bootstrap/binarystore.xml 
<!-- File system filestore -->
<config version="v1">
    <chain>
            <provider id="file-system" type="file-system"/>
    </chain>
</config>
```
