### ISSUE TITLE
[jfrog-platform] Cannot spin up the platform with default database values

### ISSUE THREAD

**Issue by onetwopunch** [jfrog/charts#1608]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): `BUG REPORT`

**Version of Helm and Kubernetes**: 
k8s: `1.22.7-gke.1500`
helm: `version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}`

**Which chart**: `jfrog-platform` version 10.4.1

**What happened**: 

Default installation does not work, presumably because of something to do with the built in postgres.

Using this command:
```
helm upgrade --install jfrog-platform --namespace jfrog-platform  jfrog/jfrog-platform -f values.yml
```
 
And this values.yaml:
```yaml
artifactory:
  nginx:
    service:
      loadBalancerIP: "${INTERNAL_IP}"
      annotations:
        networking.gke.io/load-balancer-type: "Internal"
  artifactory:
    replicaCount: 3
    license:
      licenseKey: |-
         ...
```

Most of the workloads get stuck in an initialization state:

![image](https://user-images.githubusercontent.com/1054518/161145344-16f02145-da8b-4bbb-86cb-8815d282cd13.png)

After further inspection of the Artifactory workload logs, I'm seeing this error:

```
[31mERROR:[0m Unable to proceed. Postgres is not reachable. This can occur if the service is not running or the port is not accepting requests at 5432 (host : jfrog-platform-postgresql). Gave up after 11 attempts
```

**What you expected to happen**: Helm install creates an artifactory cluster with the default values as described in the [documentation](https://www.jfrog.com/confluence/display/JFROG/Installing+the+JFrog+Platform+Using+Helm+Chart)
