### ISSUE TITLE
[artifactory-oss/jcr/cpp-ce] Artifactory dependency charts fails with jf-event issue when splitServicesToContainers is enabled

### ISSUE THREAD

**Issue by Nefelim4ag** [jfrog/charts#1639]
Must be disabled, because working only with enterprise image

```
artifactory:
  jfconnect: # Broken missing jfconnect in OSS image
    enabled: false
```

Not working because the missing jf-event in OSS image
```
artifactory:
  splitServicesToContainers: true
```

**Comment by chukka** [comment]
@Nefelim4ag Yes, This is already fixed  internally and will be released in  upcoming next minor release  of artifactory

**Comment by Nefelim4ag** [comment]
107.41.4 - same, missing jf-event

**Comment by chukka** [comment]
@Nefelim4ag  can you please share complete logs and reproducible steps ?

**Comment by Nefelim4ag** [comment]
artifactory-oss: 107.41.4

```
artifactory:
  splitServicesToContainers: true # Broken missing jf-events in OSS image
  artifactory:
    persistence:
      size: 100Gi
      storageClassName: "efs"
    resources:
      requests:
        memory: "2Gi"
        cpu: "200m"
    javaOpts:
      corePoolSize: 8
      jmx:
        authenticate: false
        enabled: false
        port: 9010
        ssl: false
      xms: "512m"
      xmx: "2g"
  ingress:
    enabled: true
    hosts:
      - artifactory-dev.example.net
    annotations:
      kubernetes.io/ingress.class: contour
      cert-manager.io/cluster-issuer: zerossl
    tls:
      - secretName: artifactory-tls
        hosts:
          - artifactory-dev.example.net

  jfconnect: # Broken missing jfconnect in OSS image
    enabled: false

  nginx:
    enabled: false

  postgresql:
    enabled: true
    postgresqlPassword: password
    global:
      storageClass: "ebs"
    persistence:
      enabled: true
      size: 16Gi
    resources:
     requests:
       memory: "256Mi"
       cpu: "100m"
```
