### ISSUE TITLE
consider http probes instead of exec probes?

### ISSUE THREAD

**Issue by billimek** [jfrog/charts#1657]
**Is this a request for help?**: No

---

**FEATURE REQUEST**:

The artifactory helm chart by default leverages exec-style probes to invoke curl commands, [e.g.](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L225-L237)

```
  livenessProbe:
    enabled: true
    config: |
      exec:
        command:
          - sh
          - -c
          - curl -s -k --fail --max-time {{ .Values.probes.timeoutSeconds }} {{ include "artifactory.scheme" . }}://localhost:{{ .Values.router.internalPort }}/router/api/v1/system/liveness
      initialDelaySeconds: {{ if semverCompare "<v1.20.0-0" .Capabilities.KubeVersion.Version }}90{{ else }}0{{ end }}
      periodSeconds: 10
      timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
      failureThreshold: 5
      successThreshold: 1
```

Is the curl command necessary to properly probe the health of the instances, or is it possible to leverage [https style probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request) to achieve the same end-result?

The reason for this ask is that there is currently an open kubernetes [issue](https://github.com/kubernetes/kubernetes/issues/82440) related to using exec-style probes and possibly resulting in high system CPU/load.

**Version of Helm and Kubernetes**: helm3, 1.22.8-gke.202

**Which chart**: `artifactory`
