### ISSUE TITLE
Upgrade fail when installing log-analytics-datadog

### ISSUE THREAD

**Issue by duelyy** [jfrog/charts#1659]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**: Helm v3.6.2, Kubernetes v1.21

**Which chart**: jfrog-platform

**What happened**:

When installing the [log-analytics-datadog](https://github.com/jfrog/log-analytics-datadog/blob/master/helm/artifactory-values.yaml) chart, I'm getting the following error:

```
upgrade.go:123: [debug] preparing upgrade for jfrog-platform
Error: UPGRADE FAILED: template: jfrog-platform/charts/artifactory/templates/artifactory-statefulset.yaml:84:3: executing "jfrog-platform/charts/artifactory/templates/artifactory-statefulset.yaml" at <tpl (include "artifactory.customInitContainersBegin" .) .>: error calling tpl: error during tpl function execution for "{{ template \"initdb\" . }}\n{{ template \"initdb\" . }}\n
```

Since the jfrog-platform chart has the artifactory chart as the dependency, my values.yaml is a bit different. I have to nest it under another parent named `artifactory:`

```
artifactory:
  artifactory:
    customInitContainersBegin: |
      - name: "download-fluentd-conf-on-persistent-volume"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
        command:
          - 'sh'
          - '-c'
          - >
            mkdir -p {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/;
            wget https://raw.githubusercontent.com/jfrog/log-analytics-datadog/master/fluent.conf.rt -O {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf

```

**What you expected to happen**: 

I expect to not have an error about initdb and that it will create a container where it will load all the fluentd config, so I can enable Datadog log ingestion.

**How to reproduce it** (as minimally and precisely as possible):

```
helm upgrade --cleanup-on-fail \
  --install jfrog-platform jfrog/jfrog-platform \
  --create-namespace \
  --namespace jfrog-platform \
  --values values.yaml \
  --values values-datadog-log-analytics.yaml \
  --version 10.6.3 \
  --debug
```

Below is the values-datadog-log-analytics.yaml file
```
artifactory:
  artifactory:
    customInitContainersBegin: |
      - name: "download-fluentd-conf-on-persistent-volume"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
        command:
          - 'sh'
          - '-c'
          - >
            mkdir -p {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/;
            wget https://raw.githubusercontent.com/jfrog/log-analytics-datadog/master/fluent.conf.rt -O {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf
        volumeMounts:
          - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
            name: datadog-fluentd-volume
      - name: "prepare-fluentd-conf-on-persistent-volume"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
        command:
          - 'sh'
          - '-c'
          - >
            sed 's/API_KEY/{{ .Values.datadog.artifactory.apiKey }}/' {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf > {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf.new;
            mv {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf.new {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf;
        volumeMounts:
          - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
            name: datadog-fluentd-volume
    customSidecarContainers: |
      - name: "artifactory-fluentd-sidecar"
        image: "partnership-public-images.jfrog.io/fluentd/fluentd:1.13.2"
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
          - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
            name: datadog-fluentd-volume
        env:
          - name: JF_PRODUCT_DATA_INTERNAL
            value: {{ .Values.artifactory.persistence.mountPath }}
          - name: FLUENTD_CONF
            value: ../../../../{{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf
datadog:
  artifactory:
    apiKey: datadog_api_key

```

**Anything else we need to know**:

**Comment by vasukinjfrog** [comment]
[duelyy](https://github.com/duelyy) - can we try using curl command instead of wget. 

i.e  change this 
wget https://raw.githubusercontent.com/jfrog/log-analytics-datadog/master/fluent.conf.rt -O {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf

to 

curl https://raw.githubusercontent.com/jfrog/log-analytics-datadog/master/fluent.conf.rt -o {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf;

**Comment by chukka** [comment]
@duelyy is above workaround provided by @vasukinjfrog helped to  solve problem ?

**Comment by duelyy** [comment]
@vasukinjfrog @chukka I went a different route and used the [native datadog agent](https://docs.datadoghq.com/containers/kubernetes/log/?tab=helm) to scrape the logs from Artifactory. The update that I had to change on the values.yaml file was to enable the sidecar, so datadog can scrape those logs.

Example:
Using the `jfrog-platform` chart, this is what I needed to enable sidecar for datadog to scrape logs.
```
artifactory:
  ...
  artifactory:
    ...
    loggers:
      - artifactory-access.log
      - artifactory-request.log
```
