### ISSUE TITLE
[artifactory-oss] Artifactory Template does not respect setting the storageClassName or Size

### ISSUE THREAD

**Issue by danmanners** [jfrog/charts#1660]
# Description

When deploying Artifactory, I want to change both the storageClass and size of the deployed disk. However, updating the expected values in the `values.yaml` file does not change any of the default values.

# Expected Behavior

I expect the values to be set to what I am defining.

# Actual Behavior

The values are unchanged from their default settings. The disk size is unchanged, and the storageClass will **ONLY** use the default storage class.

# Values to repeat issue

```yaml
artifactory:
  # Installer Settings
  installer:
    platform: art-oss-helm

  # Artifactory Settings
  name: artifactory
  image:
    registry: releases-docker.jfrog.io
    repository: jfrog/artifactory-oss
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "11Gi"
      cpu: "4"
  javaOpts:
    xms: "2g"
    xmx: "10g"

  persistence:
    enabled: true
    size: 60Gi
    storageClassName: nvme
```

## Rendered Artifactory StatefulSet Output

```yaml
...
  volumeClaimTemplates:
  - metadata:
      name: artifactory-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
```

## Screenshot

![image](https://user-images.githubusercontent.com/17593824/183306483-fd9986b7-33c0-47e2-944d-54be94e0a02f.png)

https://github.com/jfrog/charts/blob/7c0ad8e76fbeb64c40513eafc7a072d24fdb0f03/stable/artifactory/templates/artifactory-statefulset.yaml#L1341

Happy to provide any other information necessary.
