### ISSUE TITLE
Published Chart index is empty

### ISSUE THREAD

**Issue by lancehudson** [jfrog/charts#1667]
**Is this a request for help?**:
Yes, unable to install ANY charts
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
helm 3

**Which chart**:
ALL

**What happened**:
https://charts.jfrog.io/index.yaml is empty

```yaml
apiVersion: v1
entries: {}
generated: '2022-09-20T16:29:18.094999Z'
```

**What you expected to happen**:
Should list all available helm charts and versions

**How to reproduce it** (as minimally and precisely as possible):
```
helm repo add jfrog https://charts.jfrog.io
helm repo update
helm search repo | grep jfrog
```
or
```
curl https://charts.jfrog.io/index.yaml
```

**Anything else we need to know**:
