### ISSUE TITLE
Xray Helm Chart - Pods credentials issue

### ISSUE THREAD

**Issue by oscarbetancurj** [jfrog/charts#1678]
BUG_REPORT

**Version of Helm and Kubernetes**:

HELM:
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

AWS EKS: 1.22

**Which chart**:

Xray Chart

**Which product license** (Enterprise/Pro/oss):

Enterprise

**What happened**:

When you deploy XRay Helm chart pod xray-0 always keep in state CrashLoopBackOff.

**What you expected to happen**:

Pod has to be in running state.

**How to reproduce it** (as minimally and precisely as possible):

I deployed artifactory:
helm upgrade --install artifactory --set artifactory.masterKey=${MASTER_KEY} --set artifactory.joinKey=${JOIN_KEY} --namespace artifactory jfrog/artifactory

After this, I deployed XRay:
helm upgrade --install xray --set xray.masterKeySecretName=artifactory-master-secret --set xray.joinKeySecretName=artifactory-join-secret --set xray.jfrogUrl=artifactory.artifactory --namespace artifactory jfrog/xray

**Anything else we need to know**:

I have checked the logs and there is a problem with credentials for postgresql and rabbitmq in Xray deployment.
Logs:
2022-10-07 13:38:21.504 GMT [984] FATAL: password authentication failed for user "xray" 
2022-10-07 13:38:21.504 GMT [984] DETAIL: Password does not match for user "xray

Error connecting to rabbit message queue check mq settings. Error: Exception (403) Reason: "username or password not allowed"

I have updated manually the passwords with secret values and errors disappeared...

**Comment by oscarbetancurj** [comment]
@rahulsadanandan Thanks for your answer. Really I have checked the documentation everywhere and default installation only shows as required flags the master and join secrets...
https://www.jfrog.com/confluence/display/JFROG/Installing+Xray#InstallingXray-HelmInstallation
https://www.youtube.com/watch?v=9PDDYsoCFaY

I will take a look into your link. Thanks again. :)

**Comment by oscarbetancurj** [comment]
@rahulsadanandan I am using this command:
helm upgrade --install xray --set xray.masterKeySecretName=artifactory-master-secret --set xray.joinKeySecretName=artifactory-join-secret --set xray.jfrogUrl=artifactory.artifactory --set postgresql.postgresqlPassword=password --set rabbitmq.auth.password=password --namespace artifactory jfrog/xray

RabbitMQ is taking the password value correctly, however postgresql is not. May you tell me please what is the command you are using to install Xray?

Thanks a lot.

**Comment by rahulsadanandan** [comment]
@oscarbetancurj 
a fresh installation creates a random password for PostgreSQL and rabbitmq, and on upgrades, we will have to provide that generated password. 

we can also provide the passwords on fresh installations like the below examples.

``` yaml
databaseUpgradeReady: true
artifactory:
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
postgresql:
  postgresqlPassword: password

```
helm upgrade --install artifactory jfrog/artifactory -f art.yaml


and for xray

```yaml
unifiedUpgradeAllowed: true
databaseUpgradeReady: true
xray:
  jfrogUrl: http://artifactory:8082
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
postgresql:
  postgresqlPassword: password
rabbitmq:
  auth:
    password: guest
```
helm upgrade --install xray jfrog/xray -f xray.yaml
