### ISSUE TITLE
[Feature] Artifactory google-storage support

### ISSUE THREAD

**Issue by Tapanito** [jfrog/charts#170]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

According to the official documentation of Artifactory on filestorage [link](https://www.jfrog.com/confluence/display/RTF/Configuring+the+Filestore) it's possible to use various storage backends when configuring Arifactory. I would like to use google storage as a backend, but it seems that artifactory chart supports only PVC. Are there particular reasons why this is the case?

**Version of Helm and Kubernetes**:

Helm 2.12
Kubernetes: 1.10

**Which chart**:
jfrog/artifactory

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jainishshah17** [comment]
@Tapanito We already have support for google-storage in `artifactory-ha` chart.

**Comment by Tapanito** [comment]
@jainishshah17  Thanks for your reply.
 I understand that `artifactory-ha` supports that, but I was refering to `jfrog/artifactory` chart. Which, as far as I can see, does not support modifying binarystore at all. https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L234
O

**Comment by Tapanito** [comment]
Thanks @jainishshah17,I tried doing that but it seems that this approach is currently blocked by Issue #85

**Comment by eldada** [comment]
@Tapanito - the latest version of the chart, which includes Artifactory version 6.6.X should support this now. Can you test?
We should also support binarystore.xml in the `artifactory` chart. I'll open an issue for this.

**Comment by Tapanito** [comment]
Thank you for your response @eldada, however I'm receiving the error.

I added the following configmap with binarystore.xml:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: binarystore
  labels:
data:
  binarystore.xml: |-
    <!-- Google storage -->
    <config version=v1>
        <chain template=google-storage/>
  
        <provider id=google-storage type=google-storage>
            <endpoint>commondatastorage.googleapis.com</endpoint>
            <bucketName>artifactory</bucketName>
            <identity>gke-service-account@xxx.iam.gserviceaccount.com</identity>
            <credential>{  "type": "service_account", }</credential>
        </provider>
    </config>
```

And I'm installing artifactory with the following values:
```yaml
# Default values for artifactory.
# This is a YAML-formatted file.

# Beware when changing values here. You should know what you are doing!
# Access the values with {{ .Values.key.subkey }}

# Common
ingress:
  enabled: true
artifactory:
  name: artifactory
  image:
    repository: "docker.bintray.io/jfrog/artifactory-oss"
    pullPolicy: IfNotPresent
  preStartCommand: "curl -L -o /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.41.jar https://jcenter.bintray.com/mysql/mysql-connector-java/5.1.41/mysql-connector-java-5.1.41.jar"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  persistence:
    enabled: false
  resources:
   requests:
     memory: "1Gi"
     cpu: "500m"
   limits:
     memory: "2Gi"
     cpu: "1"
  javaOpts:
   xms: "1g"
   xmx: "2g"
 
nginx:
  enabled: false

postgresql:
  enabled: false
database:
  type: mysql
  host: xxx
  port: 3306
  ## If you would like this chart to create the secret containing the db
  ## password, use these values
  user: xxx
  password: xxx
  

```

After running 
`helm install --name artifactory --tiller-namespace artifactory  jfrog/artifactory --namespace artifactory --values=values.yaml`

I see the following error in the kubernetes logs:

```
 Exec lifecycle hook ([/bin/sh -c cp -Lrf /bootstrap/* /artifactory_extra_conf/;
]) for Container "artifactory" in Pod "artifactory-artifactory-0_artifactory(8a5ac0c7-0f54-11e9-81cd-4201ac100013)" failed - error: command '/bin/sh -c cp -Lrf /bootstrap/* /artifactory_extra_conf/;
' exited with 1: cp: cannot create regular file '/artifactory_extra_conf/': Not a directory
, message: "cp: cannot create regular file '/artifactory_extra_conf/': Not a directory\n"
  Normal   Killing  3m38s (x3 over 4m59s)  kubelet, gke-artifactory-master-57a16895-57b7  Killing container with id docker://artifactory:FailedPostStartHook
```
