### ISSUE TITLE
[platform] PDN Server configuration top-level key inconsistent

### ISSUE THREAD

**Issue by bmanuel** [jfrog/charts#1711]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Which chart**:

platform

**What happened**:

The pdn server dependency is enabled via `jfrog-platform.pdnServer.enabled: true` but all configuration for the subchart is under `jfrog-platform.pdn-server`.

**What you expected to happen**:

Both the flag for enabling the subchart and configuring the subchart are under the same top-level key.

**How to reproduce it** (as minimally and precisely as possible):

```
jfrog-platform:
  pdnServer:
    enabled: true
  pdn-server:
    openMetrics:
      enabled: true
```
**Anything else we need to know**:
