### ISSUE TITLE
The helm chart repository index is empty

### ISSUE THREAD

**Issue by cybercapsicum** [jfrog/charts#1734]
After running `helm repo update`, helm charts from the jFrog repository are no longer accessible.
It appears the [index.yaml](https://charts.jfrog.io/index.yaml) is currently empty, only containing the following information.

```yaml
apiVersion: v1
entries: {}
generated: 2023-02-24T16:37:41.621364797Z
```

It would appear one of the recent pushes to the helm repo removed all of the entries.
