### ISSUE TITLE
Router readiness check failed, cannot start Access

### ISSUE THREAD

**Issue by pauloazevedo88** [jfrog/charts#1745]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Version of Helm and Kubernetes**:  Helm: v3.9.1 & Kubernetes: v1.24.3

**Which chart**: repoURL: 'https://charts.jfrog.io' chart: artifactory  targetRevision: 107.55.9

**Which product license** (Enterprise/Pro/oss): Using jfrog/artifactory-pro image from https://github.com/jfrog/charts/blob/17e3ced70f5ca641cc6dd98741d18b063d184c20/stable/artifactory/values.yaml#L270

**What happened**: 
I'm trying to deploy artifactory, via ArgoCD and with an external Postgres, on our K8s cluster in order to test the tool with the following manifest:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "artifactory-alpha-cicd"
  namespace: argocd
spec:
  destination:
    namespace: artifactory
    server: https://api.cicd.alpha.intra.xxxx.io
  project: cicd
  source:
    repoURL: 'https://charts.jfrog.io'
    targetRevision: 107.55.8
    chart: artifactory
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            ingress: 
              enabled: true
              hosts: 
                - artifactory.euc1.alpha.cicd.xxxx.com
              className: "nginx-internal"
            artifactory:
              persistence:
                size: 20Gi
                redundancy: 1
                existingClaim: "artifactory-pvc"
            nginx:
              enabled: false
            postgresql:
              enabled: false
            database:
              type: postgresql
              driver: org.postgresql.Driver
              url: jdbc:postgresql://artifactory-test.xxxx.eu-central-1.rds.amazonaws.com:5432/artifactory?user=artifactory
              username: xxxx
              password: xxxx
  destination:
    server: 'https://api.cicd.alpha.intra.xxxx.io'
    namespace: artifactory
```

I can see the conection with the external DB occurs but i get a 'Router readiness check failed, cannot start Access'. Also tried installing the chart manually following https://artifacthub.io/packages/helm/jfrog/artifactory getting the same result. Is this issue related to the lack of Licence? If so, there a chart/image to use to test Artifactory?

Attaching the a pod logs life:
[logs.txt](https://github.com/jfrog/charts/files/11160884/logs.txt)
