### ISSUE TITLE
RabbitMQ autogenerated TLS certs setting doesn't seem to work

### ISSUE THREAD

**Issue by kmorkans** [jfrog/charts#1811]
Where not able to get RabbitMQ TLS autogenerated TLS certs to work.
JFrog Platform chart: 10.14.6

Tried:
```
global:
  rabbitmq:
    auth:
      tls:
        enabled: true
        autogenerated: true
```
and
```
rabbitmq:
  auth:
    tls:
      enabled: true
      autogenerated: true
```
resulted in `MountVolume.SetUp failed for volume "rabbitmq-ca-certs" : secret "artifactory-rabbitmq-certs" not found`
