### ISSUE TITLE
Jfrog Platform: Artifactory Failing to determine database type on startup

### ISSUE THREAD

**Issue by Souheil-Yazji** [jfrog/charts#1823]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
Helm: 3.7.1
k8s 1.25 (AKS)

**Which chart**:
Jfrog-platform: 10.15.1

**Which product license** (Enterprise/Pro/oss): Enterprise

**JFrog support reference** (if already raised with support team):  - no support issue raised.

**What happened**:
On start up, we see the following:
```2023-09-26T04:58:09.780Z [shell] [INFO ] [] [systemYamlHelper.sh:607       ] [main] - Resolved .shared.database.type (postgresql) from /opt/jfrog/artifactory/var/etc/system.yaml```

then while installerCommon.sh is running:
```.mc.tomcat.connector.sendReasonPhrase key is misplaced or doesnt apply at this location
.federation key is misplaced or doesnt apply at this location
yaml validation failed
2023-09-26T04:58:10.688Z [shell] [WARN ] [] [installerCommon.sh:805        ] [main] - System.yaml validation failed

Database connection check failed Could not determine database type
```
Not sure if these two failures are related, but the database.type seems to be successfully parsed above AND the connection from the mission control service succeeds right after.

`
2023-09-26T04:58:21.319Z [jfmc ] [INFO ] [                ] [.MissionControlApplication:158] [Catalina-utility-3  ] - Connection to database successful
`

**What you expected to happen**:
No failure
RT successfully connects to the external pgdb

**How to reproduce it** (as minimally and precisely as possible):
Create a helm release with all defaults but add to the chart values
If using the jfrog-platform chart::
```
  database:
    initDBCreation: false
    host: <your external pgdb fqdn>
    sslMode: require
    secrets:
      adminUsername:
        name: "admin"
        key: "admin-user"
      adminPassword:
        name: "admin-password"
        key: "admin-password"
```

**Anything else we need to know**:
