### ISSUE TITLE
Potentially Artifactory Frontend UI Bug-Report

### ISSUE THREAD

**Issue by husira** [jfrog/charts#1845]
**BUG REPORT**

We deployed the latest artifactory-pro and artifactory-oss release for our customer: 7.71.5.
For the Artifactory-oss we use the following statefulset.yaml and system.yaml (see files at the bottom).

The Frontend UI seems to be buggy, because after clicking to Administration -> General -> Mail Server Settings and then switch between "Mail Server" and "Settings" the UI goes crazy:

![failure](https://github.com/jfrog/charts/assets/26415718/f0176829-ed4e-40e8-b9f2-e8b9ef392998)

The Browser throws the following console error:
```
vue-router.min.js:11 Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/admin/configuration/general".
    at wt (https://<url>/ui/externals/vue-router/dist/vue-router.min.js:11:16484)
    at _t.confirmTransition (https://<url>/ui/externals/vue-router/dist/vue-router.min.js:11:19437)
    at _t.transitionTo (https://<url>/ui/externals/vue-router/dist/vue-router.min.js:11:18762)
    at e.push (https://<url>/ui/externals/vue-router/dist/vue-router.min.js:11:21810)
    at https://<url>/ui/externals/vue-router/dist/vue-router.min.js:11:26586
    at new Promise (<anonymous>)
    at Vt.push (https://<url>/ui/externals/vue-router/dist/vue-router.min.js:11:26549)
    at n.value (https://<url>/ui/js/chunk-vendors.5d03e18f.js:516:17796)
    at n.value (https://<url>/ui/js/chunk-vendors.5d03e18f.js:516:18050)
    at https://<url>/ui/api/v1/ui/webapp/js/adminMailConfig.js?h=4aadbc789c1cacb77961:1:15846
```

The Frontend Container throws the following logs in a loop:
```
artifactory-0 frontend 2023-12-04T18:45:23.366Z [jffe ] [WARN ] [1bf73b846cdde6af] [frontend-service.log] [main                ] - key is not part of relevant configs: frontend.login.dialog
artifactory-0 frontend 2023-12-04T18:45:23.588Z [jffe ] [WARN ] [365fdc0a8e772d41] [frontend-service.log] [main                ] - key is not part of relevant configs: frontend.login.dialog
artifactory-0 frontend 2023-12-04T18:45:23.809Z [jffe ] [WARN ] [45382934864fa5a8] [frontend-service.log] [main                ] - key is not part of relevant configs: frontend.login.dialog
artifactory-0 frontend 2023-12-04T18:45:24.086Z [jffe ] [WARN ] [587ee7d1cd4f4771] [frontend-service.log] [main                ] - key is not part of relevant configs: frontend.login.dialog
artifactory-0 frontend 2023-12-04T18:45:24.289Z [jffe ] [WARN ] [0e990d0215bf5af6] [frontend-service.log] [main                ] - key is not part of relevant configs: frontend.login.dialog
```

**Version of Helm and Kubernetes**:  Helm v3.13.1 and Kubernetes v1.24

**Which chart**: 107.71.5

**Which product license** (Enterprise/Pro/oss): Pro and oss

**JFrog support reference** (if already raised with support team): no

**What happened**: Frontend UI bug as soon as someone switches between Administration -> General -> Mail Server & Settings

**What you expected to happen**: No UI bug

**How to reproduce it** (as minimally and precisely as possible): Switch configuration between Administration -> General -> Mail Server & Settings

**Anything else we need to know**:

**system.yaml**
```
router:
  serviceRegistry:
    insecure: false
  proxy:
    httpUrl: "http://corp-proxy.internal:8080"
    httpsUrl: "http://corp-proxy.internal:8080"
    ignoredHosts:
    - "localhost"
    - "127.0.0.1"
    - "*svc"
    - "*.svc.cluster.local"
shared:
  logging:
    consoleLog:
      enabled: false
  extraJavaOpts: >
    -Dartifactory.graceful.shutdown.max.request.duration.millis=3000
    -Dartifactory.access.client.max.connections=50
    -Djavax.net.ssl.trustStore=/opt/jfrog/artifactory/app/third-party/java/lib/security/cacerts_custom
  database:
    type: "postgresql"
    driver: "org.postgresql.Driver"
artifactory:
  database:
    maxOpenConnections: 80
  tomcat:
    maintenanceConnector:
      port: 8091
    connector:
      maxThreads: 200
      sendReasonPhrase: false
      extraConfig: acceptCount="400"
frontend:
  session:
    timeMinutes: "30"
access:
  database:
    maxOpenConnections: 80
  tomcat:
    connector:
      maxThreads: 50
      sendReasonPhrase: false
      extraConfig: acceptCount="100"
splitServicesToContainers: true
metadata:
  database:
    maxOpenConnections: 80
jfconnect:
  enabled: false
federation:
  enabled: false
```

**statefulset.yaml**
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: artifactory
    chart: artifactory-107.71.5
    component: artifactory
    heritage: Helm
    release: artifactory
  name: artifactory
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
      release: artifactory
      role: artifactory
  serviceName: artifactory
  template:
    metadata:
      annotations:
        checksum/access-config: bac39781d5c9cecdf5d50786b7305993cdff2e4b905b4e024e2d15177b395dd2
        checksum/binarystore: 1abe2f902a4cc7da51e5df25931d33b203b6f99d37e293d032a1af64d65f7c60
        checksum/database-secrets: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/systemyaml: 0ed1f89aeb0c0ce6f7bac1162b6a4d2dd18ba55b65c6662d5f641bc3fe08ad95
      labels:
        app: artifactory
        chart: artifactory-107.71.5
        component: artifactory
        heritage: Helm
        release: artifactory
        role: artifactory
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: artifactory
                  release: artifactory
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          set -e; if [ -d /artifactory_extra_conf ] && [ -d /artifactory_bootstrap ]; then


            echo "Copying bootstrap config from /artifactory_extra_conf to /artifactory_bootstrap";
            cp -Lrfv /artifactory_extra_conf/ /artifactory_bootstrap/;
          fi; exec /entrypoint-artifactory.sh
        env:
        - name: JF_SHARED_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: artifactory.bitbeam-artifactory-postgres.credentials
        - name: JF_SHARED_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: artifactory.bitbeam-artifactory-postgres.credentials
        - name: JF_SHARED_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: db-url
              name: artifactory
        - name: JVM_MINIMUM_MEMORY
          value: 2048m
        - name: JVM_MAXIMUM_MEMORY
          value: 2048m
        - name: JVM_RESERVED_CODE_CACHE_SIZE
          value: 1024m
        - name: JVM_SUPPORT_RECOMMENDED_ARGS
          value: -Duser.timezone=Europe/Zurich -Djavax.net.ssl.trustStore=/opt/jfrog/artifactory/app/third-party/java/lib/security/cacerts_custom
            -Djavax.net.ssl.trustStorePassword=changeit -Dhttp.proxyHost=corp-proxy.internal
            -Dhttp.proxyPort=8080 -Dhttps.proxyHost=corp-proxy.internal
            -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts="localhost|*.svc|*.svc.cluster.local"
        - name: JF_ROUTER_ENABLED
          value: "true"
        - name: JF_ROUTER_SERVICE_ENABLED
          value: "false"
        - name: JF_EVENT_ENABLED
          value: "false"
        - name: JF_METADATA_ENABLED
          value: "false"
        - name: JF_FRONTEND_ENABLED
          value: "false"
        - name: JF_REPLICATOR_ENABLED
          value: "true"
        - name: JF_REPLICATOR_SERVICE_ENABLED
          value: "false"
        - name: JF_FEDERATION_ENABLED
          value: "false"
        - name: JF_OBSERVABILITY_ENABLED
          value: "false"
        - name: JF_JFCONNECT_SERVICE_ENABLED
          value: "false"
        - name: JF_INTEGRATION_ENABLED
          value: "false"
        - name: SKIP_WAIT_FOR_EXTERNAL_DB
          value: "true"
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/artifactory-oss:7.71.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -s -k --fail --max-time 5 http://localhost:8091/artifactory/api/v1/system/liveness
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: artifactory
        ports:
        - containerPort: 8082
          name: http
        - containerPort: 8081
          name: http-internal
        - containerPort: 8085
          name: http-rtfs
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 400m
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - curl -s -k --fail --max-time 5 http://localhost:8091/artifactory/api/v1/system/readiness
          failureThreshold: 90
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
        - mountPath: /tmp/etc/artifactory/binarystore.xml
          name: binarystore-xml
          subPath: binarystore.xml
        - mountPath: /artifactory_bootstrap/artifactory.cluster.license
          name: artifactory-license
          subPath: license
        - mountPath: /artifactory_bootstrap/info/installer-info.json
          name: installer-info
          subPath: installer-info.json
      - command:
        - /bin/bash
        - -c
        - |
          exec /opt/jfrog/artifactory/app/metadata/bin/jf-metadata start
        env:
        - name: JF_SHARED_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JF_SHARED_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: artifactory.bitbeam-artifactory-postgres.credentials
        - name: JF_SHARED_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: artifactory.bitbeam-artifactory-postgres.credentials
        - name: JF_SHARED_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: db-url
              name: artifactory
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/artifactory-oss:7.71.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8086/api/v1/system/liveness
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: metadata
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8086/api/v1/system/readiness
          failureThreshold: 90
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
      - command:
        - /bin/bash
        - -c
        - |
          exec /opt/jfrog/router/app/bin/entrypoint-router.sh
        env:
        - name: JF_ROUTER_TOPOLOGY_LOCAL_REQUIREDSERVICETYPES
          value: jfrt,jfac,jfob,jfmd,jfevt,jfint,jffe
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/router:7.81.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - while [[ $(curl --fail --silent --connect-timeout 2 http://localhost:8081/artifactory/api/v1/system/liveness)
                =~ OK ]]; do echo Artifactory is still alive; sleep 2; done
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -s -k --fail --max-time 5 http://localhost:8082/router/api/v1/system/liveness
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: router
        ports:
        - containerPort: 8082
          name: http
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -s -k --fail --max-time 5 http://localhost:8082/router/api/v1/system/readiness
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - curl -s -k --fail --max-time 5 http://localhost:8082/router/api/v1/system/readiness
          failureThreshold: 30
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/opt/jfrog/router
          name: artifactory-volume
      - command:
        - /bin/bash
        - -c
        - |
          exec /opt/jfrog/artifactory/app/third-party/node/bin/node /opt/jfrog/artifactory/app/frontend/bin/server/dist/bundle.js /opt/jfrog/artifactory/app/frontend
        env:
        - name: JF_SHARED_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/artifactory-oss:7.71.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8070/api/v1/system/liveness
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: frontend
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8070/api/v1/system/readiness
          failureThreshold: 90
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
      - command:
        - /bin/bash
        - -c
        - |
          exec /opt/jfrog/artifactory/app/event/bin/jf-event start
        env:
        - name: JF_SHARED_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/artifactory-oss:7.71.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8061/api/v1/system/liveness
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: event
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8061/api/v1/system/readiness
          failureThreshold: 90
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
      - command:
        - /bin/bash
        - -c
        - |
          exec /opt/jfrog/artifactory/app/integration/bin/jf-integration start
        env:
        - name: JF_SHARED_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/artifactory-oss:7.71.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8071/api/v1/system/liveness
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: integration
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8071/api/v1/system/readiness
          failureThreshold: 90
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
      - command:
        - /bin/bash
        - -c
        - |
          exec /opt/jfrog/artifactory/app/observability/bin/jf-observability start
        env:
        - name: JF_SHARED_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/artifactory-oss:7.71.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8036/api/v1/system/liveness
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: observability
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --max-time 5 http://localhost:8036/api/v1/system/readiness
          failureThreshold: 90
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
      initContainers:
      - command:
        - bash
        - -c
        - rm -fv /var/opt/jfrog/artifactory/etc/db.properties
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/ubi-minimal:9.2.750.1697534106
        imagePullPolicy: IfNotPresent
        name: delete-db-properties
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
      - command:
        - bash
        - -c
        - |
          echo "Preparing /var/opt/jfrog/artifactory/etc/access/bootstrap.creds"; mkdir -p /var/opt/jfrog/artifactory/etc/access; cp -Lrf /tmp/access/bootstrap.creds /var/opt/jfrog/artifactory/etc/access/bootstrap.creds; chmod 600 /var/opt/jfrog/artifactory/etc/access/bootstrap.creds;
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/ubi-minimal:9.2.750.1697534106
        imagePullPolicy: IfNotPresent
        name: access-bootstrap-creds
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
        - mountPath: /tmp/access/bootstrap.creds
          name: access-bootstrap-creds
          subPath: admin-password
      - command:
        - /bin/bash
        - -c
        - |
          if [[ -e "/var/opt/jfrog/artifactory/etc/filebeat.yaml" ]]; then chmod 644 /var/opt/jfrog/artifactory/etc/filebeat.yaml; fi; echo "Copy system.yaml to /var/opt/jfrog/artifactory/etc"; mkdir -p /var/opt/jfrog/artifactory/etc; mkdir -p /var/opt/jfrog/artifactory/etc/access/keys/trusted; cp -fv /tmp/etc/system.yaml /var/opt/jfrog/artifactory/etc/system.yaml; echo "Copy binarystore.xml file"; mkdir -p /var/opt/jfrog/artifactory/etc/artifactory; cp -fv /tmp/etc/artifactory/binarystore.xml /var/opt/jfrog/artifactory/etc/artifactory/binarystore.xml; echo "Copy access.config.patch.yml to /var/opt/jfrog/artifactory/etc/access"; mkdir -p /var/opt/jfrog/artifactory/etc/access; cp -fv /tmp/etc/access.config.patch.yml /var/opt/jfrog/artifactory/etc/access/access.config.patch.yml; echo "Copy joinKey to /var/opt/jfrog/artifactory/bootstrap/access/etc/security"; mkdir -p /var/opt/jfrog/artifactory/bootstrap/access/etc/security; echo -n ${ARTIFACTORY_JOIN_KEY} > /var/opt/jfrog/artifactory/bootstrap/access/etc/security/join.key; echo "Copy masterKey to /var/opt/jfrog/artifactory/etc/security"; mkdir -p /var/opt/jfrog/artifactory/etc/security; echo -n ${ARTIFACTORY_MASTER_KEY} > /var/opt/jfrog/artifactory/etc/security/master.key;
        env:
        - name: ARTIFACTORY_JOIN_KEY
          valueFrom:
            secretKeyRef:
              key: join-key
              name: artifactory
        - name: ARTIFACTORY_MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: master-key
              name: artifactory
        image: releases-docker.jfrog.io/jfrog/artifactory-oss/jfrog/ubi-minimal:9.2.750.1697534106
        name: copy-system-configurations
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/opt/jfrog/artifactory
          name: artifactory-volume
        - mountPath: /tmp/etc/system.yaml
          name: systemyaml
          subPath: system.yaml
        - mountPath: /tmp/etc/artifactory/binarystore.xml
          name: binarystore-xml
          subPath: binarystore.xml
        - mountPath: /tmp/etc/access.config.patch.yml
          name: access-config
          subPath: access.config.patch.yml
      securityContext:
        fsGroup: 1030
        runAsNonRoot: true
        runAsUser: 1030
      serviceAccountName: artifactory
      terminationGracePeriodSeconds: 40
      volumes:
      - configMap:
          name: java-keystore-cacert-6kct9c645g
        name: java-keystore-cacert
      - name: artifactory-volume
        persistentVolumeClaim:
          claimName: artifactory-volume-artifactory
      - name: artifactory-license
        secret:
          secretName: artifactory
      - name: access-bootstrap-creds
        secret:
          secretName: artifactory
      - configMap:
          name: artifactory-installer-info
        name: installer-info
      - name: systemyaml
        secret:
          secretName: artifactory-systemyaml-gbt595799k
      - name: access-config
        secret:
          secretName: artifactory-access-config-2h79g65gch
      - name: binarystore-xml
        secret:
          secretName: artifactory-binarystore-d55tk5f2fk
  updateStrategy:
    type: RollingUpdate
```
