### ISSUE TITLE
Can you tell me to access through s3, then where should I fill in my ak and sk

### ISSUE THREAD

**Issue by xujy1991** [jfrog/charts#1868]
I don't see where to fill in ak and sk. Don't you need to fill in accesskey and secretkey of object storage to access s3?
awsS3V3:
      testConnection: true
      identity:
      credential:
      region: zj
      bucketName: 
      path: artifactory/filestore
      endpoint: 
      port:
      useHttp:
      maxConnections: 50
      connectionTimeout:
      socketTimeout:
      kmsServerSideEncryptionKeyId:
      kmsKeyRegion:
      kmsCryptoMode:
      useInstanceCredentials: true
      usePresigning: false
      signatureExpirySeconds: 300
      signedUrlExpirySeconds: 30
      cloudFrontDomainName:
      cloudFrontKeyPairId:
      cloudFrontPrivateKey:
      enableSignedUrlRedirect: false

**Comment by gitta-jfrog** [comment]
Hi @xujy1991 

The recommended way is to use the IAM role with ServiceAccount. You can find more details about this configuration [here](https://jfrog.com/help/r/active/artifactory-connect-artifactory-to-s3-bucket-with-iam-role).

If you would like to use the AccessKey and SecretKey you can do it by configuring:
```
awsS3V3:
  identity: AccessKey
  credential: SecretKey
```

**Comment by xujy1991** [comment]
> Hi @xujy1991
> 
> The recommended way is to use the IAM role with ServiceAccount. You can find more details about this configuration [here](https://jfrog.com/help/r/active/artifactory-connect-artifactory-to-s3-bucket-with-iam-role).
> 
> If you would like to use the AccessKey and SecretKey you can do it by configuring:
> 
> ```
> awsS3V3:
>   identity: AccessKey
>   credential: SecretKey
> ```

Thank you. So for the type s3-storage-v3-direct, is it configured in binarystore.xml? The exception is that binarystore.xml needs to be modified in pod after the service is deployed?

**Comment by gitta-jfrog** [comment]
The binarystore.xml will be [generated](https://github.com/jfrog/charts/blob/master/stable/artifactory/files/binarystore.xml#L161) according to the values.yaml configuration - No need to update the binarystore.xml in the pod level.
see example:

```
artifactory:
  persistence:
    type: s3-storage-v3-direct
    awsS3V3:
      testConnection: false
      identity:
      credential:
      region:
      bucketName: artifactory-aws
      path: artifactory/filestore
      endpoint:
  ```
