### ISSUE TITLE
[xray] Incorrect formatting for `volumeMounts` for panoramic

### ISSUE THREAD

**Issue by rhys96** [jfrog/charts#1895]
**Is this a request for help?**:

Yes, I will submit a PR shortly.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT.

**Version of Helm and Kubernetes**:

```bash
$ helm version

version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

Kubernetes version: 1.29

**Which chart**:

xray.

**Which product license** (Enterprise/Pro/oss):

Enterprise.

**JFrog support reference** (if already raised with support team): 

Haven't raised.

**What happened**:

When attempting to install the `xray` chart when using custom volumes, I encountered the following error:

```
Error: INSTALLATION FAILED: YAML parse error on xray/templates/xray-statefulset.yaml: error converting YAML to JSON: yaml: line 475: did not find expected key
```

**What you expected to happen**:

I expected the following output:

```
NAME: xray
LAST DEPLOYED: Mon Jul  1 16:51:42 2024
NAMESPACE: jfrog
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Congratulations! JFrog Xray services are deployed!
```

**How to reproduce it** (as minimally and precisely as possible):

Create EKS cluster with secrets-store CSI driver.

Create secret containing the trusted certificate for RDS.

__NOTE:__ We use RDS in our deployment, but any additional volume mount will cause the xray deployment to fail.

Create `values.yaml` file.

```yaml
---
global:
  customVolumes: |
    - name: rds-cert-bundle
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: rds-cert-bundle-secret

  customVolumeMounts: |
    - name: rds-cert-bundle
      mountPath: "/mnt/trusted-certs"
      readOnly: true

xray:
  jfrogUrl: https://<URL>
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
```

Install `xray`.

```bash
$ helm repo add jfrog https://charts.jfrog.io
$ helm repo update
$ helm install -f values.yaml -f sizing/xray-xsmall.yaml xray jfrog/xray
```

**Anything else we need to know**:

I've narrowed down the issue to Line 1039 in `xray-statefulset.yaml`. The initial volume mount is out of alignment compared to the custom volume mounts.

To identify that formatting error:

Debug the xray chart output.

```bash
$ helm template xray jfrog/xray -f values.yaml -f sizing/xray-xsmall.yaml --debug > output.yaml
```

Run `yamllint` against the outputted YAML file.

```bash
$ yamllint output.yaml
...
780:9     error    syntax error: expected <block end>, but found '-' (syntax)
...
```

Show the error. 

```bash
$ cat -n output.yaml | sed `777,782!d`
777          volumeMounts:
778            - name: data-volume
779              mountPath: "/var/opt/jfrog/xray"
780          - name: rds-cert-bundle
781            mountPath: "/mnt/trusted-certs"
782            readOnly: true
```

Recommended change:

`Original`
```yaml
volumeMounts:
  - name: data-volume
    mountPath: "{{ .Values.xray.persistence.mountPath }}"
```

`Fixed`
```yaml
volumeMounts:
- name: data-volume
  mountPath: "{{ .Values.xray.persistence.mountPath }}"
```
