### ISSUE TITLE
Artifactory not upgradable with Flux

### ISSUE THREAD

**Issue by ktarplee** [jfrog/charts#1914]
I am using Flux to install the artifactory chart.  During an upgrade it looks like flux set the version of the chart to `107.90.8+2`.  The `+2` is what is causing the artifactory helm chart issues.  See this [line](https://github.com/jfrog/charts/blob/f5d30fbcb3ee8049f7e5e18905018572536b7aca/stable/artifactory/templates/artifactory-configmaps.yaml#L8).  `artifactory-107.80.8+2` is not a valid label value due to the `+`.  IMHO the `chart` label should be an annotation instead since it is not used in a label selector.  Alternatively it can be sanitized to be a valid label.

To reproduce this without flux simply set the version in the Chart.yaml to `107.90.8+2` then run helm install to see the error.

My current workaround is to use a post render to fix the chart.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory
spec:
...
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: ConfigMap
              name: artifactory-configmaps
            patch: |
              - op: remove
                path: /metadata/labels/chart
```

I am using artifactory 107.90.8 and helm version v3.15.4.
