### ISSUE TITLE
[Need help] - EBS Mount

### ISSUE THREAD

**Issue by hikouki-gumo** [jfrog/charts#1930]
I want to deploy Artifactory on EC2 and use EBS as storage. EC2 is launch automatically with a block storage (named /dev/xvdc).

To use this EBS as storage, I will need to mount /var/opt/jfrog/artifactory to EBS. I check the values.yaml but quite confuse, I guess there is something to do with customVolumes/customVolumeMounts or persistent.

Could you pls show me what is the correct way to do?

**Comment by Alexhha** [comment]
What do you mean on EC2 ? Are you using EC2 as EKS node ?

**Comment by hikouki-gumo** [comment]
Hi @Alexhha , yes, it's an EC2 node in my EKS cluster.

**Comment by Alexhha** [comment]
> EC2 is launch automatically with a block storage (named /dev/xvdc).

` /dev/xvdc` is that a root block storage ? If so EKS will use it by default no additional steps are required

**Comment by hikouki-gumo** [comment]
No, /dev/xvdc is not root device volume, it is additional EBS volumes (block device mapping).

Please see config below.
I don't want to use root storage `(dev/xvda)` to store artifactory, I want to store on block device mapping `(/dev/xvdc)` instead.

Reference: [Block device mapping concepts](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html).

```
blockDeviceMappings:
            - deviceName: /dev/xvda
              ebs:
                volumeSize: 25
            - deviceName: /dev/xvdc
              ebs:
                volumeSize: 1000
```

**Comment by oumkale** [comment]
Hi @hikouki-gumo,

Thank you for creating the issue. We are happy to help you!

You can follow these steps:

1. Check the [storage reference](https://aws.amazon.com/blogs/storage/persistent-storage-for-kubernetes/).
2. Create the required resources yourself and use `customVolumes` and `customVolumeMounts`. See this [reference](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L536) for guidance.


Example:
Create an EBS Volume: First, ensure that you have an EBS volume created in your AWS account and storage class is created in cluster. Note the volume ID:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-volume
spec:
  capacity:
    storage: 10Gi  # Adjust according to your needs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  awsElasticBlockStore:
    volumeID: "aws://us-west-2a/vol-xxxxxxxx"  # Replace with your volume ID
    fsType: ext4  # Change if you're using a different filesystem
```

Create a PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Must match or be less than the PV
  storageClassName: ebs-sc

```
How to custom volume and volume mounts in values.yaml

Sample:
```
 artifactory:
    customVolumes: |
      # - name: custom-script
      #   configMap:
      #     name: custom-script
    ## Add custom volumesMounts
    customVolumeMounts: |
      # - name: custom-script
      #   mountPath: "/scripts/script.sh"
      #   subPath: script.sh
      # - name: posthook-start
      #   mountPath: "/scripts/posthoook-start.sh"
      #   subPath: posthoook-start.sh
      # - name: prehook-start
      #   mountPath: "/scripts/prehook-start.sh"
      #   subPath: prehook-start.sh
```

**Comment by oumkale** [comment]
Hi @hikouki-gumo,

Thank you for creating the issue. We are happy to help you!

You can follow these steps:

1. Check the [storage reference](https://aws.amazon.com/blogs/storage/persistent-storage-for-kubernetes/).
2. Examples with k8s manifests: [aws ebs examples](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes) 
3. Create the required resources by yourself and use `customVolumes` and `customVolumeMounts`. See this [reference](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L536) for guidance.

Or you may explore this if it suits for your use case: [customPersistentVolumeClaim](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L552)

How to custom volume and volume mounts in values.yaml

Sample:
```
 artifactory:
    customVolumes: |
      # - name: custom-script
      #   configMap:
      #     name: custom-script
    ## Add custom volumesMounts
    customVolumeMounts: |
      # - name: custom-script
      #   mountPath: "/scripts/script.sh"
      #   subPath: script.sh
      # - name: posthook-start
      #   mountPath: "/scripts/posthoook-start.sh"
      #   subPath: posthoook-start.sh
      # - name: prehook-start
      #   mountPath: "/scripts/prehook-start.sh"
      #   subPath: prehook-start.sh
```

Note: This solution is specific to the questions raised in the issue.

**Comment by Alexhha** [comment]
> I don't want to use root storage (dev/xvda) to store artifactory, I want to store all data of artifactory on block device mapping (/dev/xvdc) instead.

you have to prepare pv/pvc 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-artifactory-data
spec:
  volumeName: custom-artifactory-data
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-artifactory-data
spec:
  capacity:
    storage: 1000Gi
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-123456789
```
and then specify pvc in the `.artifactory.persistence.existingClaim`
```
artifactory:
  persistence:
    enabled: true
    existingClaim: custom-artifactory-data
```
