### ISSUE TITLE
jfrog/artifactory chart Failed to pull image "docker.bintray.io/jfrog/artifactory-pro:6.7.0"

### ISSUE THREAD

**Issue by karlriley-wsu** [jfrog/charts#194]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report?

**Version of Helm and Kubernetes**:
```
karlriley@erp-ssh-dev-f8b9fcf4f-6d29v:~$ export KUBECONFIG=/home/karlriley/.bluemix/plugins/container-service/clusters/wsu-esg-dev/kube-config-dal10-wsu-esg-dev.yml
karlriley@erp-ssh-dev-f8b9fcf4f-6d29v:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5+IKS", GitCommit:"93ab2680ca982746b1cc0827f59bb53143ebfc08", GitTreeState:"clean", BuildDate:"2018-12-03T21:32:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
karlriley@erp-ssh-dev-f8b9fcf4f-6d29v:~$ helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

**Which chart**:
jfrog/artifactory

**What happened**:
In IBM Cloud Kubernetes, the main artifactory image will not pull.  Getting this error:
Failed to pull image "docker.bintray.io/jfrog/artifactory-pro:6.7.0": rpc error: code = Unknown desc = failed to resolve image "docker.bintray.io/jfrog/artifactory-pro:6.7.0": invalid size header: "": strconv.ParseInt: parsing "": invalid syntax

This image works fine if I try to 'docker run' it from my desktop.

**What you expected to happen**:
For the image to be pulled and run by Kubernetes

**How to reproduce it** (as minimally and precisely as possible):
In IBM Cloud Container service, set KUBECONFIG environment variable per IBM docs for the cluster, then do this:
```
$ helm repo add jfrog https://charts.jfrog.io
$ helm install --name artifactory jfrog/artifactory
```

**Anything else we need to know**:

**Comment by jainishshah17** [comment]
You will need to do the following:
```
#Create file image_policy.yaml with the following content
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: artifactory
spec:
  repositories:
  - name: docker.bintray.io/jfrog/*
    policy:
      va:
        enabled: false
```

```
# Apply image policy
kubectl apply -f  image_policy.yaml
```
