### ISSUE TITLE
Question regarding Cache FS and how it evicts

### ISSUE THREAD

**Issue by usrme** [jfrog/charts#1943]
I have a setup with a really large cache (see snippet from values file below) and I'm not sure based on what criteria exactly the eviction from local disk to S3 is being made. Based on this [white paper](https://jfrog.com/whitepaper/best-practices-for-managing-your-artifactory-filestore-2/) it’s based on access times:

> Since the maximum size can be set, artifacts in this cache will “rotate” based on their last downloaded date or creation/modified date.

But I have a concrete example of a blob that was created today (at the time of writing) that is already stored in S3:

```console
$ stat /var/opt/jfrog/artifactory/data/cache/ff/ff7e66484d8723c7f1a7b1622e018604c2131581
  File: /var/opt/jfrog/artifactory/data/cache/ff/ff7e66484d8723c7f1a7b1622e018604c2131581
  Size: 34946           Blocks: 72         IO Block: 4096   regular file
Device: 10303h/66307d   Inode: 825388      Links: 1
Access: (0640/-rw-r-----)  Uid: ( 1030/artifactory)   Gid: ( 1030/artifactory)
Access: 2024-11-26 08:34:34.979291773 +0000
Modify: 2024-11-26 08:34:34.971291759 +0000
Change: 2024-11-26 08:34:34.971291759 +0000
 Birth: 2024-11-26 08:34:34.971291759 +0000
```

![Image](https://github.com/user-attachments/assets/ce2858d0-6a2c-4b90-a341-ddfecb1e5564)

I'd really love some clarification around this and to learn if I've possibly misconfigured something. I tried to `grep` the name of the blob across `/var/opt/jfrog/artifactory/log` and `/opt/jfrog/artifactory/var/log`, but nothing came up.

Could it be that I'm misunderstanding that significance of the files in that directory and that they end up there _after_ whatever the configured cache settings are for any given remote repository? If so, where do they reside before they end up in that directory then and how does the S3 storage relate to the cache directory?

---

Snippet from values file regarding persistence:

```yaml
---
persistence:
  mountPath: /var/opt/jfrog/artifactory
  enabled: true
  size: 500Gi
  accessMode: ReadWriteOnce
  cacheProviderDir: /var/opt/jfrog/artifactory/data/cache
  # 450GB
  maxCacheSize: 450000000000
  type: aws-s3-v3
  awsS3V3:
    bucketName: bucket-name
    region: eu-west-1
    path: artifactory/filestore
    endpoint: s3.amazonaws.com
    roleName: artifactory-role
    testConnection: true
```

Chart version: 107.90.8.
