### ISSUE TITLE
[xray] rabbitmq.auth.password must be set

### ISSUE THREAD

**Issue by juame** [jfrog/charts#1961]
It is required to set a non-default password for `rabbitmq.auth.password` after the latest change:
https://github.com/jfrog/charts/blob/c277c351ca449d5a2a1a97202a284e6631293b93/stable/xray/templates/keys-warnings.yaml#L1-L3

Unfortunately, it seems that the password in RabbitMQ is set from `rabbitmq.auth.password`. However, Xray is using the password defined in `rabbitmq.auth.existingPasswordSecret` (key `rabbitmq-password`).
Xray is unable to start if the `password` does not match the password in the secret key `rabbitmq-password`.

Helm values:
```
rabbitmq:
  auth:
    username: xrayuser
    password: password-set-in-rabbitmq
    existingPasswordSecret: xray-rabbitmq-creds # key: `rabbitmq-password`
```

I would expect that we could simply set the password in `existingPasswordSecret` and have it used by both Xray and RabbitMQ.

**Comment by rahulsadanandan** [comment]
Hi @juame, `rabbitmq.existingPasswordSecret` is not currently supported. Since we have custom loadDefinitions, the password needs to be specified there, and we reference it from `rabbitmq.auth.password` We will create an internal ticket and see how we can fix this. 

Regarding the question 
> It is required to set a non-default password for rabbitmq.auth.password after the latest change 

yes this is required now

**Comment by engnatha** [comment]
What's the proper way to not hardcode secrets in values files? When using tools like fluxcd/argocd where you can specify helm values in a repository, this pattern requires committing credentials to a visible repo.

**Comment by zbialik** [comment]
I have also hit this issue and noticed that setting the `rabbitmq.auth.password` to some other invalid string does not fix the issue. It just avoid the helm check issue. 

I think this is a result of [this commit](https://github.com/jfrog/charts/commit/ce7c5e65678300fc9099e73a5e16c94701ca2d44) which relies on the `rabbitmq.auth.password` to define the `load_definition` secret, where that file should somehow be able to reference an external secret that we define under `rabbitmq.auth.existingPasswordSecret`.

**Comment by zbialik** [comment]
I think the best way to workaround this is to rely on one of these new helm values

```
rabbitmq:
    extraSecrets:
    load-definition:
      load_definition.json: 
  loadDefinition:
    enabled: true
    existingSecret: '{{ .Release.Name }}-load-definition'
```
