### ISSUE TITLE
[Artifactory] OpenMetrics System Yaml Error

### ISSUE THREAD

**Issue by vronnG-dw** [jfrog/charts#1962]
`Helm Chart 107.104.6`
`Artifactory version 7.104.6`

According to Jfrog Artifactory doc, To enable metrics in Artifactory, add the following values to the [Artifactory System YAML](https://jfrog.com/help/access?ft:clusterId=UUID-cc715606-b07f-c45b-5b8f-5906bd88f244) file and restart Artifactory for it to take effect:
ref: https://jfrog.com/help/r/jfrog-platform-administration-documentation/open-metrics
```
shared:
    metrics:
        enabled: true
artifactory:
    metrics:
        enabled: true
```
but looks like in helm chart doesn't support metrics for artifactory but only for shared.
https://github.com/jfrog/charts/blob/master/stable/artifactory/files/system.yaml#L13C1-L13C46

Verified by installing the helm chart too:
Values:

```
artifactory:
  metrics:
    enabled: true
    filebeat:
      enabled: true
      elasticsearch:
        url: "http://localhost:8082/elasticsearch"
        username: xxxx
        password: xxxx
```

System.yaml (removed the unnecessary options, irrelevant of the issue 

```
artifactory:
    database:
        maxOpenConnections: 100
    tomcat:
        connector:
            extraConfig: acceptCount="400"
            maxThreads: 200
            sendReasonPhrase: false
        maintenanceConnector:
            port: 8091
shared:
    metrics:
        enabled: true
        filebeat:
            elasticsearch:
                password: xxx
                url: http://localhost:8082/elasticsearch
                username: xxx
            enabled: true
            log:
                enabled: false
                level: info
```
