### ISSUE TITLE
Artifactory upgrade fails when upgrading from version 6.23.7 to 7.104.9

### ISSUE THREAD

**Issue by NimalDas** [jfrog/charts#1971]
Is this a BUG REPORT or FEATURE REQUEST? (choose one): Bug Report

**Version of  Kubernetes:**
K8s: v1.30.1

**Which chart:**
8.10.2

Which product license (Enterprise/Pro/oss): Pro

**Issue:**

We have artifactory version 6.23.7 running in a OKE cluster. In order to migrate it to the latest version, i followed the instructions in the below documentation.
https://jfrog.com/help/r/jfrog-installation-setup-documentation/artifactory-version-6.x-to-7.x-upgrade-with-helm

In our cluster application are installed and managed via argocd in app-of-apps pattern.
After deleting stateful set artifactory-postgres and syncing the application from argocd after updating the chart version, I get the below error from postgres pod.

"**The data directory was initialised by postgres version 9.6, which is not compatible with this version 15.6**"

Below is my helm values file used by argocd

```
databaseUpgradeReady: true
artifactory:
  license:
    secret: artifactory-license
    dataKey: artifactory.lic
  postgresql:
    enabled: true
  migration:
    enabled: true
  customVolumes: |
    - name: rtdestexport-cv
      persistentVolumeClaim:
        claimName: rtdestexport-claim

  customVolumeMounts: |
    - name: rtdestexport-cv
      mountPath: /rtdestexport-cv

  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1030
    runAsGroup: 1030
    fsGroup: 1030
    fsGroupChangePolicy: "OnRootMismatch"

global:
  versions: {}
nginx:
  enabled: false


```
