### ISSUE TITLE
Xray Pod CrashLoopBackOff Due to Database Connection Issue (MSSQL) 

### ISSUE THREAD

**Issue by mmoreno2** [jfrog/charts#2002]
Hello,

I am attempting to deploy Xray to my AKS cluster, but the pod is stuck in a ``CrashLoopBackOff`` state. The containers are failing to connect to the database with the following error:

```
Database ping failed with error dial tcp 10.244.4.54:5432: connect: connection refused
```

In my values.yaml file, I have configured Xray to use an MSSQL database, not PostgreSQL:
```
postgresql:
  enabled: false

waitForDatabase: false
database:
  type: mssql
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: "sqlserver://xxx:1433;databaseName=xray-database;sendStringParametersAsUnicode=false;encrypt=false;trustServerCertificate=true;loginTimeout=30;"
  secrets:
    user:
      name: "xxx"
      key: "username"
    password:
      name: "xxx"
      key: "password"
    url:
      name: "xxx"
      key: "db-url"
```

I came across [this documentation](https://jfrog.com/help/r/quick-debugging-tips-for-xray-db-connectivity/quick-debugging-tips-for-xray-db-connectivity), which advised removing the jdbc: prefix from the URL, which I have already done.

I checked the [System Requirements](https://jfrog.com/help/r/jfrog-installation-setup-documentation/database-and-third-party-applications-in-xray), but didn't see any explicit restrictions regarding MSSQL.

Could you please confirm whether MSSQL is officially supported for Xray? If so, is there anything else I need to do to ensure that Xray uses the correct database URL and does not attempt to connect to PostgreSQL?

Thank you!
