### ISSUE TITLE
Illegal endpoint: 's3.my.domain.net'. This endpoint is not supported.

### ISSUE THREAD

**Issue by deaksmaestro** [jfrog/charts#2010]
Helm Chart: 107.111.10
Artifactory Pro: 7.111.9

I have been unable to get the `s3-storage-v3-direct` backend storage working, with the above error given when attempting to upload an artefact to a repo.

During startup I see the following log with no errors (I reverted to using http just to count out TLS issues as the cause):
`Connecting to S3 endpoint: http://s3.my.domain.net:8080`

Helm chart config is
```
awsS3V3:
      testConnection: false
      identity: unsername
      credential: password
      region: myregion
      bucketName: artifactory-dev
      path: artifactory/filestore
      endpoint: s3.my.domain.net
      port: 8080
      useHttp: true
      useInstanceCredentials: false
```

Further Context
- I have a valid Artifactory Pro license.
- My s3 solution is a self hosted Ceph instance
