### ISSUE TITLE
postgres requirement chart is ignoring existingSecret

### ISSUE THREAD

**Issue by Xnyle** [jfrog/charts#202]
I'm trying to convince the "bundled" postgres of the artifactory chart  to always use the same secret as i need that for backing up/restoring pv.

From my values.

```
postgresql:
  persistence:
    storageClass: my-special-class
    size: 5Gi
  #not working, and injecting my own secret b4 deploy doesnt work either
  existingSecret: my-own-artifactory-postgresql
```

existingSecret is ignored. postgres always creates a new one and uses that.
Creating my own secret before deployment does also not work, cause helm refuses to install in that case:

`Error: release artifactory failed: secrets "artifactory-postgresql" already exists`
