### ISSUE TITLE
[Proposal] Upgrade postgresql chart dependency (for artifactory and artifactory-ha) to get securityContext and pgsql 10.x

### ISSUE THREAD

**Issue by zendril** [jfrog/charts#286]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:

**Which chart**:
artifactory and artifactory-ha

**What happened**:
We currently pull in a really old version of the postgresql chart which is 9.x postgresql install.

This is an issue because these older versions of the chart do not support securityContext which  then breaks many installs where pods are not allowed to be run as root.

**What you expected to happen**:
Upgrade to a newer version of the postgresql chart that pulls in postgresql 10.x and supports securityContext.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
According to https://www.jfrog.com/confluence/display/RTF/Configuring+the+Database artifactory will support Postgresql >= 9.2. 

Part of the real reason for asking to upgrade the chart is that the old version of the postgresql chart does not allow for securityContext, so I have to manually override the template to include it given that we cannot run our pods as root.

**Comment by eldada** [comment]
We are sticking with PostgreSQL 9.6.11 for now as it's aligned across our products for now.
It would be great to get the new PG chart to support the 9.6.11 image version.
If you can try it (probably needs some adapting) and let us know, we'll be happy to enjoy these new features.

**Comment by eldada** [comment]
I did a quick check and tested the latest helm chart version (postgresql-3.16.0) with a tag `9.6.11`
```
helm install --name pg --set image.tag=9.6.11 stable/postgresql 
```
And it seems to work properly.
It also uses a StatefulSet for PostgreSQL, which is much better for us.

Do you want to try and plot a migration for existing chart (0.9.5) to (3.16.0)? This is the tricky bit 😉

**Comment by zendril** [comment]
> I did a quick check and tested the latest helm chart version (postgresql-3.16.0) with a tag `9.6.11`
> 
> ```
> helm install --name pg --set image.tag=9.6.11 stable/postgresql 
> ```
> And it seems to work properly.
> It also uses a StatefulSet for PostgreSQL, which is much better for us.
> 
> Do you want to try and plot a migration for existing chart (0.9.5) to (3.16.0)? This is the tricky bit

Yeah, good thought, that will work as well.

I'm doing sort of a hybrid right now as I'm deleting the 0.9.5 version of the chart and pulling 1.0.0 and then just adding in my securityContext in a custom template override while still using 9.6.x version of pgsql.

Any pointers/tips I should be looking for that you think might be tricky about moving from 0.9.5 to 3.16.10?
Is there something I need to be aware of when having end users doing helm upgrade or something?

**Comment by eldada** [comment]
I think the biggest challenge is the move from Deployment to StatefulSet, which means the storage will not be upgraded easily.
Maybe a solution will be to pass the previously created PVC to the new postgresql chart as `persistence.existingClaim` for upgrades.
If you just run an upgrade of 3.16.0 over 0.9.5, the existing PV and PVC are removed and new ones are created... tricky.

**Comment by scphantm** [comment]
I am building out a brand new system, OKD 3.11 and encountered this.  the published helm for artifactory is useless for me because corp policy won't let me run anything root.  If i install postgres manually using the latest postgres helm, then run the helm for artifactory, will artifactory see postgres is already there and hook up everything properly?

**Comment by jainishshah17** [comment]
@scphantm You can use https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#use-an-external-database

**Comment by scphantm** [comment]
I am trying passing my own values in.  I have a secret with my postgres user/pass in it, and i am passing this values file

```
artifactory:
  license:
    secret: artifactory-license-secret
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi
  javaOpts:
    xms: 1g
    xmx: 4g
  persistence:
    type: nfs
    storageClass: managed-nfs-storage
    nfs:
      ip: "10.65.225.11"
#      haDataMount: "/artifactory-data"
#      haBackupMount: "/artifactory-backup"
#      dataDir: "/var/opt/jfrog/artifactory"
#      backupDir: "/var/opt/jfrog/artifactory-backup"
      dataDir: "/artifactory-data"
      backupDir: "/artifactory-backup"
      capacity: "1000Gi"

nginx:
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 250m
      memory: 500Mi
  persistence:
    enabled: true
    size: 5Gi
    storageClass: managed-nfs-storage

postgresql:
  enabled: false

database:
  type: postgresql
  host: 172.30.231.166
  port: 5432
  secrets:
    user:
      name: artifactory-postgres
      key: user
    password:
      name: artifactory-postgres
      key: password
```

No matter what i do, it fails to start saying that authentication failed for user `artifactory`.  Problem is, thats not the user name specified in the secret.  Its like its not picking up the secret at all and defaulting to `artifactory`
