### ISSUE TITLE
License key not found

### ISSUE THREAD

**Issue by scphantm** [jfrog/charts#297]
**Is this a request for help?**:
yes

i have been struggling with this for days now.  I finally got artifactory to connect to my external postgres ( i had to reinstall postgres container and set the root user as `artifactory` before it would work) but im beyond that.  Now i can't get it to read the stupid license secret.

I generated the secret with the same command line thats in the readme file.  Then i create this values yaml

`oc create secret generic artifactory-license --from-file=license-key=./artifactory-license.lic`

```
artifactory:
  license:
    secret: artifactory-license
    dataKey: license-key
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi
  javaOpts:
    xms: 1g
    xmx: 4g
  persistence:
    type: nfs
    storageClass: managed-nfs-storage
    nfs:
      ip: "10.65.225.11"
      dataDir: "/artifactory-data"
      backupDir: "/artifactory-backup"
      capacity: "1000Gi"

nginx:
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 250m
      memory: 500Mi
  persistence:
    enabled: true
    size: 5Gi
    storageClass: managed-nfs-storage

postgresql:
  enabled: false

database:
  type: postgresql
  host: 10.130.0.8
  port: 5432
  secrets:
    user:
      name: artifactory-postgres
      key: user
    password:
      name: artifactory-postgres
      key: password
```

then i install it with this

`helm install --name artifactory --values artifactory-values.yaml jfrog/artifactory`

here's my rig

```
 ~/code/devops/okd_install/helm   master ●  helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Im running OKD 3.11.  Now, when artifactory load, in the artifactory log i get

```
2019-04-08 19:44:04,262 [art-init] [ERROR] (o.a.m.s.MetadataEventServiceImpl:188) - Unable to init the Metadata client. The Metadata Event pipeline will be disabled.
--
  | 2019-04-08 19:44:04,275 [art-init] [ERROR] (o.a.a.e             :55) - Unable to read license file
  | 2019-04-08 19:44:04,447 [art-init] [INFO ] (o.j.c.w.ConfigurationManagerImpl:445) - Replacing temporary DB channel with permanent DB channel
  | 2019-04-08 19:44:04,448 [art-init] [INFO ] (o.j.c.w.ConfigurationManagerImpl:445) - Successfully closed temporary DB channel
  | 2019-04-08 19:44:04,449 [art-init] [INFO ] (o.a.s.ArtifactoryApplicationContext:504) - Artifactory application context set to READY by refresh
  | 2019-04-08 19:44:04,556 [art-init] [INFO ] (o.a.s.a.AccessServiceImpl:1468) - Successful register of Artifactory serviceId jfrt@01d7z4zer4c6rw1q17d38m0vx0 in Access Federation
  | 2019-04-08 19:44:04,572 [art-init] [INFO ] (o.a.m.s.MetadataMigrationHelper:162) - Current operator cursor is at '0', and migration target is '4'. Starting / continuing migration.
  | 2019-04-08 19:44:04,578 [art-init] [INFO ] (o.a.e.w.NodeEventTaskManagerImpl:50) - Background migration started on behalf of Event Operator with ID 'metadata-operator'
  | 2019-04-08 19:44:04,584 [art-init] [INFO ] (o.a.w.s.ArtifactoryContextConfigListener:215) -
  | ###########################################################
  | ### Artifactory successfully started (57.945 seconds)   ###
  | ###########################################################
  |  
  | 2019-04-08 19:44:09,566 [art-exec-5] [ERROR] (o.a.a.e             :55) - Unable to read license file

```

when i terminal into the container i get

```
$ cd /opt/jfrog/artifactory/etc/
$ ls -alh
total 1.1M
drwxr-xr-x. 7 artifactory artifactory 4.0K Apr  8 19:42 .
drwxrwxrwx. 9 root        root        4.0K Apr  8 19:42 ..
-rw-r-----. 1 artifactory artifactory  33K Apr  8 18:57 artifactory.config.latest.1554749839000.xml
-rw-r-----. 1 artifactory artifactory  33K Apr  8 18:57 artifactory.config.latest.xml
drwxr-xr-t. 3 artifactory artifactory 4.0K Apr  8 18:56 artifactory.lic
-rw-r-----. 1 artifactory artifactory  864 Apr  8 19:44 artifactory.properties
-rw-r-----. 1 artifactory artifactory  13K Apr  8 18:56 artifactory.system.properties
-rw-r-----. 1 artifactory artifactory 1.2K Apr  8 18:56 binarystore.xml
-rw-r--r--. 1 artifactory artifactory  920 Apr  8 19:44 db.properties
drwxr-xr-x. 2 artifactory artifactory 4.0K Apr  8 18:56 info
-rw-r-----. 1 artifactory artifactory  16K Apr  8 18:56 logback.xml
-rw-r-----. 1 artifactory artifactory 5.7K Apr  8 18:56 mimetypes.xml
drwxr-xr-x. 2 artifactory artifactory 4.0K Apr  8 18:56 plugins
drwx------. 3 artifactory artifactory 4.0K Apr  8 19:44 security
drwxr-x---. 2 artifactory artifactory 4.0K Apr  8 18:56 ui
$ cd artifactory.lic
$ ls -alh
total 288K
drwxr-xr-t. 3 artifactory artifactory 4.0K Apr  8 18:56 .
drwxr-xr-x. 7 artifactory artifactory 4.0K Apr  8 19:42 ..
drwxr-xr-x. 2 artifactory artifactory 4.0K Apr  8 19:50 ..2019_04_08_18_56_01.254719901
lrwxrwxrwx. 1 artifactory artifactory   31 Apr  8 18:56 ..data -> ..2019_04_08_18_56_01.254719901
lrwxrwxrwx. 1 artifactory artifactory   34 Apr  8 18:56 artifactory.cluster.license -> ..data/artifactory.cluster.license
```

Why am i having so much trouble with this?  Is this helm simply not compatible with OKD/OpenShift?  Should I give up and just manually install it with docker directly or something?  This was supposed to be simple and yet, it almost seems like the thing is simply incapable of reading secret files.  I had to rebuild the postgres container because the thing refused to read the secrets saying use user `int-db-postgres-artifactory` rather than `artifactory`, and now it won't read the license file.  

Whats going on here?

**Comment by scphantm** [comment]
oh, and when i try to update the license file thru the UI, i get

`Unable to install license. java.io.IOException: File '/opt/jfrog/artifactory/etc/artifactory.lic' exists but is a directory`

**Comment by scphantm** [comment]
I calmed down and thought about it some more.  I think i see whats happening, i just don't understand why. 

```
artifactory:
  license:
    secret: artifactory-license
    dataKey: license-key
```

I think something is wrong with the chart and its not capable of reading the `dataKey` value within the secret.  I think its similar to what i encountered with postgres, where it was able to load the secret, but not pull the data.  

heres my secret

```
apiVersion: v1
data:
  license-key: >-
    {bla bla bla}
kind: Secret
metadata:
  creationTimestamp: '2019-04-08T19:04:11Z'
  name: artifactory-license
  namespace: artifactory
  resourceVersion: '1135586'
  selfLink: /api/v1/namespaces/artifactory/secrets/artifactory-license
  uid: 17dc9bbd-5a31-11e9-af31-0cc47a51e1de
type: Opaque
```

all of the secrets this chart is having a hard time reading are of type `Opaque`.  Should they be a different type?
