### ISSUE TITLE
drop /artifactory from url

### ISSUE THREAD

**Issue by thinkTank15** [jfrog/charts#306]
**Is this a request for help?**:
yes

**Version of Helm and Kubernetes**:
Server: &version.Version SemVer:"v2.13.0"

**Which chart**:
artifactory

I am using artifactory with nginx-ingress, the old system I have is configured as http://someurl/webapp

The new system that I am using comes up as https://someurl/artifactory/webapp, 
It would be good to maintain consistency among both. I did some research and found out that this points to the `public context path` in `reverse proxy settings`.

I tried multiple rewrite configurations as:

`    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;
      rewrite ^/$ /webapp/ redirect;
      rewrite ^/webapp$ /webapp/ redirect;`
and some other configurations as well but haven't been able to achieve desired result. Can somebody please point out what additional configurations do I need to amend in `values.yaml`?
Thanks.

**Comment by jainishshah17** [comment]
@thinkTank15 Can you provides us more details about Artifactory chart version and Artifactory appVersion that you have deployed. Also what ingress-controller are you using?

**Comment by thinkTank15** [comment]
@jainishshah17 

chart version is : `artifactory-7.12.11`
app version is : `6.8.7`

as for the ingress-controller I am using, ingress-nginx https://github.com/kubernetes/ingress-nginx

**Comment by jainishshah17** [comment]
@thinkTank15 Can you please share your ingress.yaml as well.

**Comment by thinkTank15** [comment]
@jainishshah17 

`# Source: artifactory/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-artifactory
  labels:
    app: artifactory
    chart: artifactory-7.12.11
    release: RELEASE-NAME
    heritage: Tiller
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/ingress.class: internal
    kubernetes.io/tls-acme: "true"
    namespace: artifactory
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;
        #      some rewrite stuff that I tried:
        #      rewrite ^/$ /webapp/ redirect;
        #      rewrite ^/webapp$ /webapp/ redirect;
        #      proxy_pass my.host/;
        #      rewrite ^/artifactory/?(.*) /$1;
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: "my.host"
    http:
      paths:
      - backend:
          serviceName: RELEASE-NAME-artifactory
          servicePort: 8081
        path: /
  tls:
    - hosts:
      - my.host
      secretName: some-secret
`

**Comment by jainishshah17** [comment]
Can you try this `rewrite ^/webapp$ artifactory/webapp/ redirect;`?

**Comment by thinkTank15** [comment]
@jainishshah17 

That did not work :/ ```myhost/webapp``` returns ```404```

Updated Ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-artifactory
  labels:
    app: artifactory
    chart: artifactory-7.12.11
    release: RELEASE-NAME
    heritage: Tiller
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/ingress.class: internal
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;
      rewrite ^/webapp$ artifactory/webapp/ redirect;
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  backend:
    serviceName: RELEASE-NAME-artifactory
    servicePort: 8081
  rules:
  - host: "myhost"
    http:
      paths:
      - backend:
          serviceName: RELEASE-NAME-artifactory
          servicePort: 8081
        path: /
  tls:
    - hosts:
      - myhost
      secretName: mysecret

**Comment by alex-mnt** [comment]
Hi,

Any updates on this topic?
It would be very nice to have this flexibility.

Kind regards,
Alexandru

**Comment by eldada** [comment]
Now that nginx config was moved to the `values.yaml`, it should be possible with some adjustments to the rewrite rules in `nginx.artifactoryConf`. I will try and provide a working example in the coming days. Can't commit to an ETA.

**Comment by danielezer** [comment]
@alex-mnt @thinkTank15 This is how I made it work:
1. Create a values file called art-values.yaml with the following content:
```
ingress:
  enabled: true

  defaultBackend:
    enabled: false

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

  additionalRules: |
    - host: artifactory-test.jfrogdev.org
      http:
        paths:
          - path: /webapp
            backend:
              serviceName: {{ template "artifactory.nginx.fullname" . }}
              servicePort: {{ .Values.nginx.externalPortHttp }}
          - path: /
            backend:
              serviceName: {{ template "artifactory.nginx.fullname" . }}
              servicePort: {{ .Values.nginx.externalPortHttp }}
```

2. Run the following command:
`helm upgrade --install artifactory stable/artifactory --values art-values.yaml`

Let me know if it worked out for you
