### ISSUE TITLE
binarystore.xml wrong volume mount in artifactory-ha

### ISSUE THREAD

**Issue by andrewhertog** [jfrog/charts#338]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:
"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Helm
```Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Which chart**:
artifactory-ha

**What happened**:
Set in values.yaml:
```yaml
artifactory: 
    persistence:
        type: aws-s3
        awsS3:
            endpoint: s3.amazonaws.com
            region: us-east-1
            roleName: jfrog-s3
            bucketName: myartifactorybucket
            path: ""
```
It didn't mount the change to the binarystore.xml as expected, but left the defaults as shard-fs

**What you expected to happen**:
update the binarystore.xml to the s3 configuration.

**How to reproduce it** (as minimally and precisely as possible):
Apply the helm chart with s3 the previously mentioned values.

**Anything else we need to know**:
I manually edited the stateful set `jfrog-artifactory-ha-primary` from
```
- mountPath: /artifactory_extra_conf/binarystore.xml
          name: binarystore-xml
          subPath: binarystore.xml
```
to 
```
- mountPath: /var/opt/jfrog/artifactory/etc/binarystore.xml
          name: binarystore-xml
          subPath: binarystore.xml
```
And it corrected the issue

Edit: I will provide a PR with my fix for review shortly

**Comment by eldada** [comment]
@andrewhertog - Was this done as an upgrade?
`binarystore.xml` is intentionally mounted to `/artifactory_extra_conf` and not directly to `/var/opt/jfrog/artifactory/etc/`. It's picked up by the entrypoint is copied to its final destination. Only on first deployment or if you set `artifactory.copyOnEveryStartup` with the proper configuration.
Does this help?

**Comment by danielezer** [comment]
@andrewhertog please take a look at this line: https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L104

If you add this to your values.yaml:
```
artifactory:
  copyOnEveryStartup:
    - source: /artifactory_extra_conf/binarystore.xml
      target: etc/
```

It will cause artifactory to copy the binarystore.xml file from /artifactory_extra_conf/ to ARTIFACTORY_HOME/etc on every startup, which will cause the binarystore configuration to be updated.
