### ISSUE TITLE
Fail when using existing claim for Artifactory

### ISSUE THREAD

**Issue by hoeghh** [jfrog/charts#34]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm v2.8.2 - Kubernetes v1.10.1

**Which chart**: 7.4.2

**What happened**: Failed when using existing volume claim

**What you expected to happen**: It worked and used an existing claim

**How to reproduce it** (as minimally and precisely as possible): set existingClaim to a value

**Anything else we need to know**:
The problem is in the /templates/artifactory-statefulset.yaml file. The accessModes and resources.requests.storage is not used when an existing claim is used, and kubernetes will fail the deployment. A volumeClaimTemplates needs these fields.

Instead the template part should look like this : 
```
  volumeClaimTemplates:
  - metadata:
      name: artifactory-volume
    spec:
    {{- if .Values.artifactory.persistence.existingClaim }}
      selector:
        matchLabels:
          app: {{ template "artifactory.name" . }}
    {{- else }}
      {{- if .Values.artifactory.persistence.storageClass }}
      {{- if (eq "-" .Values.artifactory.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.artifactory.persistence.storageClass }}"
      {{- end }}
      {{- end }}
    {{- end }}
      accessModes: [ "{{ .Values.artifactory.persistence.accessMode }}" ]
      resources:
        requests:
          storage: {{ .Values.artifactory.persistence.size }}
      {{- else }}
      - name: artifactory-volume
        emptyDir: {}
      {{- end }}
```

So that no matter if a claim is specified or not, accessMode and resource request storage is filled out.

Errors im getting before changing the template:
```
Statefulset failing:
  Warning  FailedCreate  2m (x12 over 2m)  statefulset-controller  create Pod artifactory-artifactory-0 in StatefulSet artifactory-artifactory failed error: Failed to create PVC artifactory-volume-artifactory-artifactory-0: PersistentVolumeClaim "artifactory-volume-artifactory-artifactory-0" is invalid: [spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Required value]
  Warning  FailedCreate  2m (x13 over 2m)  statefulset-controller  create Claim artifactory-volume-artifactory-artifactory-0 for Pod artifactory-artifactory-0 in StatefulSet artifactory-artifactory failed error: PersistentVolumeClaim "artifactory-volume-artifactory-artifactory-0" is invalid: [spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Required value]

  Warning  FailedCreate  1s (x11 over 7s)  statefulset-controller  create Claim artifactory-volume-artifactory-artifactory-0 for Pod artifactory-artifactory-0 in StatefulSet artifactory-artifactory failed error: PersistentVolumeClaim "artifactory-volume-artifactory-artifactory-0" is invalid: spec.resources[storage]: Required value
  Warning  FailedCreate  1s (x11 over 7s)  statefulset-controller  create Pod artifactory-artifactory-0 in StatefulSet artifactory-artifactory failed error: Failed to create PVC artifactory-volume-artifactory-artifactory-0: PersistentVolumeClaim "artifactory-volume-artifactory-artifactory-0" is invalid: spec.resources[storage]: Required value
```

**Comment by jainishshah17** [comment]
@hoeghh Did it work for you after making changes that you have suggested here?

**Comment by hoeghh** [comment]
@jainishshah17 Yes, then it works. Then you get 
```
      accessModes: [ "{{ .Values.artifactory.persistence.accessMode }}" ]
      resources:
        requests:
          storage: {{ .Values.artifactory.persistence.size }}
```
if persistence is enabled, whether existing claim is defined or not, as it should

**Comment by jainishshah17** [comment]
@hoeghh Sure will do. Can you provide more detail on what storage provider are you using? Do you have custom storageClass configured?

**Comment by jainishshah17** [comment]
@hoeghh Any update on this one?

**Comment by hoeghh** [comment]
Hi,

sorry for the delay.

So, with other charts when they have an "existingClaim", what is expected from the user, is to provide the name of an already existing volume claim. Like Jenkins here : 
```
persistentVolumeClaim:
          claimName: {{ .Values.Persistence.ExistingClaim | default (include "jenkins.fullname" .) }}
```
But this claim will take the value of existingClaim and use it to match a label with a key "app" as seen here : 
```
    {{- if .Values.artifactory.persistence.existingClaim }}
      selector:
        matchLabels:
          app: {{ template "artifactory.name" . }}
```

I think its fine that you as a user can define labels. But i would then wish it was done like here : 
```
  {{- if .Values.Persistence.VolumeClaimTemplates.Selector.Enabled }}
      selector:
        matchLabels:
          {{- range $key,$value := .Values.Persistence.VolumeClaimTemplates.Selector.MatchLabels }}
          {{ $key }} : {{ $value }}
          {{- end }}
  {{- end }}
```
So the user can give both the key and value, and as many as they need like here : 
```
     Selector:
       Enabled: true
       MatchLabels:
         app: artifactory
         system: production
         type: homefolder
```

But, for now, it would be great if the chart would work at all, when specifying an "existingClaim".

The problem is that when you specify an "existingClaim", it will not add accessModes or resources elements, and it will fail.

If you use the helm code in my first post, it will add these for both an existingclaim AND if you dont.

Hope it makes sense.

**Comment by mellena1** [comment]
@hoeghh I tried out your template change from your original comment, and while it no longer fails the deployment, it seems like the statefulset tries to make its own volume claim instead (ignoring my existing claim). Are you seeing that behavior?

**Comment by hoeghh** [comment]
@mellena1  I will look into it tomorrow at work.

**Comment by hoeghh** [comment]
Hi @mellena1 

Ok, so i have been playing with it. 

The way its implemented now, does not allow users to specify an existing claim. The volumeClaimTemplates will create new PVC's. 

What you get, is a PVC with a match on label "app: artifactory". It doesnt even use the existingClaim the user specifies. It uses the name of the helm app.

```
      selector:
        matchLabels:
          app: {{ template "artifactory.name" . }}
```

This could be changed to 
```
      selector:
        matchLabels:
          app: {{ .Values.artifactory.persistence.existingClaim }}
```
Then the use has to create a PV like this : 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-0
  labels:
    app: [existingClaim goes here]
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-server.example.com
    path: /home/nfsshare/artifactory
```

But the name of the helm attribute "existingClaim" is very misleading. 

If you change the volumeClaimTemplates to this : 
```
  volumeClaimTemplates:
  - metadata:
      name: artifactory-volume
    spec:
    {{- if .Values.artifactory.persistence.existingClaim }}
      selector:
        matchLabels:
          app: {{ .Values.artifactory.persistence.existingClaim }}
    {{- else }}
      {{- if .Values.artifactory.persistence.storageClass }}
      {{- if (eq "-" .Values.artifactory.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.artifactory.persistence.storageClass }}"
      {{- end }}
      {{- end }}
    {{- end }}
      accessModes: [ "{{ .Values.artifactory.persistence.accessMode }}" ]
      resources:
        requests:
          storage: {{ .Values.artifactory.persistence.size }}
      {{- else }}
      - name: artifactory-volume
        emptyDir: {}
      {{- end }}
```

People will be able to add a value to the selector that finds your PV's. It will generate a PVC that uses that value in its selector. It will not use an existing Volume Claim. 

If i were you, i would make the correction, and then create a new issue that describes how you would want it to really work. That way people can use the existingClaim (then i will work), and later hopefully actually choose an PVC. 

I will be glad to help with that part if needed.

**Comment by mellena1** [comment]
Thanks for the reply @hoeghh.

> What you get, is a PVC with a match on label "app: artifactory". It doesnt even use the existingClaim the user specifies. It uses the name of the helm app.
> 
> ```
>       selector:
>         matchLabels:
>           app: {{ template "artifactory.name" . }}
> ```
> This could be changed to
> 
> ```
>       selector:
>         matchLabels:
>           app: {{ .Values.artifactory.persistence.existingClaim }}
> ```

I did notice this as well, after I played with it and looked through the template. I did make a PVC with the label "app: artifactory", and despite that it still didn't use the existing one. I'm still curious if making a volumeClaimTemplate actually allows you to specify an old PVC using a selector or if it will allows create something. My workaround was similar to yours listed above, but I went at it from a slightly different angle. This is what I came up with:

In the volumes definition of spec, I added:
```yaml
volumes:
      {{- if .Values.artifactory.persistence.existingClaim }}
      - name: artifactory-volume
        persistentVolumeClaim:
          claimName: {{ .Values.artifactory.persistence.existingClaim }}
      {{- end }}
```

And then my volumeClaimTemplates looked like this:
```yaml
{{- if .Values.artifactory.persistence.existingClaim }} # Couldn't figure out how to do a !defined
{{- else }}  # just did an empty if and then put the important part in else instead
  {{- if .Values.artifactory.persistence.enabled }}
volumeClaimTemplates:
- metadata:
    name: artifactory-volume
  spec:
    {{- if .Values.artifactory.persistence.storageClass }}
    {{- if (eq "-" .Values.artifactory.persistence.storageClass) }}
    storageClassName: ""
    {{- else }}
    storageClassName: "{{ .Values.artifactory.persistence.storageClass }}"
    {{- end }}
    {{- end }}
    accessModes: [ "{{ .Values.artifactory.persistence.accessMode }}" ]
    resources:
      requests:
        storage: {{ .Values.artifactory.persistence.size }}
    {{- else }}
    - name: artifactory-volume
      emptyDir: {}
  {{- end }}
{{- end }}
```

So existingClaim gets passed in as the name of the claim like you said above, but it attaches it in the volume block instead of dealing with the volumeClaimTemplate. When existingClaim doesn't exist, it will make a new volume with the other values.

**Comment by hoeghh** [comment]
Hi @mellena1 

This will work. Though properly not on the HA chart as you need to scale the Volume. But its fine for this chart. If you do a ```helm package``` the chart and attach it, i can test it tomorrow if you want.

**Comment by mellena1** [comment]
Yeah I haven't looked at the HA chart at all so I wasn't taking that into account. Here is the chart if you want to test it out. (I just changed the extension from .tgz to .zip as github doesn't allow tgz as an extension)
[artifactory-7.5.4.zip](https://github.com/jfrog/charts/files/2468885/artifactory-7.5.4.zip)

**Comment by hoeghh** [comment]
@mellena1 Im looking into a solution that might work on both server and HA. brb

**Comment by hoeghh** [comment]
@mellena1 
I dont think the normal "Volume" section supports a selector. I cant find any examples at least. All are on VolumeClaimTemplate's. 

But, would it be better to use the VolumeClaimTemplate with labels. Where a user can define multible, and the PVC's that it generates will use from the pool of PV's that matches those labels. That way it still scales. 

The solution you found only supports one PVC. 

I can make an example if you want, where you can specify multible keys and values that will be used on the generated PVC. Then its not "existingClaim" but that you specify matchLabels to be used (along with storageClassName and resources).

**Comment by mellena1** [comment]
> @mellena1
> I dont think the normal "Volume" section supports a selector. I cant find any examples at least. All are on VolumeClaimTemplate's.
Yeah I couldn't find a way to do that either. I believe the only way you can do it right now is with the name of the PVC, rather than with labels.

> 
> But, would it be better to use the VolumeClaimTemplate with labels. Where a user can define multible, and the PVC's that it generates will use from the pool of PV's that matches those labels. That way it still scales.
> 
> The solution you found only supports one PVC.

Yeah my solution definitely doesn't work for every scenario. It was more of a hack to get it up and running. It would ideally be more scalable.

> 
> I can make an example if you want, where you can specify multible keys and values that will be used on the generated PVC. Then its not "existingClaim" but that you specify matchLabels to be used (along with storageClassName and resources).

If you can get it to work go for it! I personally only need the one PVC, but I'm sure others may need more, especially in the HA chart. I just couldn't find enough documentation on a lot of this stuff and hacked my method together.

**Comment by jainishshah17** [comment]
@hoeghh @mellena1 Can you try using this template to create PVs and PVCs https://www.jfrog.com/confluence/display/EP/Static+Volume+Provisioning+with+NFS

**Comment by hoeghh** [comment]
@jainishshah17 

Hi,

I haven't tried it, but i just had a quick look at it.

In the Helm install command you use ```--set postgresql.persistence.existingClaim=artifactory-database-pvc``` and have a PVC with the name ```artifactory-data-pvc```. They dont match.

But. The helm chart doesnt try to find a PVC by name, but with a label ```app: artifactory```. Thats hard coded into the chart.

That means, that no matter what i write in existingClaim, it will use that label selection.

I, as a user, have no control over which PVC it chooses if i have multible PVC' with that one label.

And, as i stated in my initial post, if you choose to use existingClaim, it forgets to add resources and storageclass. And then the deployment breaks.

So, the name existingClaim is misleading and it doesnt work yet. And there are better ways to do it, as i have pointed out. Like using labels defined by the user, and not call it existingClaim.

**Comment by jainishshah17** [comment]
@hoeghh Make sense. Will work on adding this changes.

**Comment by hoeghh** [comment]
I thinks something like this would work. I havent tried it (free hand).

```
  volumeClaimTemplates:
  - metadata:
      name: artifactory-volume
    spec:
      accessModes: [ {{ .Values.artifactory.persistence.accessMode | quote }} ]
      resources:
        requests:
          storage: {{ .Values.artifactory.persistence.Storage | quote }}
      storageClassName: {{ .Values.artifactory.persistence.storageClass | quote }}

  {{- if .Values.artifactory.persistence.selector.enabled }}
      selector:
        matchLabels:
          {{- range $key,$value := .Values.artifactory.persistence.selector.matchLabels }}
          {{ $key }} : {{ $value }}
          {{- end }}
  {{- else }}
      - name: artifactory-volume
        emptyDir:
          sizeLimit: {{ .Values.artifactory.persistence.size }}
  {{- end }}
```

And then in the values file have this:
```
     selector:
       enabled: false
       matchLabels:
         app: artifactory
         system: production
```

I dont remember if an emtyDir needs storageClass and resources.
