### ISSUE TITLE
Unable to update DB password after initial helm install

### ISSUE THREAD

**Issue by CarpathianUA** [jfrog/charts#351]
**Is this a BUG REPORT or FEATURE REQUEST?** : BUG

**Version of Helm and Kubernetes**: Helm v2.13.1, k8s v1.11.9

**Which chart**: artifactory-ha-0.13.3

**What happened**: DB password is not updateable after initial ```helm install``` using correct values:
```
...
database:
  type: "postgresql"
  host: <REDACTED>
  port: 5432
  ## If you would like this chart to create the secret containing the db
  ## password, use these values
  user: artifactory_dev
  password: <REDACTED>
...
```

**What you expected to happen**:
DB password is updateable without any issues using appropriate Helm value;

**How to reproduce it** (as minimally and precisely as possible):
1) Update DB password;
2) Scale both primary and member sts to 0.
3) Update Helm release with ```helm upgrade``` using values file with new DB password or set it via --set;
4) Scale both primary and member sts to the required number of replicas (>0);
5) Check db.properties file with new encrypted DB password - ```password``` is not changed.

**Anything else we need to know**:
My assumption here that artifactory-entrypoint.sh functions setDBConf() and setDBType() are not optimized for consequent updates of Helm release.
I've just tested this in our dev Artifactory release, but it will be a real pain when somebody needs to update DB password or properties in production.
