### ISSUE TITLE
ConfigMap too long

### ISSUE THREAD

**Issue by angegar** [jfrog/charts#372]
**Is this a request for help?**:

Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Not a bug but a limitation

**Which chart**:
jfrog/artifactory-ha

**What happened**:
I am trying to migrate a legacy artifactory ha instance to our kubernetes cluster thus i get the security.xml and config.xml files from the legacy instance. But during the k8s instance deployment i receive the following message :

```
ConfigMap "artifactory-config" is invalid: []: Too long: must have at most 1048576 characters
```

Someone probably already encounter this issue, how did you sort it out ?

**What you expected to happen**:

Configuration loaded

**Comment by danielezer** [comment]
Hi @angegar, this means that your configmap is bigger than 1MB, which is very big. I can suggest that you separate the two files into two different configmaps, which will each be (hopefully) under 1MB. You can then use the customVolumes and customVolumeMounts feature to mount in to /artifactory_extra_conf/.

An example values.yaml would look like this:
```
artifactory:
  customVolumes: |
     - name: artifactory-security-xml
        configMap:
          name: <SECURITY_XML_CONFIGMAP_NAME>
     - name: artifactory-config-xml
        configMap:
          name: <CONFIG_XML_CONFIGMAP_NAME>

  customVolumeMounts: |
     - name: artifactory-security-xml
        mountPath: "artifactory_extra_conf/security/"

     - name: artifactory-config-xml
        mountPath: "artifactory_extra_conf/config/"

  copyOnEveryStartup:
    - source: /artifactory_extra_conf/config/artifactory.config.xml
       target: etc/
    - source: /artifactory_extra_conf/config/security.import.xml
       target: etc/

```

**Comment by angegar** [comment]
Hi @danielezer ,

Thank you for your answer, i just tried this approach but it appears our security file is too big 😒. Any other idea which may help ?

**Comment by danielezer** [comment]
@angegar you can store your security file somewhere that's available over http, and add a postStart command for downloading it. This will combine the two methods.

The values file would look something like this:
```
artifactory:
  preStartCommand: "wget -O /artifactory_extra_conf/security/security.import.xml <URL_TO_GET_FILE_FROM>"

  customVolumes: |
    - name: artifactory-config-xml
      configMap:
        name: <CONFIG_XML_CONFIGMAP_NAME>

  customVolumeMounts: |
    - name: artifactory-config-xml
      mountPath: "/artifactory_extra_conf/config/"

  copyOnEveryStartup:
    - source: /artifactory_extra_conf/config/artifactory.config.xml
      target: etc/
    - source: /artifactory_extra_conf/security/security.import.xml
      target: etc/

```
