### ISSUE TITLE
Issue with Nginx reverse proxy

### ISSUE THREAD

**Issue by andrewhertog** [jfrog/charts#396]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm Version:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
jfrog/artifactory-ha-0.14.4
Artifactory 6.10.4

**What happened**:
docker login was giving 404 errors:
```
docker login repo.hostname.org
Error response from daemon: login attempt to https://repo.hostname.com/v2/ failed with status: 404 Not Found
```
The nginx error logs show that it was trying to direct the request to a https://repo.hostname.orgv2/index.html so to me it showed that the nginx conf wasn't catching this entry

**What you expected to happen**:
Expected to login successfully

**How to reproduce it** (as minimally and precisely as possible):
Values.yaml:
```yaml
artifactory:
  accessAdmin:
    password: password
  copyOnEveryStartup:
  - source: /artifactory_extra_conf/binarystore.xml
    target: etc/
  license:
    dataKey: license.lic
    secret: artifactory-cluster-license
  masterKeySecretName: jfrog-master-key
  node:
    javaOpts:
      jmx:
        enabled: false
      xms: 1g
      xmx: 4g
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
  persistence:
    awsS3:
      bucketName: s3-bucket-name
      endpoint: s3.amazonaws.com
      region: region
      roleName: iam-role-name
    type: aws-s3
  primary:
    javaOpts:
      jmx:
        enabled: false
      xms: 1g
      xmx: 4g
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
nginx:
  externalPortHttps: 443
  internalPortHttps: 443
  resources:
    limits:
      cpu: 250m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:region:account-number:certificate/uuid
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  tlsSecretName: artifactory-tls
postgresql:
  postgresPassword: password
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi
```

**Anything else we need to know**:
This was broken already on my install before I upgraded the chart from 0.14.0 to 0.14.4.
I was able to fix it by editing the config map nginx-artifactory-conf and adding my hostnames to server name in the nginx chart so the server name line looks like:
`server_name ~(?<repo>.+)\.jfrog-artifactory-ha jfrog-artifactory-ha ~(?<repo>.+)\.hostname.org hostname.org;`

Edit: added more details
