### ISSUE TITLE
[all charts] Upgrade PostgreSQL chart to a StatefulSet

### ISSUE THREAD

**Issue by eldada** [jfrog/charts#412]
For better stability and the option to enjoy newer features, the Artifactory and Artifactory HA PostgreSQL sub charts should be upgraded to a newer version that
- Deploys PostgreSQL as a StatefulSet
- Allows setup of replication (master and slave)
- Provide more flexibility around configuration setup
- Will support easy upgrade to newer versions of PostgreSQL
- A non-root pod for the DB

Currently Artifactory and Artifactory HA charts use a very old PostgreSQL chart version (0.9.5).

**NOTE:** Due to the nature of the big upgrade, we'll have to provide migration instructions.
For example (requiring downtime):
1. Stop Artifactory (scale to 0)
2. Stop PostgreSQL (scale to 0)
3. Prepare a new PV and PVC (for the new PostgreSQL)
4. Spin up a special migration pod that mounts old PG PVC and new PV and performs migration of the DB
5. Deploy an upgrade of the Artifactory chart that will include the new PostgreSQL chart with passing the new PVC as `existingVolumeClaim`
6. See Artifactory come up and use new DB with migrated data

Another good migration is simple a system export and import.

The [stable PostgreSQL chart](https://hub.helm.sh/charts/stable/postgresql) (by Bitnami)

**Comment by loreny-jfrog** [comment]
Once we migrate to the newer Bitnami chart, we should also move off using the 'root' user when the pod is deployed. This appears to be done by default when utilising the bitnami postgres chart.

**Comment by lwj5** [comment]
What is the timeline of this

**Comment by eldada** [comment]
Don't have an ETA on this, but I can share we are working on this internally (it has other implications).
For now, you can deploy PostgreSQL separately with their [official chart](https://hub.helm.sh/charts/stable/postgresql) and configure Artifactory to use it with the following values block:
```
# Do not use internal postgresql
postgresql:
  enabled: false

## If NOT using the PostgreSQL in this chart (postgresql.enabled=false),
## specify custom database details here or leave empty and Artifactory will use embedded derby
database:
  type:
  host:
  port:
  ## If you set the url, leave host and port empty
  url:
  ## If you would like this chart to create the secret containing the db
  ## password, use these values
  user:
  password:
  ## If you have existing Kubernetes secrets containing db credentials, use
  ## these values
  secrets: {}
  #  user:
  #    name: "rds-artifactory"
  #    key: "db-user"
  #  password:
  #    name: "rds-artifactory"
  #    key: "db-password"
  #  url:
  #    name: "rds-artifactory"
  #    key: "db-url"


```
