### ISSUE TITLE
Howto setup Google-Storage for Artifactory-HA

### ISSUE THREAD

**Issue by johnwalker247** [jfrog/charts#431]
**Is this a request for help?**:
YES
---

**Version of Helm and Kubernetes**:
helm 2.14.2 kubernetes v1.12.8-gke.10

**Which chart**:
CHART                           APP VERSION 
 artifactory-ha-0.15.6     6.11.3 

**What happened**:
Trying to configure google-storage, we have specified <identify> as the service account name (as created in Google Cloud Console.
Cant work out what the <credentials> value should be set to (GCP_KEY is not obvious to us)

What should we be using in values.yaml to use google-storage (persistent data)

Here is a section of values.yaml (the string used for credential is a copy'n'paste from something found elsewhere......

```yaml
 googleStorage:
      endpoint: storage.googleapis.com
      httpsOnly: true
      # Set a unique bucket name
      bucketName: "foo-artifactory-store"
      identity: "foo-admin@foo-artifactory.iam.gserviceaccount.com"
      credential: "{ type: service_account }"
      path: "artifactory-ha/filestore"
      bucketExists: true
````
