### ISSUE TITLE
additional rules not working for artifactory-ha ingress configuration (adding xray)

### ISSUE THREAD

**Issue by johnwalker247** [jfrog/charts#433]
**Is this a request for help?**:
yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm 2.14.2 kubernetes v1.12.8-gke.10

Which chart:
CHART APP VERSION
artifactory-ha-0.15.6 6.11.3

**What happened**:
we modified the values.yaml to add the xray service as a path in the artifactory ingress, i.e.
mycompany.com/artifactory   goes to artifactory
mycompany.com/xray  goes to xray

```yaml
 # Additional ingress rules
  additionalRules:
  - host: packages.mycompany.com
    http:
      paths:
      - backend:
          serviceName: xray-ha-xray-server
          servicePort: 80
        path: /xray
```

**What you expected to happen**:

this was fixed in #370   but for us it creates the following yaml
```yaml
spec:
  rules:
  - host: packages.mycompany.com
    http:
      paths:
      - backend:
          serviceName: artifactory-ha
          servicePort: 8081
        path: /
  - host: packages.mycompany.com
    http:
      paths:
      - backend:
          serviceName: xray-ha-xray-server
          servicePort: 80
        path: /xray

```

examples elsewhere suggest there should be multiple paths entries under a single host rather than multiple identical hosts. We have verified the xray service is working correctly by going in on a separate ingress. But when we go to mycompany.com/xray we get 404.
