### ISSUE TITLE
db.properties': Not a directory

### ISSUE THREAD

**Issue by jmcfallargo** [jfrog/charts#440]
**Is this a request for help?**:

No sure

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
2.14.2/GKE 1.13-7

**Which chart**:
HA

**What happened**:
I was running for several days but noticed some performance issues.  The install was purged and memory/cpu settings were modified.   Upon install the chart again, the HA pod would no longer launch with the following error:
```
{
 insertId:  "p95d3tg6agj33h"  
 labels: {…}  
 logName:  "projects/xxx/logs/delete-db-properties"  
 receiveTimestamp:  "2019-08-07T07:27:38.710766839Z"  
 resource: {
  labels: {
   cluster_name:  "artifactory-ha-cluster"    
   container_name:  "delete-db-properties"    
   instance_id:  "xxx"    
   namespace_id:  "default"    
   pod_id:  "artifactory-ha-artifactory-ha-primary-0"    
   project_id:  xxx   
   zone: xxx
  }
  type:  "container"   
 }
 severity:  "ERROR"  
 textPayload:  "rm: can't stat '/var/opt/jfrog/artifactory/etc/db.properties': Not a directory
"  
 timestamp:  "2019-08-07T07:27:10.396525303Z"  
}
```
**What you expected to happen**:
I expected to be able to install from the chart again - I removed all configuration, reverted the changes that I made, and even tried removing all of the nodes and volumes.
The only thing that I didn't do was to remove my DB ( using remote ) and Binary storage. 

**How to reproduce it** (as minimally and precisely as possible):
I am not sure what steps led to this.

**Anything else we need to know**:
I have most values set directly from helm using set, but do have some custom overrides the yml
```
artifactory:
  customVolumes: |
     - name: access-key
       configMap:
         name: access-config-map

  customVolumeMounts: |
    - name: access-key
      mountPath: "/access/etc/keys/root.crt"
      subPath: root.crt

  copyOnEveryStartup:
     - source: /access/etc/keys/root.crt
       target: access/etc/keys/trusted
     - source: /artifactory_extra_conf/artifactory.cluster.license
       target: etc
```
