### ISSUE TITLE
[artifactory]: Host in database url is ignored

### ISSUE THREAD

**Issue by ybonjour** [jfrog/charts#441]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**Version of Helm and Kubernetes**:
```
$helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.7", GitCommit:"b6001a5d99c235723fc19342d347eee4394f2005", GitTreeState:"clean", BuildDate:"2019-06-24T19:27:39Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
stable/artifactory (artifactory-7.16.9)

**What happened**:
I want to use an external Postgres database.
When I provide the database information using an url, artifactory seems to ignore the host part in the url. And the connection to the database fails. This is the configuration I tested with:

```
artifactory:
  image:
    repository: docker.bintray.io/jfrog/artifactory-oss
postgresql:
  enabled: false
database:
  type: postgresql
  url: "jdbc:sqlserver://10.10.10.10:5432;databaseName=artifactory;sendStringParametersAsUnicode=false;applicationName=Artifactory Binary Repository"
  user: artifactory
  password: ****
```

The logs show, that DB_HOST is set to `postgresql` and that the URL it is trying to connecto to contains `postgresql` as the host instead of the host set in the url. 
```
2019-08-10 09:16:28  [404 entrypoint-artifactory.sh] DB_TYPE is set to postgresql
2019-08-10 09:16:28  [327 entrypoint-artifactory.sh] DB_HOST is set to postgresql
2019-08-10 09:16:28  [329 entrypoint-artifactory.sh] Checking if need to copy postgresql configuration
2019-08-10 09:16:28  [332 entrypoint-artifactory.sh] /var/opt/jfrog/artifactory/etc/db.properties already exists. Making sure it's set to postgresql...
2019-08-10 09:16:28  [335 entrypoint-artifactory.sh] /var/opt/jfrog/artifactory/etc/db.properties already set to postgresql
2019-08-10 09:16:28  [260 entrypoint-artifactory.sh] Waiting for DB postgresql to be ready on url=jdbc/sqlserver///postgresql/5432;databaseName=artifactory;sendStringParametersAsUnicode=false;applicationName=Artifactory Binary Repository within 30 seconds
```
I also observed the same when I additioanlly set the host variable in the configuration.

When I provide the database information with host and port settings, it works fine:
```
artifactory:
  image:
    repository: docker.bintray.io/jfrog/artifactory-oss
postgresql:
  enabled: false
database:
  type: postgresql
  host: 10.10.10.10
  port: 5432
  user: artifactory
  password: ****
```
and the log messages show
```
2019-08-09 15:51:06  [356 entrypoint-artifactory.sh] Setting DB_USER to artifactory
2019-08-09 15:51:06  [360 entrypoint-artifactory.sh] Setting DB_PASSWORD to **********
2019-08-09 15:51:06  [364 entrypoint-artifactory.sh] Setting DB_PORT to 5432
2019-08-09 15:51:06  [379 entrypoint-artifactory.sh] Setting DB_HOST to 10.10.10.10
```

I executed the two tests on a completely "empty" GKE cluster (I set up a new cluster for each test). There were no other charts installed.

**What you expected to happen**:
I would expect that I can connect to the database with a url.

**Comment by danielezer** [comment]
@ybonjour It seems like you have an error with your URL. it says:
`jdbc://sqlserver://` which means this is the url for an sql server and not for postgresql. You can find a reference to the format of the postgresql connection string here: https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by ybonjour** [comment]
@danielezer thanks for your answer.
A silly mistake from my side. I copied the URL from the external Postgres example in stable/artifactory/README.md. MIght be worth fixing the URL in the README.

However even if I use the URL formats
`jdbc:postgresql://10.10.10.10:5432`, `jdbc:postgresql://10.10.10.10:5432/artifactory` or `jdbc:postgresql://10.10.10.10:5432;databaseName=artifactory;sendStringParametersAsUnicode=false;applicationName=Artifactory Binary Repository`
as described in (https://jdbc.postgresql.org/documentation/head/connect.html), I observe the same behavior where the host is set to postgresql and the connection can not be established.

**Comment by danielezer** [comment]
Hey @ybonjour, the `databaseName` format is used for sqlserver. Can you please try with the following format: `jdbc:postgresql://10.10.10.10:5432/artifactory` and send the error message you see?

**Comment by danielezer** [comment]
Also, good point on the example, I'll fix that

**Comment by danielezer** [comment]
@ybonjour using the database URL does work for me with the following values:
```yaml
database:
  type: postgresql
  url: "jdbc:postgresql://postgres123-postgresql:5432/artifactory"
  user: artifactory
  password: password

postgresql:
  enabled: false

```

I had a database host running with the name `postgres123-postgresql` and I created a DB by the name `artifactory`. 
Please let me know if it still doesn't work for you

**Comment by ybonjour** [comment]
@danielezer: I tried all the 3 formats I have mentioned above, including:
*  `jdbc:postgresql://10.10.10.10:5432` -> Which I would expect to default to the artifactory database
* `jdbc:postgresql://10.10.10.10:5432/artifactory`.
Both variants showed the following in the log before timing out:
```
2019-08-10 09:16:28  [260 entrypoint-artifactory.sh] Waiting for DB postgresql to be ready on url=jdbc/sqlserver///postgresql/5432/artifactory within 30 seconds
```
I also have a  `artifactory` and an `artifactory` user with corresponding rights for the database. The database host is reachable from the cluster (otherwise it would not work when I provide the information with `host` and `port` in the config).

The only difference (apart possibly from different versions) I see between your config and my config is, that you used a the hostname and I used the IP. Unfortunately, I can not easily switch to a hostname. Could you test with the IP instead of the hostname?

**Comment by danielezer** [comment]
@ybonjour thanks for the feedback. I'm pretty sure I see your issue. Can you please share which version of the chart you are using? Also, please share your values file. You probably have the parameter `deleteDBPropertiesOnStartup` set to `false`. This will cause that even though you change your DB configuration, it is not picked up by Artifactory. 
If you use an older version of the chart, please run `helm repo update` and try to reinstall.
If you use a recent version of chart (more recent than `7.14.4` to be exact), please change the value of the `deleteDBPropertiesOnStartup` to `true`, which is also the default.

**Comment by ybonjour** [comment]
@danielezer thanks for looking into it.

I am on verrsion `7.16.9`. My full values file is:
```
artifactory:
  image:
    repository: docker.bintray.io/jfrog/artifactory-oss
nginx:
  enabled: false
postgresql:
  enabled: false
database:
  type: postgresql
  url: "jdbc:postgresql://10.10.10.10:5432/artifactory"
  user: postgres
  password: ****
```
So `deleteDbPropertiesOnStartup` should be `true` by default.  However I will try to set it to `true` explicitly and let you know what happens.
