### ISSUE TITLE
Configuration possibility of various config files

### ISSUE THREAD

**Issue by AlexanderDenk-EE** [jfrog/charts#468]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): maybe FEATURE REQUEST

Artifactory supports making changes to the configuration by adding or modification of different files, e.g.

```
access/etc/keys/trusted/*
etc/artifactory.system.properties
etc/logback.xml
```

We are currently using the Helm charts and are pretty happy with them, but it seems to be a bit hart to modify one of the files above in a "consistent way". What is currently the preferred option to add keys in the folder above or to replace one of the two other files?
For the last two files the bootstrapping screte should be an option?

Currently there seems to be no consistent way to 

**Version of Helm and Kubernetes**: n/a

**Which chart**: latest

**What happened**: see description

**What you expected to happen**: solution or chart extension

**How to reproduce it** (as minimally and precisely as possible): see description

**Anything else we need to know**: n/a

**Comment by danielezer** [comment]
@AlexanderDenk-EE have you considered using the `customVolumes` and `customVolumeMounts` feature? You can create a configmap/secret with the `customVolumes` and use the `customVolumeMounts` to mount it to the location you want the files to be present in. 
In order to achieve that, do the following:
1. Create a configmap containing the content of the logback.xml file
2. Creates a values.yaml file with the following content:
```
artifactory:
  customVolumes: |
    - name: logbackXml
      configMap:
        name: logback-xml

  customVolumeMounts: |
    - name: logback-xml
      mountPath: "/tmp/logback"

    copyOnEveryStartup:
   # absolute path
    - source: /tmp/logback/logback.xml
   # relative to ARTIFACTORY_HOME/
      target: etc/
```
3. install the helm chart:
```
helm upgrade --install artifactory jfrog/artifactory
```
