### ISSUE TITLE
6.13.1 support 

### ISSUE THREAD

**Issue by lexual** [jfrog/charts#496]
6.13.0 is only available from helm chart for artifactory-ha despite 6.13.1 being released a few days ago.

**Comment by eldada** [comment]
Yes. This is correct. We will submit a pull request for this shortly.
In general, it's a good idea to manage the Artifactory version in your custom config `values.yaml`. It's supported in the `artifactory.image.version` key:
```
artifactory:
  name: artifactory
  image:
    repository: "docker.bintray.io/jfrog/artifactory-pro"
    version: 6.13.1

```

This way, you are not dependant on the chart release cycle.
