### ISSUE TITLE
[artifactory-ha] db.properties file error

### ISSUE THREAD

**Issue by andrewhertog** [jfrog/charts#500]
**Is this a request for help?**:
Help!
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
```
k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-825e5d", GitCommit:"825e5de08cb05714f9b224cd6c47d9514df1d1a7", GitTreeState:"clean", BuildDate:"2019-08-18T03:58:32Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
artifactory-ha-0.17.1

**What happened**:
Performed an upgrade from `artifactory-ha-0.15.6` to `artifactory-ha-0.17.1` via helm upgrade. 
1. `helm get values jfrog > jfrog.yaml`
2. `helm upgrade jfrog jfrog/artifactory-ha -f jfrog.yaml`
After the upgrade was performed `jfrog-artifactory-ha-primary-0` began crashing with the following error:
```
2019-10-15 15:29:26  [665 entrypoint-artifactory.sh] Checking DB_TYPE
2019-10-15 15:29:26  [674 entrypoint-artifactory.sh] DB_TYPE is set to postgresql
2019-10-15 15:29:26  [590 entrypoint-artifactory.sh] DB_HOST is set to jfrog-postgresql
2019-10-15 15:29:26  [592 entrypoint-artifactory.sh] Checking if need to copy postgresql configuration
2019-10-15 15:29:26  [595 entrypoint-artifactory.sh] /var/opt/jfrog/artifactory/etc/db.properties already exists. Making sure it's set to postgresql...
2019-10-15 15:29:26   [49 entrypoint-artifactory.sh] ERROR: /var/opt/jfrog/artifactory/etc/db.properties already exists and is set to a DB different than postgresql
``` 

**What you expected to happen**:
Helm to complete the upgrade completely, bringing the primary and members completely

**How to reproduce it** (as minimally and precisely as possible):
This occured when upgrading from `artifactory-ha-0.15.6` to `artifactory-ha-0.17.1`

**Anything else we need to know**:
No changes were made to my values.yaml in the upgrade. the values file is as follows:

```yaml
artifactory:
  accessAdmin:
    password: passwords
  copyOnEveryStartup:
  - source: /artifactory_extra_conf/binarystore.xml
    target: etc/
  license:
    dataKey: license.lic
    secret: artifactory-cluster-license
  masterKeySecretName: jfrog-master-key
  node:
    javaOpts:
      jmx:
        enabled: false
      xms: 1g
      xmx: 4g
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
  persistence:
#    customBinaryStoreXmlSecret: custom-binarystore
    awsS3:
      bucketName: s3-bucket-name
      endpoint: s3.amazonaws.com
      region: us-east-1
      roleName: iam-role-name
    type: aws-s3
  primary:
    javaOpts:
      jmx:
        enabled: false
      xms: 1g
      xmx: 4g
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
nginx:
  customArtifactoryConfigMap: art-nginx-conf
  externalPortHttps: 443
  internalPortHttps: 443
  resources:
    limits:
      cpu: 250m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: some:valid:arn:removed:for:security
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  tlsSecretName: artifactory-tls
postgresql:
  postgresPassword: password
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi
```
