### ISSUE TITLE
Support Kubernetes 1.16.0 is broken due to old PostgreSQL sub-chart

### ISSUE THREAD

**Issue by eldada** [jfrog/charts#509]
**BUG**
Due to the use of old PostgreSQL sub chart (version 0.9.5), deploying on k8s 1.16.0 does not work with default values.

**Which chart**:
- artifactory
- artifactory-ha
- distribution
- mission-control
- xray

**What happened**:
With k8s 1.16.0, support for Deployment version `extensions/v1beta1` is dropped. This breaks the ability to easily install our charts with the default `helm install <chart>`.
Getting the following error:
```
$ helm install jfrog/artifactory
Error: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**What you expected to happen**:
Default install works without any errors.

**How to reproduce it** (as minimally and precisely as possible):
Try installing artifactory chart on k8s 1.16.0 cluster.

**Anything else we need to know**:
Related to issue https://github.com/jfrog/charts/issues/286

**Comment by eldada** [comment]
A workaround for this is to

1. Pre install the PostgreSQL chart from a later version or use an external PostgreSQL DB
2. Prepare chart database config to point to external PostgreSQL instance (in or out of K8s)
```
# Example custom DB config for Artifactory (custom-db.yaml)

# Disable bundled PostgreSQL
postgresql:
  enabled: false

# Set custom PostgreSQL DB connection details
database:
  type: postgresql
  host: postgresql-host
  port: 5432
  user: artifactory
  password: aG00dPa$$worD
```
3. Deploy chart with PostgreSQL disabled (`--set postgresql.enabled=false`) and pass external DB parameters (as file with `-f custom-db.yaml` or command line parameters with `--set database....`)
```
# Example
$ helm install --name artifactory -f custom-db.yaml
```
