### ISSUE TITLE
Artifactory in-accessible when spun up using AWS ELB Load Balancer

### ISSUE THREAD

**Issue by tduffield** [jfrog/charts#526]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

Kubernetes EKS 1.14
```

**Which chart**: `artifactory-ha`

**What happened**: 
When using an AWS Load Balancer, classic or network, nginx starts but fails to serve content. 

**What you expected to happen**:
By specifying [the supported annotations](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancers), I can use an Amazon Load Balancer to front my nginx deployment and serve content via HTTP and/or HTTPS

**How to reproduce it** (as minimally and precisely as possible):
Stand up an Artifactory deployment with the following nginx service annotations:

```
nginx:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxxx:xxxxxxx/xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx # replace this
```

**Anything else we need to know**:

* If you create the service using the `http` backend protocol, you'll be unable to access Artifactory via HTTPS because you'll be attempting to hit port 443 using the TCP protocol. 
* If you create the service using the `https` backend protocol, all of the instances will be marked as OutOfService because the health check will attempt to connect to port 80 (the port automatically selected for the health check) using the TLS protocol. 
* It would be great if we could select whether or not we want to serve up port 443.
