### ISSUE TITLE
Missing changes with the new PostgreSQL chart version

### ISSUE THREAD

**Issue by sebastien-prudhomme** [jfrog/charts#529]
**Version of Helm and Kubernetes**:

**Which chart**:

Artifactory 8.1.4 (and certainly the HA version)

**What happened**:

postgresqlConfiguration format has change in the new chart.

It uses now local camel case convention in YAML (and transform it to snake case in this https://github.com/helm/charts/blob/master/stable/postgresql/templates/configmap.yaml) :

```yaml
postgresql:
 
  postgresqlConfiguration:
    listenAddresses: "'*'"
    maxConnections: "1500"

```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
