### ISSUE TITLE
Can't set DEBUG level logging via helm chart for Xray

### ISSUE THREAD

**Issue by lexual** [jfrog/charts#569]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: n/a

**Which chart**: 1.2.9

**What happened**: logging level is hard-coded to INFO level.

**What you expected to happen**:

According to below link, logging can be set to DEBUG or other levels, but currently this isn't exposed via the helm chart.

https://www.jfrog.com/confluence/display/XRAY/Troubleshooting#Troubleshooting-Xrayisnotprovidingenoughinformationinitslogfiles

Would expect can set logging-level via helm chart if we want value other than INFO.

**How to reproduce it** (as minimally and precisely as possible):
install helm chart for xray

**Anything else we need to know**:
no

**Comment by danielezer** [comment]
Hey @lexual, thanks for reporting, this is a valid feature request. 
Currently, there's no "native" support for doing something like `--set xray.logging.level=DEBUG`, however, in the next Xray major version, which is due to be released in the next few weeks, it would be supported.
In the mean time, you can use `customVolumes` and `customVolumeMounts` in order to achieve the same result. Here's an example:

First, create a config map with the content of Xray's log configuration file (`analysis_log4go_config.xml`)

Then, create a values.yaml file with the following content:
```
indexer:
  ## Create a volume pointing to the config map with your configuration file
  customVolumes: |
    - name: log-xml-configmap
      configMap:
        name: log-xml-configmap
  customVolumeMounts: |
    - name: log-xml-configmap
      mountPath: {{ xrayConfigPath }}
```

Finally, upgrade your release:
```
helm upgrade --install xray jfrog/xray --values values.yaml
```
