### ISSUE TITLE
About ingress TLS

### ISSUE THREAD

**Issue by yiwu1** [jfrog/charts#599]
Ingress can't be deployed successfully here with TLS cert with following spec:

ingress:

  defaultBackend:
    enabled: false
  enabled: true
  hosts:
  - artifactory-stg.test.com
  tls:
  - secretName: artifactory-tls

Reading this https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#ingress-and-tls and Wondering is that following annotations the must annotation to add?

annotations:
      kubernetes.io/tls-acme: "true"

**Comment by danielezer** [comment]
Hey @yiwu1,
you need to add something like the following:
```
ingress:
  enabled: true
  hosts:
    - artifactory-stg.test.com
  tls:
    - secretName: artifactory-tls
      hosts:
        - artifactory-stg.test.com
  defaultBackend:
    enabled: false
```

You were missing the `tls.hosts` part, which tells ingress which hostnames should use SSL
