### ISSUE TITLE
Feature: customizable mountOptions for nfs-pv

### ISSUE THREAD

**Issue by andyzhang495** [jfrog/charts#609]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:

`helm v2.14.1`

`kubernetes 1.12.6`

**Which chart**:

`artifactory-ha`

**Anything else we need to know**:

Some NFS providers need the client to add specific `mountOptions`, like these:

```yaml
  spec:
    mountOptions:
      - vers=4.0
      - noresvport
```

We'll need an entry in the templates to allow users add their `mountOptions` in the `values.yaml` file.
