### ISSUE TITLE
Artifactory S3 backend is not working

### ISSUE THREAD

**Issue by ghost** [jfrog/charts#625]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:
Helm: 3.0
Kubernetes: 1.4

**Which chart**: Artifactory HA

**What happened**: I have updated values.yml with S3 configuration but when I am trying to install this chart with the values.yml file, the S3 back is throwing error. I tried IAM and access/secret key but none of them are working.

2020-01-22 00:32:22,690 [art-init] [ERROR] (o.a.a.f.t.j.s.S3JetS3tBinaryProvider:369) - Failed to put blob '80796860e7602658812571105bfcd24857fb463e' to s3 caused by 403:The request signature we calculated does not match the signature you provided. Check your key and signing method.

**What you expected to happen**: It should take S3 parameter from values.yml and use S3 as backend.

**How to reproduce it** (as minimally and precisely as possible):
helm install --generate-name -f templates/artifactory-ha-values.yaml jfrog/artifactory-ha

**Comment by danielezer** [comment]
@rapandya Can you share your values.yaml file?

**Comment by danielezer** [comment]
From a quick google search, this looks like an issue with your AWS access key - https://stackoverflow.com/questions/30518899/aws-s3-how-to-fix-the-request-signature-we-calculated-does-not-match-the-sign

**Comment by res0nat0r** [comment]
- So I had this exact problem and that error also. I was getting that same error and I 100% knew my key was correct because I was verifying it would read/write to the bucket via the awscli tool.

I did have my `path:` set to `/` originally, and this didn't work and was apparently causing the issue. I don't know if you have it set like this, or possibly the path being blank, but trying to set something like `path: project-name-here` and see if it works for you.

```yaml
    awsS3:
      # Set a unique bucket name
      bucketName: "bucket-name-here"
      endpoint: "s3.us-east-1.amazonaws.com"
      region: "us-east-1"
      identity: "XXX"
      credential: "YYY"
      path: "this-must-be-set"
      refreshCredentials: false
      testConnection: true
      s3AwsVersion: "AWS4-HMAC-SHA256"
```
