### ISSUE TITLE
Mission Control service not added on Ingress template

### ISSUE THREAD

**Issue by erick-duran** [jfrog/charts#643]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes: 1.14
Helm: 3.0.3

**Which chart**:
Mission Control

**What happened**:
Deployed MC using Ingress with the default `small` values. Accessing via the Ingress URL returned a blank page, server response was 404.

**What you expected to happen**:
MC to work with Ingress.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy MC enabling Ingress
2. Try to access the service via the Ingress URL

**Anything else we need to know**:
The way I fixed this was adding the service manually to the `ingress` object after deploying. Here's the config:
```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: mission-control
  namespace: test
...
spec:
  backend:
    serviceName: mission-control
    servicePort: 80
  rules:
...
```
So I guess this might be fixed by adding the `serviceName: {{ $serviceName }}` and `servicePort: {{ $servicePort }}` to `spec.backend` [here](https://github.com/jfrog/charts/blob/master/stable/mission-control/templates/ingress.yaml#L21) similar to [other services](https://github.com/jfrog/charts/blob/master/stable/distribution/templates/ingress.yaml#L23-L26).

**Comment by danielezer** [comment]
@erick-duran You have to use `ingress.hosts` here. If you look at the code:
```
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
```

You can see that we loop over the ingress hosts and create rules based on those.
Ingress routing can work in two ways:
1. Route to the proper appropriate service based on the host you used to access it. For example, if you were trying to reach `jfmc.yourcompany.com` it would redirect to mission control. If you were trying to reach `artifactory.yourcompany.com` it would redirect to Artifactory.

2. Route to the appropriate backend service based on the url path. For example. if you were trying to reach with `10.1.2.3/jfmc`, it would redirect to mission control. If you were trying to reach `10.1.2.3/artifactory` it would redirect to artifactory.

**Comment by danielezer** [comment]
This PR ☝️ should help you with your issue. Nonetheless, you will still be required to provide either the `ingress.hosts` or the `ingressAdditionalRules`

**Comment by erick-duran** [comment]
@danielezer, I'm actually using `ingress.hosts`, here's all my Ingress config:
```yaml
ingress:
  enabled: true
  annotations:
    ... (cluster specific)
  hosts:
    - <url>
  tls:
    - hosts:
        - <url>
```

The PR will probably help, thanks! 👍
