### ISSUE TITLE
Setting configuration variable for Artifactory-HA heavy loads

### ISSUE THREAD

**Issue by lexual** [jfrog/charts#649]
Hi,

We have been experiencing some performance issues with our Artifactory installation, and are looking to tweak some of the settings set out here:

https://jfrog.com/knowledge-base/how-do-i-tune-artifactory-for-heavy-loads/

e.g. values in:
* $ARTIFACTORY_HOME/tomcat/conf/server.xml
* $ARTIFACTORY_HOME/etc/artifactory.system.properties

Is this possible with current helm charts?

**Comment by lexual** [comment]
If not, any short-term workaround ideas would be appreciated.

**Comment by eldada** [comment]
Hey @lexual . These tunings are possible. In the chart's values, there is a section that allows setting custom environment variables and extra java options.
This info uses features from [official Artifactory Docker image](https://www.jfrog.com/confluence/display/RTF/Installing+with+Docker#InstallingwithDocker-SupportedEnvironmentVariables).

In the chart's `values.yaml`, use `artifactory.extraEnvironmentVariables` for setting these variables.
The content of `artifactory.system.properties` can be replaced with command line system properties to java.
For the extra java opts, use a common `artifactory.javaOpts.other` or specific primary/node settings with `artifactory.primary.javaOpts.other` and `artifactory.node.javaOpts.other` to pass the needed system property like `-Dartifactory.access.client.max.connections=100`.

**Comment by danielezer** [comment]
To conclude, it would be something like the following:
```
artifactory:
  extraEnvironmentVariables:
    - name: SERVER_XML_ARTIFACTORY_MAX_THREADS
       value: "200"
    - name: SERVER_XML_ACCESS_MAX_THREADS
      value: "50"
    - name: DB_POOL_MAX_ACTIVE
      value: "300"

  javaOpts:
    other: "-Dartifactory.async.poolMaxQueueSize= 100000 -Dartifactory.http.client.max.total.connections=100 -D
```

You can look at the (values.yaml)[https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L329] as a reference to the `extraEnvironmentVariables`
