### ISSUE TITLE
artifactory - can I use ingress sub path ?

### ISSUE THREAD

**Issue by Hokwang** [jfrog/charts#653]
Hello.

I want to use artifactory with https://my.company.com/artifactory-stage URL.

Is it possible?
(using including docker registry case or excluding docker registry case)

I can't deploy with sub path, can you provide simple example?

my values.yaml is
```
ingress:
  enabled: true
  defaultBackend:
    enabled: false
  hosts:
    - nwse.sec.samsung.net
  path: /artifactory-stage
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url : "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(v2)/token /$2/artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /$2/artifactory/api/docker/$2/$1/$3;
  tls:
    - secretName: ingress-tls
      hosts:
        - my.company.com

artifactory:
  image:
    repository: "docker.bintray.io/jfrog/artifactory-oss"
  masterKey: 5a406dd12321a3832c25532c0893630ce3657a89a52c7978ed8237bc75aa1744
  joinKey: 5a406dd12321a3832c25532c0893630ce3657a89a52c7978ed8237bc75aa1744

  accessAdmin:
    ip: "*"
    password: "1qaz2wsx"

  persistence:
    enabled: true
    storageClass: "nfs-client-stage"

nginx:
  enabled: false

postgresql:
  postgresqlPassword: "1qaz2wsx"
  persistence:
    enabled: false
```

When I access my.company.com/artifactory-stage, it moved to my.company.com/artifactory and return 404 not found error.

**Comment by Hokwang** [comment]
I found out ingress.path does not work.

```
$ k get ing artifactory-stage-artifactory -n artifactory-stage -o yaml
<snip>
spec:
  rules:
  - host: nwse.sec.samsung.net
    http:
      paths:
      - backend:
          serviceName: artifactory-stage-artifactory
          servicePort: 8082
        path: /
      - backend:
          serviceName: artifactory-stage-artifactory
          servicePort: 8081
        path: /artifactory/
```

I guess this is bug.

**Comment by Hokwang** [comment]
@danielezer can you helm me?

**Comment by danielezer** [comment]
@Hokwang You can try something like the following https://github.com/jfrog/charts/issues/306#issuecomment-520211341. Let me know if it works

**Comment by Hokwang** [comment]
@danielezer 
.Values.nginx.externalPortHttp is deprecated and I don't use nginx.
```
nginx:
  enabled: false
```
so serviceName and servicePort does not match.

**Comment by danielezer** [comment]
Try to change it to the artifactory service name and the artifactory external service port

**Comment by Hokwang** [comment]
I did run below commands,
```
# cat myvalue.yaml
ingress:
  enabled: true
  defaultBackend:
    enabled: false
  hosts:
    - my.company.net
  path: /artifactory-stage
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
    - secretName: ingress-tls
      hosts:
        - my.company.net

artifactory:
  image:
    repository: "docker.bintray.io/jfrog/artifactory-pro"
    license:
      secret: artifactory-license
      dataKey: art.lic
  masterKey: 5a406dd12321a3832c25532c0893630ce3657a89a52c7978ed8237bc75aa1744
  joinKey: 5a406dd12321a3832c25532c0893630ce3657a89a52c7978ed8237bc75aa1744

  accessAdmin:
    ip: "*"
    password: "1qaz2wsx"

  persistence:
    enabled: false

nginx:
  enabled: false

postgresql:
  postgresqlPassword: "1qaz2wsx"
  persistence:
    enabled: false

# helm install artifactory-stage -n artifactory-stage -f artifactory-stage-values.yaml jfrog/artifactory
# k get ing -n artifactory-stage 
NAME                            HOSTS                  ADDRESS   PORTS     AGE
artifactory-stage-artifactory   nwse.sec.samsung.net             80, 443   30s

# k edit ing artifactory-stage-artifactory -n artifactory-stage
<snip>
spec:
  rules:
  - host: my.company.net
    http:
      paths:
      - backend:
          serviceName: artifactory-stage-artifactory
          servicePort: 8082
        path: /
      - backend:
          serviceName: artifactory-stage-artifactory
          servicePort: 8081
        path: /artifactory/
      - backend:
          serviceName: artifactory-stage-artifactory
          servicePort: 8082
        path: /webapp
```
8082 / and 8081 /artifactory/ is created automatically. I added 8082 /webapp
Do you mean this spec?
Anyway still not works and I tried to change this spec so many times but no luck.

**Comment by Hokwang** [comment]
@danielezer can you test this?

**Comment by danielezer** [comment]
@Hokwang Hey, sorry for the delay in my response. I have tried achieving what you are aiming for and I managed to do it with the following `values.yaml`:
```
ingress:
  enabled: true
  defaultBackend:
    enabled: false
  hosts:
    - my.company.net
  path: /artifactory-stage
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite "(?i)/artifactory-stage(/|$)(.*)" /$2 break;

  additionalRules: |
    - host: my.company.net
      http:
        paths:
          - path: /artifactory-stage
            backend:
              serviceName: {{ template "artifactory.fullname" . }}
              servicePort: {{ .Values.artifactory.externalPort }}

```

Please let me know if it works out for you

**Comment by Hokwang** [comment]
Thanks for your kind reply, but I didn't make it success. I gave up.
my last value.yaml is
```
ingress:
  enabled: true
  defaultBackend:
    enabled: false
  hosts:
    - my.company.net
  routerPath: /artifactory-stage/
  artifactoryPath: /artifactory-stage/artifactory
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite "(?i)/artifactory-stage(/|$)(.*)" /$2 break;
  tls:
    - secretName: ingress-tls
      hosts:
        - my.company.net
```
