### ISSUE TITLE
Chart Artifactory 9.0.23 volumeClaimTemplate error on fresh installation (and migration) when artifactory.persistence.existingClaim is used

### ISSUE THREAD

**Issue by ahs-dev** [jfrog/charts#671]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: Kubernetes 1.17,2, Rancher 2.3.3/2.3.5 (instead of Helm)

**Which chart**: artifactory-9.0.23

**What happened**:

When artifactory.persistence.existingClaim is set to refer to a pre-configured persistentVolumeClaim both a fresh installation and a migration (from chart artifactory-8.5.1) fail.

(fresh installation)

```
create Claim artifactory-volume-artifactory-artifactory-0 for Pod artifactory-artifactory-0 in
StatefulSet artifactory-artifactory failed error: PersistentVolumeClaim "artifactory-volume-artifactory-artifactory-0"
is invalid: [spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Required value]
```

(migration)
```
Failed to install app artifactory. Error: UPGRADE FAILED: StatefulSet.apps "artifactory-artifactory" is invalid: spec:
Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden 
```

**What you expected to happen**:
Should work identical to chart version artifactory-8.5.1 where the volumeClaimTemplates segment within the template artifactory-statefulset.yaml is removed when artifactory.persistence.existingClaim is set

**How to reproduce it** (as minimally and precisely as possible):
create namespace artifactory and within create the following:
create pvc artifactory-content (bound to pv)
create pvc artifactory-postgresql (bound to pv)
create secret artifactory-masterkey (key: master-key)
create secret artifactory-joinkey (key: join-key)
create secret artifactory-postgresql (key: postgresql-password)

install chart artifactory-9.0.23 into namespace artifactory with the following configuration

```
artifactory:
  masterKeySecretName: artifactory-masterkey
  joinKeySecretName: artifactory-joinkey
  persistence: 
    existingClaim: artifactory-content
nginx: 
  enabled: false
  mainConf: "empty"
  artifactoryConf: "empty"
postgresql:
  existingSecret: artifactory-postgresql
  persistence: 
    existingClaim: artifactory-postgresql
```

**Anything else we need to know**:

The volumeClaimTemplates segment in chart version 8.5.1 is guarded as follows:

```
{{- with .Values.artifactory.persistence }}
  {{- if and .enabled (not .existingClaim) }}
  volumeClaimTemplates:
  - metadata:
      name: artifactory-volume
  [...]
  {{- end }}
{{- end }}
```

which was changed in the 9.0.X charts to

```
  volumeClaimTemplates:
  {{- if .Values.artifactory.persistence.enabled }}
  - metadata:
      name: artifactory-volume
    {{- if not .Values.artifactory.persistence.existingClaim }}
    spec:
      [...]
    {{- end }}
  {{- end }}
```

i.e. the segment is always present, but empty
