### ISSUE TITLE
[artifactory-ha] values.yaml formatting causes syntax highlighting issues in vscode

### ISSUE THREAD

**Issue by TJM** [jfrog/charts#687]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug, but it might not be  :)

**Version of Helm and Kubernetes**: v3.1.1 / v1.15.2

**Which chart**: artifactory-ha 2.0.31 (could also affect others)

**What happened**: I opened the values.yaml file in vscode to see what the defaults were and for documented examples, but the syntax highlighting was confused by the comment style on the lines that use a yaml block style indicator without a block, which makes it harder to read.

* ![Without Spaces - color is incorrect](https://user-images.githubusercontent.com/1641316/76906627-0224a700-686a-11ea-9da0-c988cf6850eb.png)

**What you expected to happen**: I expected the colors to work

* ![With spaces, the color looks as expected](https://user-images.githubusercontent.com/1641316/76906675-1d8fb200-686a-11ea-96d6-1c045a1a97f4.png)

**How to reproduce it** (as minimally and precisely as possible):
Open values.yaml in vscode (see attached screenshots), I am willing to admit this could be a vscode bug, but I will start here first.

**Anything else we need to know**:
Adding a two space indent before the comment (hash) fixes the issue, for example ...

```yaml
some_key: |
# comment1
# comment2
another_key: value
```

... confuses things, however, if you add the two spaces like:

```yaml
some_key: |
  # comment1
  # comment2
another_key: value
```

The highlighting works as expected.

However, that may not "work" as intended. If the intent was to have an "empty" string, perhaps it would be better to have `null` or `""`  or just comment the key out entirely? (that may actually cause other issues). I think its fairly well understood that people need to remove the `{}` (empty hash), so maybe `""` would be a good option, then comment out the entire example like:

```yaml
some_key: ""
# some_key: |
#   comment1
#   comment2
another_key: value
```

Interestingly, GitHub's parser seems to handle either style.

REF: https://yaml-multiline.info/
