### ISSUE TITLE
[artifactory] Use postgresqlExtendedConf instead of postgresqlConfiguration

### ISSUE THREAD

**Issue by lwj5** [jfrog/charts#693]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**:
-

**Which chart**:
2.0.13

**What happened**:
Don't use `postgresqlConfiguration`, use `postgresqlExtendedConf` instead as it will interfere with other chart configuration. 

For example if replication is enabled, by using postgresqlConfiguration it will prevent slaves from replicating with the master as max_wal_senders=0
```
 postgresql:
   enabled: true
   postgresqlConfiguration:
     listenAddresses: "'*'"
     maxConnections: "1500"

```
**What you expected to happen**:
-

**How to reproduce it** (as minimally and precisely as possible):
-

**Anything else we need to know**:
-
