### ISSUE TITLE
[artifactory] chart 9.2.1 (and older) masterKeySecretName is not used correctly

### ISSUE THREAD

**Issue by ahs-dev** [jfrog/charts#735]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Kubernetes: 1.17,4, Rancher: 2.3.3/2.3.5, Helm: 3.11

**Which chart**: artifactory chart 9.2.1 (and older) 

**What happened**: "Master key is missing."

**What you expected to happen**: Master Key is taken from existing secret via masterKeySecretName 

**How to reproduce it** (as minimally and precisely as possible):
create namespace artifactory and within create the following:
create pvc artifactory-content (bound to pv)
create pvc artifactory-postgresql (bound to pv)
create secret artifactory-masterkey (key: master-key)
create secret artifactory-joinkey (key: join-key)
create secret artifactory-postgresql (key: postgresql-password)

install chart artifactory-9.2.1 into namespace artifactory with the following configuration

```
artifactory:
  masterKeySecretName: artifactory-masterkey
  joinKeySecretName: artifactory-joinkey
  persistence: 
    existingClaim: artifactory-content
nginx: 
  enabled: false
  mainConf: "empty"
  artifactoryConf: "empty"
postgresql:
  existingSecret: artifactory-postgresql
  persistence: 
    existingClaim: artifactory-postgresql
```

```
Master key is missing. Pending for 5 seconds with 60 seconds timeout 
Master key is missing. Pending for 15 seconds with 2m0s timeout 
Master key is missing. Pending for 15 seconds with 2m0s timeout [init] 
Configuration data wasn't found in db. Loading defaults 
Service id initialized: jfac@01e4dxe85atsgg00v06dxw1pz3 
No master.key supplied. Generating master.key 
Saving master.key to /opt/jfrog/artifactory/var/etc/security/master.key 
```

**Anything else we need to know**:

Looking at the chart templates for version 9.2.1 and cannot find any location where the secret is actually read. I can find the text 'masterKeySecretName' eight times, where seven times it is for documentation purposes. The only template use is in templates\artifactory-secrets.yaml
where it just supresses the creation of a duplicate 'master-key' entry.

Currently we execute the installation by setting artifactory.masterKey to the same value.
