### ISSUE TITLE
Initcontainer fail trying to mount custom volume

### ISSUE THREAD

**Issue by rdcarrera** [jfrog/charts#831]
## BUG Report
**Version of Helm and Kubernetes**: 

**k8s**: Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
**helm**: Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

**Which chart**: 
artifactory:9.4.1

**What happened**:
After the upgrade of the helm chart, the initContainer migration-artifactory doesn't start because it tries to mount a file that doesn't exist yet.
```
Error: failed to start container "migration-artifactory": 
Error response from daemon: OCI runtime create failed: 
....
docker/overlay2/d3af7ea30d87b.........368aa8c8c5fad4/
merged/opt/jfrog/artifactory/app/third-party/java/lib/security/cacerts\\\" 
caused \\\"not a directory\\\"\"": unknown: 
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**How to reproduce it** (as minimally and precisely as possible):
- You need a configmap with the ca certificates: _external-ca_  and 2 differents key/value with the certificates:
  - rdcarrera.pem
  - kubernetes.pem
```
---
artifactory:
 customVolumeMounts: |
    - name: artifactory-cacerts
      mountPath: "/opt/jfrog/artifactory/app/third-party/java/lib/security/cacerts"
      subPath: cacerts
  customVolumes: |
    - name: artifactory-cacerts
      emptyDir: {}
    - name: external-ca
      configMap:
        name: external-ca
  customInitContainers: |
    - name: "trust-ca-certificate"
      image: "rdcarrera/add-ca-to-cacert"
      imagePullPolicy: IfNotPresent
      env:
      - name: CACERT_DEST
        value: "/dest"
      - name: CERTS_FOLDER
        value: "/certs"
      volumeMounts:
      - name: artifactory-cacerts
        mountPath: /dest
      - name: external-ca
        mountPath: /certs/rdcarrera.pem
        subPath: rdcarrera.pem
      - name: external-ca
        mountPath: /certs/kubernetes.pem
        subPath: kubernetes.pem
      securityContext:
        privileged: true
        runAsUser: 0
```

**Anything else we need to know**: 
I think to solve this issue, my initContainer must run first to create the cacert file. 

**Commit**:
[Adding customVolumeMounts for initContainers](https://github.com/jfrog/charts/commit/05f234ca8bd4ba26e2dcd5dca3ed2fee9ea1bc12#diff-b720cd1e3be456a7c60d6bc0513e20b2)

*Thanks & Regards!*

**Comment by Satheesh-Balachandran** [comment]
@rdcarrera I think it is because you are trying to mount a directory to the file "cacerts". This would not only fail in the initcontainer and also in the artifactory container. If you are trying to mount the external CA to the container, please use the extra_java_opts like below in the [system.yaml](https://github.com/jfrog/charts/blob/a8c77e91c3761c161acd46ca43bbabe7ce0b32b4/stable/artifactory/values.yaml#L356) and mount the file to the /var/opt/jfrog/artifactory/etc/cacerts

-Djavax.net.ssl.trustStore=/var/opt/jfrog/artifactory/etc/cacerts -Djavax.net.ssl.trustStorePassword=changeit

**Comment by rdcarrera** [comment]
Hi @Satheesh-Balachandran,

Actually, with previous version of the artifactory helm-charts, this method works.

![Captura de pantalla de 2020-04-21 10-45-05](https://user-images.githubusercontent.com/26046280/79845728-caa3a000-83bd-11ea-8978-f3bc1ddc0afd.png)
![Captura de pantalla de 2020-04-21 10-45-25](https://user-images.githubusercontent.com/26046280/79845749-d0998100-83bd-11ea-9c8f-2f4d9b25348a.png)
![Captura de pantalla de 2020-04-21 10-45-46](https://user-images.githubusercontent.com/26046280/79845756-d2fbdb00-83bd-11ea-99a2-1cb1ab4ad898.png)

```
---
containers:
  - command:
    - /bin/bash
    - -c
    - |
      set -e; if [ -d /artifactory_extra_conf ] && [ -d /artifactory_bootstrap ]; then
        echo "Copying bootstrap config from /artifactory_extra_conf to /artifactory_bootstrap";
        cp -Lrfv /artifactory_extra_conf/ /artifactory_bootstrap/;
      fi; exec /entrypoint-artifactory.sh
    env:
    - name: JF_SHARED_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: artifactory-postgresql
    image: docker.bintray.io/jfrog/artifactory-pro:7.4.1
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - |
            echo;
    livenessProbe:
      failureThreshold: 10
      httpGet:
        path: /router/api/v1/system/health
        port: 8082
        scheme: HTTP
      initialDelaySeconds: 180
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: artifactory
    ports:
    - containerPort: 8082
      protocol: TCP
    - containerPort: 8081
      protocol: TCP
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /router/api/v1/system/health
        port: 8082
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/opt/jfrog/artifactory
      name: artifactory-volume
    - mountPath: /artifactory_bootstrap/binarystore.xml
      name: binarystore-xml
      subPath: binarystore.xml
    - mountPath: /artifactory_bootstrap/artifactory.lic
      name: artifactory-license
      subPath: artifactory.lic
    - mountPath: /artifactory_bootstrap/info/installer-info.json
      name: installer-info
      subPath: installer-info.json
    - mountPath: /opt/jfrog/artifactory/app/third-party/java/lib/security/cacerts
      name: artifactory-cacerts
      subPath: cacerts
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: artifactory-artifactory-token-n8dkd
```

If we change the method of the cacerts generation we lost the possibility to automatically add new ca certificates on runtime only adding new keys on the configmap, but, if it's the only way we will move to this method
