### ISSUE TITLE
Tomcat maxThreads / acceptCount

### ISSUE THREAD

**Issue by DNewt** [jfrog/charts#898]
**Sorry if this feature already exists, I think the way this was managed has changed in Artifactory 7.x**

**Is this a request for help?**:
Yes

This is a
**Feature Request**

I would like to be able to update the Tomcat values for maxThreads for both Access and Artifactory.

As recommended in this document: https://jfrog.com/knowledge-base/how-do-i-tune-artifactory-for-heavy-loads/ it needs to be tuned for heavy loads. 

This document also mentions Tomcat acceptCount 
https://jfrog.com/whitepaper/best-practices-for-managing-your-artifactory-database/
I have yet to find a value in my Artifactory config representing this - so I am unsure if it is still a thing in Artifactory 7.x

**Which chart**:
artifactory-ha

**Comment by chukka** [comment]
@DNewt  maxThreads/acceptCount can be configured via systemyaml in values.yaml

For Example :

```
artifactory:
      database:
        maxOpenConnections: {{ .Values.artifactory.database.maxOpenConnections }}
      tomcat:
        connector:
          maxThreads: 200
          extraConfig: "acceptCount=\"100\""
access:
      database:
        maxOpenConnections: {{ .Values.access.database.maxOpenConnections }}
      tomcat:
        connector:
          maxThreads: 200
          extraConfig: "acceptCount=\"100\""

```
