### ISSUE TITLE
Cluster join: Service registry ping failed; context deadline exceeded

### ISSUE THREAD

**Issue by leylmordor** [jfrog/charts#986]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

**Which chart**:
Latest Chart

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: artifactory
  namespace: artifactory
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: artifactory
  chart:
    git: git@github.com:jfrog/charts.git
    path: stable/artifactory-oss
    ref: master
  values:
    artifactory:
      artifactory:
        image: 
          repository: docker.bintray.io/jfrog/artifactory-oss
        service:
          type: NodePort
        annotations:
          vault.security.banzaicloud.io/vault-addr: ''https://subdomain.domain.dev''
          vault.security.banzaicloud.io/vault-role: deployinator
      nginx: 
        enabled: false
      postgresql:
        enabled: true
        master:
          podAnnotations:
            vault.security.banzaicloud.io/vault-addr: 'https://subdomain.domain.dev'
            vault.security.banzaicloud.io/vault-role: somerole
        postgresqlPassword: 'path/postgres#password'
        postgresqlUsername: artifactory
        serviceAccount:
          enabled: true
          name: kubernetes-vault-auth-sa
      serviceAccount:
        create: false
        name: kubernetes-vault-auth-sa
      ingress:
        default:
          backend: enabled
        enabled: true
        annotations:
          kubernetes.io/ingress.allow-http: 'false'
          kubernetes.io/ingress.global-static-ip-name: artifactory-external-ip
          networking.gke.io/managed-certificates: artifactory-managed-cert
    postgresql:
      enabled: true
```

**Anything else we need to know**:
